### ISSUE TITLE
Responsive Design Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#10]
@atjonathan is in charge of coordinating the expansion of these challenges, but he needs your help.

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

Here are the challenges we have currently planned (these can be further expanded):

- [x] Create a Media Query
 - [x] Set a Responsive Breakpoint
 - [x] Create a Compound Media Query
- [x] Make an image responsive
- [x] Use a retina image
- [x] Make typography responsive

**Comment by atjonathan** [comment]
I will lead as topic owner for this section.

**Comment by atjonathan** [comment]
**Create a Media Query**

_**Description:**_
Media Queries are a new technique introduced in <code>CSS3</code> that let the presentation of content be changed for a specific viewport only.
They consist of a [media type](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) and if that media type matches the type of device the document is being displayed on, the styles will be applied. Here is an example of a media query that returns the content when the device's width is under <code>100px</code>:

```css
@media (max-width: 100px) {}
```

**Remember** The css inside the media query will only be displayed if the media type matches the one of the device being used.

Add a media query, so that the `p` tag will have the font size of 10px when the device's height is smaller than 800px.

_**Tests:**_
```js
assert($("img").css('font-size') == '10px', 'message: Your <code>p</code> tag should have the font size of <code>10px</code> when the device's height is smaller than <code>800px</code>.'),
```

_**Initial Seed Code:**_
```html

<style>

</style>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tempus massa. Aenean erat nisl, gravida vel vestibulum cursus, interdum sit amet lectus. Sed sit amet quam nibh. Suspendisse quis tincidunt nulla. In hac habitasse platea dictumst. Ut sit amet pretium nisl. Vivamus vel mi sem. Aenean sit amet consectetur sem. Suspendisse pretium, purus et gravida consequat, nunc ligula ultricies diam, at aliquet velit libero a dui.</p>
```

_**Solution:**_
```html

<style>

  @media (max-height: 800px) {
    p {
      font-size: 10px;
    }
  }

</style>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tempus massa. Aenean erat nisl, gravida vel vestibulum cursus, interdum sit amet lectus. Sed sit amet quam nibh. Suspendisse quis tincidunt nulla. In hac habitasse platea dictumst. Ut sit amet pretium nisl. Vivamus vel mi sem. Aenean sit amet consectetur sem. Suspendisse pretium, purus et gravida consequat, nunc ligula ultricies diam, at aliquet velit libero a dui.</p>
```

**Comment by atjonathan** [comment]
**Make an image responsive**

_**Description:**_
Making images responsive in <code>CSS</code> is actually very simple.
Instead of applying an absolute width to an element e.g.
```css
img { width: 720px; }
```
you can use:
```css
img { max-width: 720px; width: 100%; }
```

<code>max-width</code> prevents the width being larger than <code>720px</code> and <code>width: 100%</code> makes sure the width isn't larger than the viewport size (100%).

Set the max width of the <code>img</code> tag to <code>300px</code>.

_**Tests:**_
```js
assert($("img").css('max-width') == '300px', 'message: Your <code>img</code> tag should have the max width of <code>300px</code>.'),
```

_**Initial Seed Code:**_
```html

<style>

</style>

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1000px-Google_%22G%22_Logo.svg.png" alt="Google's logo" />
```

_**Solution:**_
```html

<style>

  img {
    max-width: 300px;
    width: 100%;
  }

</style>

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1000px-Google_%22G%22_Logo.svg.png" alt="Google's logo" />
```

**Comment by atjonathan** [comment]
**Use a retina image**

_**Description:**_
The simplest way to make your images appear "retina" is to define your width and height as only half of what the original file is.
Here is an example of an image that is only using half of the original height and width:

```html
<style>
	img { height: 250px; width: 250px; }
</style>

<img src="https://bit.ly/chrome500x500" alt="Google Chrome's Logo" />
```

_**Instructions**_
Set the width and height of the <code>img</code> tag to half of what they originally where. In this case, the original height was <code>200px</code> and the original width was <code>200px</code>.

_**Tests:**_
```js
assert($("img").width() == '100px', 'message: Your <code>img</code> tag should have the width of <code>100px</code>.'),
assert($("img").height() == '100px', 'message: Your <code>img</code> tag should have the height of <code>100px</code>.')
```

_**Initial Seed Code:**_
```html

<style>

</style>

<img src="https://bit.ly/bigben200x200" alt="Big Ben" />
```

_**Solution:**_
```html

<style>
	img {
    	width: 100px;
        height: 100px;
    }
</style>

<img src="https://bit.ly/bigben200x200" alt="Big Ben" />
```

**Comment by atjonathan** [comment]
**Make typography responsive**

_**Description:**_
Instead of using <code>em</code> or <code>px</code> we can use Viewport units for responsive typography. Viewport units differ from percentages because they use e.g. the width of the viewport instead of the parent container.

The four different viewport units are:
- <code>vw</code> : <code>10vw</code> would be 10% of the viewport's width.
- <code>vh</code> : <code>3vh</code> would be 3% of the viewport's height.
- <code>vmin</code> : <code>70vmin</code> would be 70% of the viewport's smaller dimension.
- <code>vmax</code> : <code>100vw</code> would be 100% of the viewport's bigger dimension.

_**Instructions:**_
Set the width of the <code>h2</code> tag to 80% of the viewport's width.
_**Tests:**_
```js
assert($("h2").width() == '80vw', 'message: Your <code>h2</code> tag should have the width of <code>80vw</code>.')
```

_**Initial Seed Code:**_
```html

<style>

</style>

<h2>Bonjour</h2>
```

_**Solution:**_
```html

<style>
	h2 {
    	width: 80vw;
    }
</style>

<h2>Bonjour</h2>
```

**Comment by Greenheart** [comment]
@atjonathan I just noticed this:
> vmax : **100vw** would be 100% of the viewport's bigger dimension

**100vw** should be **100vmax**

**Comment by atjonathan** [comment]
@Greenheart thanks :smiley:

**Comment by QuincyLarson** [comment]
I'm closing this challenge and seeding these in. I will update #46 as I build these seed files.

**Comment by HKuz** [comment]
I'm considering this as a WIP - any input on the 'mobile first' sentences at the end of paragraph 1 is appreciated. 

#### Intro
Today there are many types of devices that can access web content. These range from large desktop computers to small mobile phones. Many of these devices have different screen sizes, resolution, and processing power. Responsive Web Design is the approach to make a web project viewable in response to the device that displays it. The page structure and CSS rules should be flexible to accommodate these differences. In general, design the page's CSS to your target audience. If the expected traffic to your website is from mobile users, take a 'mobile-first' approach. Then add conditional rules for larger screen sizes. If your visitors are desktop users, then design for larger screens with conditional rules for smaller sizes.

CSS provides utilities for a web developer to write different style rules and apply them depending on the device. This section will cover the basic ways to use CSS for Responsive Web Design.

**Comment by QuincyLarson** [comment]
@hkuz Thanks for sharing this. Responsive design is quite challenging to explain, and you've succeeded in doing so.

I've re-written it slightly to for clarity, make it second person, and break paragraphs up (people are much more likely to read short paragraphs and skip long ones):

---

Today, there's a wide range of devices that can access the web. These range from large desktop computers to small mobile phones. These devices have different screen sizes, resolutions, and processing power. 

Responsive Web Design is an approach to designing web content that respond to the constraints of different devices. The page structure and CSS rules should be flexible to accommodate these differences. 

In general, design the page's CSS to your target audience. If you expect most of your traffic to be from mobile users, take a 'mobile-first' approach. Then add conditional rules for larger screen sizes. If your visitors are desktop users, then design for larger screens with conditional rules for smaller sizes.

CSS gives you tools to write different style rules, then apply them depending on the device. This section will cover the basic ways to use CSS for Responsive Web Design.

--- 

I recommend doing something similar to the other intros when time permits.

**Comment by HKuz** [comment]
@QuincyLarson this looks great! I'll get it in the next iteration. I'll fix the other few to break up for readability, too. By the way, the web comic didn't look too bad for the Regex section when I ran it locally. It just needed some formatting to align it better.

**Comment by QuincyLarson** [comment]
@HKuz great! Yes - we may need to create a special view for these intro sections instead of using slide challenges. I image a two-column layout would be superior if we're showing smaller web comics and more text.

**Comment by QuincyLarson** [comment]
@HKuz I think we could update the "make an image responsive" to involve using:

img{
  max-width: 100%;
  display: block; 
  height: auto;
}

This is the more text-book way to accomplish this, and will have better results than the approach used in the initial challenge. Could you update the challenge and tests accordingly?

**Comment by HKuz** [comment]
@QuincyLarson - no problem, I've got it updated locally, so it'll be in the next iteration of the curriculum expansion branch.

**Comment by ZokiMar** [comment]
solution to https://github.com/freeCodeCamp/CurriculumExpansion/issues/10#issuecomment-239407872: 

<style>
  
  h2 {
      width: 80vw;
  }

  p {
      width: 75vmin;
  }
</style>
