### ISSUE TITLE
Learn Testing Basics by Building a Recipe Ingredient Parser

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#100]

**Comment by brandenbyers** [comment]
@QuincyLarson What do you mean by a Fact Checker? As in what a human does when fact checking journalism? Or something simpler like checking the "facts" of a website or checking some kind of array of facts?

**Comment by QuincyLarson** [comment]
@brandenbyers I was naively thinking something that check for the presence of numbers to and maybe superlative words in statements. If you can come up with a better project idea to teach people testing, I would welcome it.

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, just checking in to see how things are going. Were you able to start on this project? If not, did you have another idea for a project to teach testing?

**Comment by brandenbyers** [comment]
I have a tentative idea that I'm planning to work on but available time has been slipping away from me. I'm hoping to get something submitted this week though!

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, okay! Looking forward to it.

**Comment by scissorsneedfoodtoo** [comment]
Hi @brandenbyers, just wanted to check in and see how things are going with your prototype. Is there anything we can help with?

**Comment by brandenbyers** [comment]
Sorry this keeps slipping. 😔 My idea, that I still haven't had time to develop, is as follows:

Instead of a fact checker, I'm thinking we focus on a recipe ingredient parser. Then, break this testing lesson up into two parts (either one lesson with two parts or two lessons). One part focuses on the "happy path" and the other focuses on the "not so happy and kind of scary path."

Testing the happy path will include looking at and testing examples like this:

```
1 cup flour
2 cups brown sugar
1 teaspoon salt
2 fluid ounces water
```

With the expected results for `1 cup flour` returned in json:

```
{
	"ingredient": {
		"quantity": 1,
		"unitOfMeasurement": "cup",
		"ingredient": "flour"
	}
}
```

Through a series of walkthrough tests, an understanding of how to write tests will be explained.

Taking the user down the happy path is an important journey. But the not-so-happy path is equally important and provides insights on how to think about edge cases. It may also raise questions in regard to how many edge cases should be included to consider testing complete?

This not-so-happy path may include input like this:

```
1.5 cups flour
2 cups and 2 tablespoons water
1 tablespoon (10 grams) sea salt
4-5 tablespoons oil
1 to 2 teaspoons pepper
3 15 ounce cans of garbanzo beans
```

As is hopefully highlighted in the the list above, certain edge cases may not have been considered in development. Or even if they were already considered in development, it is equally important to test for these edge cases. And to emphasize that without automated tests covering these edge cases, some future developer (or your future self) could change something that breaks one of these edges without realizing it.

---

The main thing holding me back at this time is time itself. Before taking on this commitment I had adequate time to complete this, but soon after have been given a lot more commitments at work and home. I still plan to complete this relatively soon unless I'm holding back someone else that wants to complete it.

The main help I could use at this time is links to some of the finished challenges that best fit the flow of this challenge. I haven't had a chance to dig through any completed PRs to really see how these challenges are being coded.

And last bit of help would be confirming that this idea is, in fact, going in the right direction. Thanks!

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, awesome! @QuincyLarson and I both agree that a recipe ingredients parser is an excellent idea to teach testing. By the way, I had no idea you wrote a cookbook and have a podcast! Seems like a recipe parser is right up your alley. And don't worry, you aren't holding up the project in any way. Feel free to work on it whenever you have some free time!

Right now the best project to look at is the [RPG Game](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/basic-javascript-role-playing-game) @beaucarnes developed. Right now we're just focused on breaking each project down into small steps with short test descriptions to instruct students along the way. In the RPG Game, Beau does a really great job keeping the test descriptions short and informative, even without a lot of explainer text or jargon. That project is meant for beginners, though. If you check Quincy's announcement about the [new curriculum](https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546), your project will be in the middle of a much later section, Learn Information Security and Quality Assurance. Students won't need as much hand holding by then, though we would still like to break the steps down as granularity as possible.

Do you have some time to hop on a call for 20 or 30 minutes? I'd be happy to talk more about this project with you before you start working on a prototype.

**Comment by brandenbyers** [comment]
Thanks for the RPG Game recommendation. I'll take a look at that. And yes, I could do a call next week if that works for you.

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, no problem. And I'll send you a calendar invite for sometime next week. Looking forward to talking with you!

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, I sent you an email using the contact form on brandenbyers.com. Not sure if you'll see that or this message first, so please email me at kris@freecodecamp.org whenever you can.

**Comment by QuincyLarson** [comment]
Hey @brandenbyers I hope your summer is going great. Have you had a chance to think more about this project? Let me know if I can do anything to help. This is one of the most important projects in the entire curriculum and I am stoked to see what you do with it.

**Comment by brandenbyers** [comment]
Hey! Sorry this message slipped by. I have definitely still had this on my mind, but it was an unexpectedly busy spring. I have an big event I'm organizing that takes place at the end of July, so I've had to push off the actual implementation of this again. But I'm very serious when I say this is at the TOP of my list of priorities come the beginning of August. Sorry that time slipped away.

I have nearly all of the test case examples scattered around in various notes. And I have the basic gist of the story for the lesson(s). The one place I am still stumped is how to automate the verification process. How do we test the tests?

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, no problem, thank you for the update. Glad to hear that you have example test cases and a story in mind.

I don't think you need to worry about how to automate verifying the tests now -- that's something we can figure out on our end later. For the current [Quality Assurance with Chai](https://learn.freecodecamp.org/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai) section, we use an API to parse and verify the learner's tests. But since we want these new projects to work offline, my guess is that we'll use regex to verify whatever the learner writes and will mock the results or errors thrown by the test suite. Maybe @raisedadead can weigh in on this.

Perhaps the best thing we can do now is to get a prototype project and all the test descriptions up. By then we should have a better idea of how to actually test the tests.

**Comment by scissorsneedfoodtoo** [comment]
Hi @brandenbyers, were you able to think more on this project and start getting all of your lesson ideas and notes together?

**Comment by brandenbyers** [comment]
Yes, I was. I should have something ready to share by the end of this week...finally!

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, awesome! Looking forward to seeing what you came up with :+1: :+1:

**Comment by brandenbyers** [comment]
I'm not certain how I should share what I have so far since it isn't a legitimate PR as this point. Let me know if you would like me to roll this into a PR anyway. Otherwise, I have a couple of gists to convey the basic gist of the lesson structure as it is written now:

Lesson text: https://gist.github.com/brandenbyers/86101570463339cc1100e398d5e3c740

Tests with example failures and passing results: https://gist.github.com/brandenbyers/816fc822d4cda5ff9beeb757167db8ce

Granted, I'm not sure if this is following enough with the fast paced lesson structure outlined months ago. Please let me know if this is going at all in the right direction or if I should plan to change everything.

One important bit is that this lesson is focusing on learning how to think like a tester more than regurgitating documentation on specific testing syntax (also emphasized in the lesson text linked above). In some ways, using a recipe ingredient parser under test is a very good way to learn about this. However, even though the edge cases are extremely diverse, the actual test cases that need to be written for this specific type of parser are repetitive. Is this ok? Or the wrong direction for what FCC needs?

I also have notes within the two gists about ideas of how to do the testing of the tests. This is still the biggest conundrum from my perspective. One thing I realized as I was writing this first draft of the lesson is that I need to actually write the recipe parser. And multiple iterations of it at different points that will actually fail specific types of tests. Let me know if you think this is a good plan. Thanks!

**Comment by scissorsneedfoodtoo** [comment]
@brandenbyers, I really enjoyed reading through your lesson text. Made me hungry to learn more about testing, and also just plain hungry.

This definitely seems to be headed in the right direction. While we did discuss a fast paced lesson structure, with each lesson having up to 5 or so sentences of descriptive text, I'm sure we could find creative ways to break the text you have into smaller lessons, all while keeping the narrative flow.

You bring up a good point about thinking like a tester -- I feel like that's exactly what we're going for with all of these projects. Teaching the fundamentals of testing and how to think like a tester is much more important than covering every Chai method. The repetition is totally fine, and will give learners a lot of practice writing basic tests. We can do things to ease the repetition quite a bit, like having students only write the first full object of ingredients early on, then giving them the code to copy and paste as they go through the rest of the project.

Testing the tests will certainly be the biggest problem. I've been trying to find a simple way to run the tests, or just a subset of the tests, and save it to a variable so we can actually write unit tests based on that. I have a very rough idea of how that might work here: https://codepen.io/scissorsneedfoodtoo/pen/WNewqry?editors=0011. Will need to do more, well, testing on fCC itself.

About the recipe parser, that's true, it will be good to have one so learners can see the changes as they write their tests. It could be a very simple one, though.

**Comment by brandenbyers** [comment]
I like the direction you're going with capturing the test cases and results. How strict do you think the evaluation of the tests would be? As in, does the user need to enter an exact test string in order for the lesson to pass?

I have been thinking more about a quasi mutation testing strategy for more open ended test coverage in the later tests. More to get the users thinking like testers. Maybe more open ended lessons (if I am understanding correctly, each segment is called a lesson?) towards the end that ask, "have you considered x?" With "x" being something with more than one gotcha to consider and test for. And then going quasi mutation testing to the extent that, behind the scenes, the pre-coded recipe parser still has bugs due to missing edge cases. From the backend lesson perspective, these bugs are known. We have a number of behind the scenes example tests that will fail; one test for each type of failure we're hoping the user will write a test for. These tests wouldn't need to be run at the time of the lesson (although they should be run against the recipe parse to ensure the recipe parser is failing as expected), only the final count of failures would need to be known.

Then, when the user writes their tests for the lesson and runs them, we're expecting x amount of failures from their tests. If we expect 5 failures, and their tests only produce 2, then we can assume they are missing expected test case coverage (either because they wrote a bad test, or just didn't write enough tests to cover all expected edge cases). We could then go as far as regexing the test cases, but it seems like it would be a challenge to comprehend what the user wrote in this kind of open ended strategy).

However, if we went that route, there would have to be a limit on how many times the user tried to re-write/add tests to match the failure count since it isn't a perfect system. The user could also circumvent the system by writing the same failing test 5 times unless we had an accurate way to regex or otherwise confirm the scope of the test. If the lessons went this route, then I'm imagining something like, "try to write tests to cover this topic of edge cases...", and then if they fail, "looks like you're missing a few tests...", and then if they fail again, then the expected tests are shown to them to self-check.

Again, not a perfect system by any means and I'm sure there have to be better ways to do this. But this is what I continue to struggle with figuring out how to confirm.

In the meantime, I'll get started on the actual recipe parser...

**Comment by scissorsneedfoodtoo** [comment]
Great, I'm glad to hear that I might be on to something. I'm in the process of writing tests for another project, and I'm hopeful that we'll be able to for find a good way to write tests for this project as well. 

Sorry for any confusion. I have a tendency to use the words "step" and "lesson" interchangeably when talking about these projects. It's my understanding that we'll be quite flexible in evaluating learner input for each lesson, checking for just one key change/addition/output each step along the way. We also won't be testing each part of what learners write like we currently do in some challenges. For example, if a learner is instructed to rewrite a function using fat arrow syntax but later rewrites it to use the older `function name()` style, the code will still pass if the function has the right properties, variables, or output. When the learner goes on to the next lesson, we'll use the "correct" seed file to populate the code editor. 

That's an interesting way we can handle some later lessons. While we'd try to stick closely to testing one thing at a time, I could see having tests much later that check for a certain number of failures. Like you mentioned, it would be possible to cheat the test for that lesson if learners just write the same failing test a handful of times. Hopefully we'll be able to capture the actual results of the test suite and parse those. From what I understand about the tests and instructions for these projects, we'll try to write them more as a guide than anything, and not worry so much about edge cases or possible cheaters.

As for the text that shows up in the console after failing a test, I'm not sure how that will work with the new platform. I imagine that it will work something like it does on the current production site, showing what sort of output is expected so they can self-check. I'm not sure that there will be alternate text if learners fail the same test multiple times. This is something I'll have to think about, too.

**Comment by Steffan153** [comment]
@scissorsneedfoodtoo I see this has the "help wanted" tag, so I'm wondering how I can help with this?

**Comment by scissorsneedfoodtoo** [comment]
@Steffan153, thanks for your patience. Yes, this project is open and we would appreciate your help.

Just to give you a bit context, originally the plan was to cover all aspects of testing with this single project. In the end we decided that there's too much to cover. Instead, we're planning to [break this section up](https://www.freecodecamp.org/news/python-curriculum/#-javascript-quality-assurance-10-projects-) further by having this project act as an introduction to testing.

First we would need a completed recipe parser (or any other completed project you think is more appropriate) to use as a base to write the tests. Would you be able to start on that and post a link to it on a platform like [CodeSandbox](https://codesandbox.io/)?

Also, if you'd like to hop on a call to talk more about this project, send me an email at kris@freecodecamp.org.

**Comment by mesporas1** [comment]
Hey @scissorsneedfoodtoo , I created a prototype "Garden" program that users can write basic tests against. The main idea is that the learner will be given some requirements and a program made according to those requirements. Then, the learner will write tests to verify the functionality. https://codesandbox.io/s/test-program-qldjt 

Let me know what you think about it and how it can be improved or expanded!

**Comment by Steffan153** [comment]
@scissorsneedfoodtoo I started on CodeSandbox, but it was way too slow, so I went to StackBlitz (It's way faster, and I like it better. It even hot reloads the preview which is handy.) I'm thinking something like this, but I'm not completely sure: https://stackblitz.com/edit/js-yejfpz

What do you think?

**Comment by Steffan153** [comment]
Alright, this one turns it into JSON. I think this fits this project well: https://stackblitz.com/edit/js-pm4kte

**Comment by scissorsneedfoodtoo** [comment]
@Steffan153, thank you for posting both of your prototypes. I'm sorry, I must have gotten some wires crossed by asking both you and @mesporas1 to work on this project.

We will probably go with @mesporas1's prototype for this project. After some internal discussion we realized that a recipe ingredient parser might be a bit too difficult to build and test, and will go for something that can be done with just a terminal for this beginner project.

There are several other testing projects projects available. Would you be interested in working on one of the other [open testing projects](https://github.com/freeCodeCamp/CurriculumExpansion/issues?q=is%3Aissue+is%3Aopen+testing)?

**Comment by scissorsneedfoodtoo** [comment]
@mesporas1, thank you for sending us your prototype. I've played around with it a bit and it seems like a great project to teach the basics of testing. I really like your garden idea, too -- it's a really novel idea and will be much more interesting to build than a test answer checker like we discussed before.

This looks like it's ready to be broken up into steps. I'll send you a calendar invite for later this week in case you have some time to hop on a quick call to discuss next steps.

**Comment by beaucarnes** [comment]
I like this project idea. I'm still not totally clear what part the user will be creating and what part will be given.

**Comment by mesporas1** [comment]
@beaucarnes , thanks for looking at my prototype! I was thinking that the users will primarily write the tests in the "tests" directory. The tests will be for the garden code that I wrote. The garden code will be provided to the user.

I was also thinking that I could purposefully put bugs in my garden code in the final version. The user can write tests, find the bugs according to the failing tests, and debug the code as they see problems. It's just an idea though. We don't necessarily have to do that.
