### ISSUE TITLE
Learn D3 by Building a Map of Earth

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#108]

**Comment by QuincyLarson** [comment]
@HKuz This is a tentative project idea - really anything that involves D3 would be a good project.

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, just wanted to check in and see how things are going with this project. Were you able to start working on a prototype?

**Comment by HKuz** [comment]
Hi @scissorsneedfoodtoo - just started digging into this one now that JSON is in good shape! I'm reviewing some D3 now (little rusty 😅 ) and creating an outline, and hope to start a skeleton project by the weekend 👍

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, sounds good! Really looking forward to seeing your project. It'll be good review for me since I forgot almost everything about D3!

**Comment by HKuz** [comment]
Alright, here's a skeleton of this project [here](https://hkuz.github.io/fCC_D3_CurrExp/), with code repo [here](https://github.com/HKuz/fCC_D3_CurrExp). I would have liked to have gotten a little farther along, but D3v5 threw me and the example code I was using a few curveballs 😅 .

This is a start / WIP, with the following things I want to add in:
- Find country data (like population) to also bind to the map
- Add tooltip functionality to display the country name and [population] data
- Color the countries based on that data to teach scales
- Add pan/zoom functionality (not critical, but seems like a common function in interactive maps)

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, looks great so far! Showed your prototype to @QuincyLarson and we're both looking forward to seeing what you do with this. He suggested that you include the world map JSON, along with whatever other data sets you'll use, in your project directory. We should be able to host everything on the platform, and it will be nice for students to open up those files and take a look at them.

Your ideas all sound good, and it would be great if you could find a way to include a bar graph somehow since that's a common use for D3.

**Comment by HKuz** [comment]
Alright - getting there on this one! I pulled population data from the World Bank, added the functionality above, and pulled both the JSON and population data files into the project. (That's a good call having it available for students to look at vs manipulating it blindly). Also, I was able to include a scale at the bottom so we can cover the main steps of tying an axis to a scale 👍 . Let me know if this is in good shape and I can start outlining how to break it down into each step ([project still here](https://hkuz.github.io/fCC_D3_CurrExp/), [code still here](https://github.com/HKuz/fCC_D3_CurrExp)). I may tweak some of the particulars as I dig into explaining each piece - never know when you realize a better way of doing things!

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, awesome! Everything looks great, especially scale and the tool tip which are really slick. I'm excited to build this!

One small thing I noticed is that the tool tip seems to interrupt the mouse over, for lack of a better term. Maybe it's because of the opacity? I found [this](https://bl.ocks.org/mbostock/1087001) example that has the tool tip move along the mouse. After playing around with your code a bit, I moved a lot of what you have in `.on("mouseover"...` into `.on("mousemove"...` and it seems to work like that example. Here's a rough Gist of what I changed: https://gist.github.com/scissorsneedfoodtoo/3517f6f6d8c7b451fa0b2053e8098b0c

Anyway, I was just messing around with it, so don't feel obligated to make any big changes to your project. I think you're good to go! Really excited to see this project broken down into steps.

**Comment by HKuz** [comment]
Thanks for the thorough review @scissorsneedfoodtoo ! Very helpful comments and thanks for taking the time to figure out that mouseover fix - I thought it was my mouse being glitchy 😅 but it works much better now. The latest project has those changes incorporated. I'm traveling through the weekend, but can get started breaking this down next week 👍

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, hope you had a nice trip over the weekend! Just wondering, do you have about 20 to 30 minutes to hop on a call to talk about your projects? If so, please send me an email at kris@freecodecamp.org!

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, thanks again for taking the time to talk! I took a quick look at the [D3 page](https://d3js.org/), and there are some instructions for including the library locally. Just thought I'd mention it before you get too deep into writing your test descriptions.

I'm really looking forward to seeing your completed project :+1: :+1: Please just let me know if there's anything I can do to help.

**Comment by HKuz** [comment]
Thanks for checking on that @scissorsneedfoodtoo ! For now, to keep offline functionality simple, I saved the D3 scripts (what the CDNs were pointing to) into the project folder and link to them vs the CDN. I'm thinking that we can update this with the optimal bundling/module import system when there's more info about how the platform will run. Time to get cranking on these lessons! 👍

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, awesome! Glad that it worked, and hopefully we'll know more about the platform soon. Looking forward to seeing your lessons!

**Comment by scissorsneedfoodtoo** [comment]
Hi @HKuz, were you able to start breaking this project down into steps? Looking forward to seeing them soon.

**Comment by HKuz** [comment]
Hi @scissorsneedfoodtoo - yes, I've been working on breaking this down over on my repo for the project. I've been stretched a little thin lately, so my progress is on the slower side, but I'd say I've got about half of the lessons done - getting there!

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, okay! Thank you for the update. Glad to hear that you've been making steady progress on breaking this project down. Half of the lessons already is great, especially considering how complex this project is. Will check them out over on your repo!

**Comment by HKuz** [comment]
Just a quick update on this project - late summer/early fall got a bit nuts, but I've been making steady progress on it recently. I'm estimating that there will be around 130 total lessons with about 35 still outstanding. Lessons covering background D3 info, setup, map functionality, and the tooltip are done, with the pan/zoom and legend ones still to-do. Onwards and upwards!

**Comment by scissorsneedfoodtoo** [comment]
@HKuz, great! Thank you for such a detailed update and glad to hear that you've been making steady progress. 130 total lessons for such a big topic/project sounds about right given everything you'll be covering.
