### ISSUE TITLE
Responsive Web Design Project: Survey Form

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#12]
We are introducing a few new front end projects to give campers more experience working just with HTML and CSS before adding JavaScript to the mix. 

Here are the agile use stories for this challenge:
1. I can complete a survey that has various questions, and uses check boxes, radio buttons, text inputs and select inputs.
2. Some of these fields are required and some are optional.
3. Some of these fields use HTML5 form validation.
4. When I click the submit button, it redirects me to a submission page on Free Code Camp.

We are looking for a volunteer who can build a working demo of this on CodePen using only HTML5 and CSS (no libraries).

**Comment by ChaituVR** [comment]
I am Interested doing this

**Comment by ChaituVR** [comment]
I've finished this here http://codepen.io/ChaituVR/full/rLwJjZ/ used only basic inputs .. It would be great if someone reviews this and i would like to make changes if needed .. @QuincyLarson  @atjonathan

**Comment by QuincyLarson** [comment]
@ChaituVR excellent work! This demo is good to go! We can create a corresponding Free Code Camp submission view.

Could you create the agile user stories that correspond to this challenge?

**Comment by ChaituVR** [comment]
@QuincyLarson The User stories you mentioned are good to go..
I modified them a bit..
**User Story:** I can fill in the survey having a minimum of six various input fields like text checkboxes, radio buttons, text inputs and select inputs.
**User Story:** I can see at least three inputs should be marked important and i should not be able to submit the survey without filling these input fields
**User Story:** I can utilize native HTML5 validations on at least two input fields to detect wrong input
**User Story:** I can click on the submit button which redirects to me to the Freecodecamp 's submission page

**Comment by QuincyLarson** [comment]
@ChaituVR excellent work! This is great! I am going to go ahead and close this issue and we will use your user stories and implementation as the demo. 
Thank you again for your hard work on this.

**Comment by ChaituVR** [comment]
Thanks for you.. Learned many aspects by doing this :)

**Comment by SamAI-Software** [comment]
@ChaituVR great form! What do you think about making it a bit more modern-looking (flat design)? Just to keep campers up to date with current trends.

![surveyform1 webmed](https://cloud.githubusercontent.com/assets/16253583/17051925/66b2a3fe-5025-11e6-936e-059d42b4b474.jpg)


http://codepen.io/SamAI-Software/pen/KroJvX
I've changed just a few lines, so the code is still very simple.

**Comment by ChaituVR** [comment]
That looks great.. @SamAI-Software .. but as this issue is closed .. i would like to wait until @QuincyLarson watch this and confirm this ..  thanks for the changes @SamAI-Software :+1:

**Comment by SamAI-Software** [comment]
@ChaituVR cool :+1: 
By the way, checkboxes and radio buttons are usually positioned vertically, because horizontally they look confusing from **UX** perspective.

![surveyform4](https://cloud.githubusercontent.com/assets/16253583/17055819/8d3e964a-5039-11e6-926c-41917328f9e4.jpg)

***
So we can make it even better with a vertical layout to cultivate good practices among campers.

![surveyform6](https://cloud.githubusercontent.com/assets/16253583/17056005/b8c8c2ee-503a-11e6-821d-1894850459cc.jpg)


http://codepen.io/SamAI-Software/pen/KroJvX

**Comment by QuincyLarson** [comment]
@SamAI-Software I agree with you that these should definitely each be on their own line, but I think centering the question vertically is confusing because it will require users to see the option, then glance down and realize they are associated with question text lower. I think the question should be at the top of the options.

**Comment by SamAI-Software** [comment]
@QuincyLarson yes, I totally agree with you. I've already tried to put questions on top, but this code is full of margins/paddings in many elements, so I've changed a lot for that approach to make it look good, which added complexity to the code, so finally I've decided to backup and to stick with a vertical centering for **simplicity**.

It would be really great if @ChaituVR can do refactoring and make the code a bit more simple with
```css
.labels {
  vertical-align: top;
}
```
Here is a fork with a proper align, but problems with margin/padding.
http://codepen.io/SamAI-Software/pen/KroJvX

***
I think it's important to use simple clean code for our projects, because most of the campers break the rule and actually look the source code, at least I did that all the time :)

The first rule of Free Code Camp is: you do not look at the example project's code. 
The second rule of Free Code Camp is: you **DO NOT** look at the example project's code!

[![Tyler.jpg](https://files.gitter.im/SamAI-Software/Tyler.jpg)](https://files.gitter.im/SamAI-Software/Tyler.jpg)

**Comment by SamAI-Software** [comment]
With @ChaituVR help, the final survey form looks like this - http://codepen.io/SamAI-Software/pen/KroJvX

![surveyfinal](https://cloud.githubusercontent.com/assets/16253583/17268725/7e614c4c-565d-11e6-8e96-1740f87a14c5.jpg)

**Comment by QuincyLarson** [comment]
@SamAI-Software @ChaituVR excellent work! This looks much better. Note that your custom button does not show the pointer when you hover over it.

**Comment by QuincyLarson** [comment]
@SamAI-Software @ChaituVR since you did such a good job on this, would either of you be interested in tackling https://github.com/FreeCodeCamp/CurriculumExpansion/issues/36 or https://github.com/FreeCodeCamp/CurriculumExpansion/issues/35?

**Comment by ChaituVR** [comment]
@QuincyLarson Sure .. :)

**Comment by SamAI-Software** [comment]
@QuincyLarson yes, we know. There are debates if buttons [should have pointer or not](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b).

But we can make pointer if you want to.

**Comment by QuincyLarson** [comment]
@SamAI-Software It is convention that buttons have pointers, regardless of the points the author argues (and if you look in the comments, most people agree that you should follow this convention).

**Comment by SamAI-Software** [comment]
OK, done. Then for other projects we will need pointer for consistency, too.

**Comment by SamAI-Software** [comment]
@QuincyLarson btw Yahoo search uses **pointer** for buttons, while Google search uses **default** cursor :)

But that's very interesting topic, because for all other Google's products (except Google+) they use **pointer** for buttons. Probably because main google search page is full of links, so they don't want to overuse **pointer**, so they keep it only for links. I doubt that such a big successful company will break the consistency just by accident.
Anyway, it's very interesting to see what gonna happen with this trend.

**Comment by QuincyLarson** [comment]
@SamAI-Software Google is inconsistent in their usage of pointer. In virtually all cases, they do use pointer, though.

**Comment by QuincyLarson** [comment]
@SamAI-Software yes - I agree. We want to be as consistent as possible. We have an opportunity to make these project examples a bit more consistent as well :)
