### ISSUE TITLE
Learn Intermediate JavaScript by Building a Calorie Counter

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#123]

**Comment by lmilliken** [comment]
I'm interested in helping out with this one.

**Comment by Gcoded** [comment]
I'm also interested in helping with this.

**Comment by QuincyLarson** [comment]
@lmilliken @Gcoded Thanks for your patience. Which of you is interested in building this?

The first step is to build the project itself. Then you can work backward to break it down into steps, like this: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files#diff-99314d694942b489d28d8a6f0c3bc5a3

**Comment by lmilliken** [comment]
I can take a stab at this.  Just to clarify, this "Fitness Tracker" will be more of an activity tracker where people log their workouts (type of activity, duration), which will be saved in local storage.  Let me know if you are thinking of something else (like connecting to like a FitBit api and presenting the data?)

**Comment by QuincyLarson** [comment]
@lmilliken Ah - I had forgotten we already had a fitness tracker project in our curriculum! We should probably focus on something similar but different - like a calorie counter or something like that, where you  post the number of calories in a meal you ate, and it then tells you how much you are over/under the recommended daily recommended caloric intake (2,500 calories for a man, 2,000 for a woman).

**Comment by lmilliken** [comment]
Ok, I can help with this.  To clarify, this is a single front-end page and the UI components are controlled by plain Javascript, correct?  No jQuery or other libraries?

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, thanks for your patience.

Yes, you're right. All the projects should be a single page with no additional libraries like jQuery. The exception would be projects like the React Flappy Bird game or D3 map of Earth that require libraries.

@Gcoded, have you already started building this? If not, I'll assign @lmilliken to this project.

**Comment by Gcoded** [comment]
Sorry all for being MIA. I haven't done anything for this project, but I'm still interested in helping with the new curriculum so I'll look to see what else is available.

**Comment by scissorsneedfoodtoo** [comment]
@Gcoded, no worries! There are still a few other projects that are available. Please take a look at the ones with the "help wanted" label and leave a comment if you'd like to work on it.

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, just checking in to see how things are going with your prototype. Do you have anything you can show us? If so, we could give some early feedback.

**Comment by lmilliken** [comment]
@scissorsneedfoodtoo , sorry I was pulled away on the stock trading app.  I'll try to put something together shortly.

**Comment by lmilliken** [comment]
@scissorsneedfoodtoo , here is the work in progress draft: https://codepen.io/millifly/pen/eoGBPv.  Let me know what you think.  Not sure if this is too basic or how deeply we want to teach DOM manipulation with javascript

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, this is looking great so far! To answer your questions, since this project will cover intermediate JavaScript, teaching DOM manipulation is totally fine. Would be useful for students to learn how to do all of that. We're trying to avoid all libraries as much as possible. Could you provide the styling instead?

**Comment by lmilliken** [comment]
@scissorsneedfoodtoo , here is the final draft: https://codepen.io/millifly/pen/eoGBPv.  Let me now if any recommendations before I start breaking it down to steps. 

Any help with styling from anyone would be greatly appreciated!

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, this is looking good! Really good use of function expressions and arrow functions at the bottom that would be good to teach at this point in the curriculum.

I just noticed that you can pass negative values in for breakfast, lunch, or dinner. Could you have a check to prevent that? There doesn't need to be a UI warning or anything, just defaulting to 0 and updating the value in the text input would be fine. Also, according to MDN, the `<center>` tag is considered obsolete. Could you use CSS to center that instead?

As for the styling, we don't need to worry so much about it. The only suggestions I have would be to try and organize your CSS rules a bit more so it's as if you're styling things from the top of the page to the bottom. Moving the `body` rule to the top, then `.container`, `.calorie-form`, and so on. It would also be good to vertically center text like "Sex", "Breakfast", "Lunch", and "Dinner".

Another thought I had is that it would be really cool to add additional meals or snacks to the form. Something like a plus button that appends another text area and number input to the page to let users enter in what they ate and how many calories it was. This would also give you the opportunity to let students refactor the project as it goes along, and introduce some new concepts like `getElementsByClassName()`, `Array.from`, and `map()`. I started playing around with it a little here: https://codepen.io/scissorsneedfoodtoo/pen/QPrjqo?editors=1111

Again, this is coming along really nicely! I'll see if I can get another review from @QuincyLarson, @beaucarnes, or @Ethan-Arrowood before you start breaking things down into steps.

**Comment by lmilliken** [comment]
@scissorsneedfoodtoo , here is the updated draft based on your feedback: https://codepen.io/millifly/pen/eoGBPv.  Maybe it's because I haven't done JS DOM manipulation in a while, but it feels very clunky and laborious (it's going to be complicated to explain this in the in-depth instructions).  

Let me know if you have further feedback on the code itself and ways to potentially simplify it for a lesson.

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, this looks great! Thank you for being so open to my rambling input.

I think that fCC users will learn a lot while working through your lessons to build this. You did a great job here, and used all the best practices as far as I can tell (creating and removing text nodes rather than using `innerHTML`). I suppose you could build a template literal string and `textContent` for the output, but what you did is totally fine. Since this is intermediate JavaScript it would be good to teach the DOM manipulation concepts that you have here. You could post your CodePen link to the [Contributor's Chatroom](https://gitter.im/FreeCodeCamp/Contributors) for more input if you'd like, but I believe you're good to go here.

You're right that it could be difficult to explain some of these concepts, even with in depth instructions. However, I'm confident that you'll be able to do that if you break the project down into steps similar to how you built it. Don't worry about having the users build the HTML and CSS -- you can start with those already built out like in the [RPG](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/basic-javascript-role-playing-game) game and just focus on teaching JavaScript.

**Comment by beaucarnes** [comment]
@lmilliken I just checked out the code pen. It looks good to me!

**Comment by lmilliken** [comment]
work in progress instructions: https://github.com/lmilliken/CalorieCounter

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, that's great! Looking forward to reading all of your instructions soon :+1: :+1:
