### ISSUE TITLE
Learn CSS Variables by Building a City Skyline

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#130]

**Comment by ahmadabdolsaheb** [comment]
I removed my assignment just in case someone is interested in contributing to this while I work on the other parts of the curriculum.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb Sounds good. Thanks for freeing this up.

**Comment by thecodingaviator** [comment]
@QuincyLarson Can I pick this one up? You can check my [CodePen](https://codepen.io/thecodingaviator/pens/public/) I have some examples of CSS things I've done over there, if it looks good, please assign it!

**Comment by moT01** [comment]
I can try and take this one. So what's going to happen to flappy the penguin? ☹️

**Comment by QuincyLarson** [comment]
@moT01 We may be able to keep it as a separate project, like "Learn Basic CSS by Building a CSS Penguin" or something like that.

**Comment by moT01** [comment]
Looking for some initial feedback...
full page -> https://codepen.io/moT01/full/RdzNPr
code -> https://codepen.io/moT01/pen/RdzNPr?editors=1100

So are we going to want users to create all the code?
Or is it acceptable for me to like create some div's or something and just tell them to "add 'class' to all the div's"

**Comment by ahmadabdolsaheb** [comment]
@moT01, so on this curriculum iteration we are focusing on repetition. So the project need to be built from the first line of code. you could checkout other topics for reference.

**Comment by thecodingaviator** [comment]
@moT01 Looks awesome!

**Comment by moT01** [comment]
Thanks guys! So will I want a single HTML file with all the CSS in style tags like the current challenges? And how much do I want in there? doctype, html, head? Have the user create all of that, or will the editor basically be the body tag and just have them create the stuff in there?

**Comment by QuincyLarson** [comment]
@moT01 That's a thing of beauty. Brought a tear to my eye.

Yes - we will want to have people write ever line of code if possible. In doing so, not only do they get the repetition @ahmadabdolsaheb mentioned, but they also get more of a feel of accomplishment that they are actually building the full project themselves.

**Comment by moT01** [comment]
Thanks @QuincyLarson, I used a lot of `linear-gradient` - I'm not sure how much that will be covered in other projects, should we expand this to cover that in depth a little more? Maybe `Learn CSS Variables and Linear-Gradient by Building a Skyline`. I will pretty much have to cover it regardless, but maybe not as much if it was already taught.

**Comment by QuincyLarson** [comment]
@moT01 This may be the first place gradients will be covered, so you can go into relative depth with lots of tests around this. We may consider changing the name to `Learn CSS Variables and Gradients by Building a Skyline` though that is a bit of a mouthful. 😄 Best of luck writing the tests, and let me know if I can be of any help. I am excited to get people working through these tests and building this project. It will definitely be something they can show off to their families.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, your project looks great! Looking forward to building my own city skyline now.

**Comment by huyenltnguyen** [comment]
@moT01 Wow, I just checked out your pen and it's awesome! Have to admit that after looking at it in the full-page mode, I had to change the view to editor to make sure I wasn't looking at an svg or png 🤣

**Comment by moT01** [comment]
Thanks everyone - I need to disclose something here... Before I built this, I did a quick search for images and basically built this from an Image. Specifically, [this image](https://www.kisspng.com/png-building-flat-design-skyline-cartoon-city-521247/). So that person should get some visual design credit. My result has many differences, but is quite similar. I didn't think anything of it at first, but it could potentially be a copyright issue. Is this going to be a problem @QuincyLarson?

**Comment by raisedadead** [comment]
The image is licenses for personal use and can't be used. Let's find a replacement.

**Comment by huyenltnguyen** [comment]
I just found this website: https://publicdomainvectors.org/en/
It offers free illustration images which are licensed under [Creative Commons Deed CC0](https://creativecommons.org/publicdomain/zero/1.0/deed.en). Worth taking a look, I guess.

**Comment by moT01** [comment]
alright, is this still too similar? https://codepen.io/moT01/full/OGXLZd

**Comment by scissorsneedfoodtoo** [comment]
@moT01, sorry! Totally missed your update. Your new project looks great! Different enough that it shouldn't be an issue with the license.

Pinging @QuincyLarson for a second opinion.

**Comment by QuincyLarson** [comment]
@moT01 This looks great to me. This will be a lot of tests - do you want to go ahead and start the process?

This may very well be hundreds of tests - we should have a test for every significant step - we want them building this up one or two lines of code at a time.

Do you plan to have them build the basic skyline first, then go through and add the details to each building afterward?

**Comment by moT01** [comment]
@QuincyLarson I made a PR with my first rendition of the instructions - it's linked above. Feel free to look over them if you want, any feedback is appreciated. @scissorsneedfoodtoo was thinking it needs to be broken up a little more, sounds like you are leaning the same way. So I'll probably have to at least do some of that. There's more than a few tests that have additions of way more than two lines of code, but I thought it might be fine since it was gone over pretty well in this and probably other projects. The addition of width and height properties for instance - I have that getting added to maybe 4-6 elements at once. It might end up getting a little long if we break it up too much. Hopefully we can find a way to make it work.

As I recall, I started by creating one building most of the way. Then did the outlines of the rest of the buildings. And pretty much went through them one by one after that.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, we're starting the process of porting some of these projects over to the current platform for people to test. Would you be interested in helping us write the unit tests for each step in your project?

**Comment by moT01** [comment]
Once a branch on the main repo is created for these projects, I will make a PR there - for now, these challenges are viewable [here](https://github.com/freeCodeCamp/freeCodeCamp/compare/master...moT01:feat/add-tests-for-skyline-project?expand=1) - the tests are all created, and I'm pretty satisfied with all of the challenges.
