### ISSUE TITLE
Learn Basic JavaScript by Building a Role Playing Game

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#133]

**Comment by beaucarnes** [comment]
I made a PR for this with my first draft of the updated curriculum. Maybe I should move it to the `CurriculumExpansion` repo. https://github.com/freeCodeCamp/freeCodeCamp/pull/35634

**Comment by waltmurray** [comment]
Hi,

I'm a new student of JS and reviewed this from that perspective. This is my first time contributing to open source, so not sure where the best place is to put my comments ... but here they are:

-Overall it was a nice experience with a cool end product
-The difference between `var` and `let`wasn't explained too clearly at the beginning. Also, the lesson never shows in what scenario you would use `var`, it just says to use `let` instead. I would suggest starting off with `let` if it's best practice and then introducing `var` later on in the lesson for some specific purpose.
-When console.log is first introduced, it's assumed the user knows where to check for its output. Maybe some explanation about where to check the console could be added.
-The easterEgg function add the end of the game isn't fully functional (e.g. the pick function isn't defined). It could be neat at that point to challenge the student to make the hidden easterEgg game and hint that they can access it by calling easterEgg in the console.

That's all I have, thanks for putting the lesson together!

**Comment by scissorsneedfoodtoo** [comment]
@ryanwaltmurray, thank you for your review! You bring up some interesting points that hopefully I'll be able to answer.

For the difference between `var` and `let`, there's a lot to go over that could be overwhelming for the complete beginners this lesson is aimed at. A better explanation is given [here](https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/basic-javascript-role-playing-game/index040.js) about how using `let` is better in modern JavaScript. As far as the order in which they're introduced, I think I prefer the way it is now with `var` for a few lessons to show the older way of declaring variables, then quickly introducing `let` and later `const`.

We'll be rolling out a [new UI](https://www.freecodecamp.org/forum/t/freecodecamp-redesign-command-line-chic/267917) soon, and it will probably change quite a bit more as these new projects are released. Even with all those changes, I imagine that there will still be a console to show output like there is in the current UI. If not, we may need to update those lessons.

About the easterEgg function, that's a very good point. In the last lesson, the user creates the pickTwo and pickEight functions, but not the actual pick function. But in the final file, `index.js`, the pick function is complete. This might have been done to shorten the project length a bit since there are already more than 140 lessons. Maybe @beaucarnes can shed some light here.

Thank you again for your thorough review! Would you be interested in reviewing some of the other projects, like the [Cat Photo App](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/html-cat-photo-app) or the [CSS Variables Skyline](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/variables-skyline)? Or if you would rather work on a project, there are still some [unclaimed ones](https://github.com/freeCodeCamp/CurriculumExpansion/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

**Comment by ryanwaltmurray** [comment]
Thanks, that all makes sense. I'll see where I can help out with the unclaimed projects. I could also review more completed projects, but if the new UI is rolling out soon then I'll wait until then to review them. I'll be quite busy until mid-June, but I'll try to chunk out some time.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for your help! Anything from participating in discussions about each project to reviewing one or building your own is greatly appreciated. 

And sorry, I may have overstated how soon the new UI will come out. Really there are two things going on with the UI. There's a refresh coming out soon, and is detailed in the forum post I linked to above. A bigger overhaul is planned for release along with these projects, and will include things like multiple file support. 

All that said, don't feel like you have to wait for those UI updates before contributing here. Feel free to reach out to me if you have any questions.

**Comment by beaucarnes** [comment]
@ryanwaltmurray Thanks for reviewing this project. I'll think about how I better explain the difference between let and var in the project. For the console log, I think the UI will make it more clear where to look once it is complete.

Thanks for pointing out that the pick function is missing. I actually have that on my local copy but for some reason the version on GitHub is missing the last few lessons. I'll get those on GitHub. I'm glad you caught that issue.

**Comment by shithilIRON** [comment]
Thank you for your help! Anything from participating in discussions about each project to reviewing one or building your own is greatly appreciated
