### ISSUE TITLE
Write CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ethan-Arrowood** [freeCodeCamp/CurriculumExpansion#141]
We've been receiving a ton of great work from all of you! Some of your challenges are nearly ready too. I'm going to work on an official contributing guideline doc so y'all will have all of the information you need to make better curriculum and amazing pull requests.

**Comment by scissorsneedfoodtoo** [comment]
@Ethan-Arrowood, sorry, I just saw this issue. This would be really helpful! What sort of information will you me including here? Will it be similar to the Contributor's Guide in the main repo?

**Comment by Ethan-Arrowood** [comment]
I'm thinking like
- make sure challenges are in a folder
- make sure there are no spelling mistakes
- be thorough but keep challenges to a couple minutes each; shorter is better

What else can you think of?

**Comment by scissorsneedfoodtoo** [comment]
Yes, that all sounds great! Your last point is mentioned in the Style Guide, but it was written with the older challenge format in mind. I wrote some [FAQs](https://www.freecodecamp.org/forum/t/freecodecamp-curriculum-7-0-faqs/269346) about the new curriculum over on the forum, and it goes over:
* breaking projects down into separate steps/files
* writing test descriptions in the file/area the user will be focused on

I also thought about updating the Style Guide to include sections outlining how to write about HTML elements, attributes, function names, and so on, more as a reference for us rather than contributors.

**Comment by QuincyLarson** [comment]
@Ethan-Arrowood could you use @scissorsneedfoodtoo's forum post and then add the usual contributing.md boilerplate around it?
