### ISSUE TITLE
OpenCV.js tutorial at freeCodeCamp.org

### ISSUE THREAD

**Issue by ieliz** [freeCodeCamp/CurriculumExpansion#209]
Greetings!
We are Summer Intel Interns.
Our team would like to collaborate with freeCodeCamp.org project.

We want to create beginner's course about OpenCV.js. The course will include topics like: installing, resize image and image processing, camera management and others by means of short theory sentences, interactive examples, tasks for self test.

Based on this, better way to create this course is challenges: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md

But we can consider to create that course in other ways you accept:
YouTube: https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ
Articles: https://terms-of-service.freecodecamp.org

We want to ask you several questions about content requirements
 on freeCodeCamp.org platform:
1) Are you considering that kind of contributions to your platform?
2) In which category do you want to see our course? (https://learn.freecodecamp.org)
3) What expectations and proposals do you have about that project?

We will be glad to hear your ideas and offerings.

Sincerely, @ilbalance, @SimpleVlad.

/cc @dkurt.

**Comment by SimpleVlad** [comment]
We wrote a message about occurred problem as @raisedadead said and are waiting for your reply.(https://gitter.im/FreeCodeCamp/Contributors?at=5d63efcf022dba538e642c13)

**Comment by scissorsneedfoodtoo** [comment]
Hi @SimpleVlad, thank you for continuing to work on the OpenCV tutorial. Unfortunately we're not looking to add new courses to the current curriculum or the upcoming one in the CurriculumExpansion repository.

As I said in our [earlier conversation](https://github.com/freeCodeCamp/CurriculumExpansion/issues/209#issuecomment-510891166), the best thing to do is to create an in-depth text tutorial first. It could be similar to a crash similar to [this](https://www.freecodecamp.org/news/the-html-handbook/) or [this](https://www.freecodecamp.org/news/want-to-learn-to-build-websites-try-our-free-4-hour-crash-course-on-html-css-2/). Your tutorial/article doesn't need to be quite that long, but could walk learners through the basics, explaining what computer vision and OpenCV is, and how open, read, write, and show images. Then it could start going over some common methods used in OpenCV before actually showing what you can do with the library like converting an image to greyscale, resizing or smoothing an image, and so on. The content from your PR looks great, and would work well in an article format.

My apologies if that wasn't clear from my earlier comment. Thank you all again for all of your hard work on the lessons so far, and again, I think they will make for an excellent text-based tutorial. Feel free to send me an email at kris@freecodecamp.org if you'd like to hop on a call and talk more about the next steps.

**Comment by raisedadead** [comment]
Hi @ilbalance this is still an ongoing topic and implementation that we are likely to add.

**Comment by dkurt** [comment]
@raisedadead, Can we ask you about the structure of the samples. In example, https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/build-npm-module. Am I right that it's a kind of sequence? Is there Web GUI which can show them one-by-one?

**Comment by raisedadead** [comment]
Am I right that it's a kind of sequence? 

Yes, this is an sample sequence for node js bases projects/challenges. I'll defer to @scissorsneedfoodtoo for an exact requirement.

Is there Web GUI which can show them one-by-one?

Not at the minute, we can develop a UI depending on the content. That is something will come after the fact. The content needs to be curated first as a part if the research and development for the curriculum.

**Comment by scissorsneedfoodtoo** [comment]
Hi @dkurt, @SimpleVlad, and @ilbalance. Talked this over with @QuincyLarson and last night and we're excited by the prospect of making OpenCV content available to freeCodeCamp learners, especially since there isn't much out there for the JS library right now. Building an interactive curriculum is a huge undertaking, so here's what we suggest:

1. Create an in-depth article that covers the basics similar to [this](https://www.freecodecamp.org/news/the-html-handbook/) that can be published on [Developer News](https://www.freecodecamp.org/news/)
2. Turn that article into a video which could possibly be published on our YouTube page
3. Finally, we could look to turn this into an interactive project like the ones in this repo

Our thinking is that the article will take the least amount of time, and will serve as the script for the video. The video will require some planning to set up the examples to teach the concepts in your article. I imagine it being similar to this recent [Sass tutorial](https://www.youtube.com/watch?v=_a5j7KoflTs) where you can assume the learner has some prior knowledge of JS before teaching OpenCV. Then finally, the video can be used as the basis for the interactive project.
