### ISSUE TITLE
Arithmetic Formatter (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#231]
Create project from the Python scientific computing certification.

**Comment by scissorsneedfoodtoo** [comment]
Project prototype: https://repl.it/@BeauCarnes/fcc-arithmetic-arranger

**Comment by notingGone** [comment]
Typo on the sixth bullet point.
I assume this:
"There should be a single space between the operator the following number."
should be:
"There should be a single space between the operator and the following number."

**Comment by scissorsneedfoodtoo** [comment]
Thank you for catching this @notingGone. We'll be sure to update this before the release.

**Comment by notingGone** [comment]
*"Accepts between one and five problems. Otherwise, the function should return Error: Too many problems.."*
implies:
`if (len(problems) > 5 or len(problems) < 1):
      return "Error: Numbers cannot be more than four digits."`
whereas the solution code only tests for the upper limit:
`if len(problems) > 5:
    return "Error: Too many problems."`

**Comment by behrtam** [comment]
```python
def test_simple_arangement(self):
    actual = arithmetic_arranger(["235 + 52"])
    expected = "  235\n+  52\n-----"
    self.assertEqual(actual, expected)
```

For me it was helpfull to have a very simple test based on the first README example before the `test_arangement` test with 4 problems.

**Comment by borntofrappe** [comment]
> Accepts between one and five problems. Otherwise, the function should return `Error: Too many problems.`

And

> Each number is between one and four digits long. Otherwise, the function should return `Error: Numbers cannot be more than four digits.`

As @notingGone points out, the text describes a range, while the error message seems to suggest we should test for the upper threshold only.

The function has always at least one problem, and we always consider positive integers, so perhaps the text should describe only the greater boundary?

---

> There should be a single space between the operator the following number.

I believe the single space should be between the operator and the longest of the two numbers.

For instance with '235 + 5', the space is between the plus sign `+` and `2`. There is more whitespace between `+` and the number which follows.

```py
arithmetic_arranger(['235 + 5'])
'''
  235
+   5
-----
'''
```

---

> There should be four spaces between each vertically arranged problem.

I might be daft, but this one puzzled me a little. It describes the number of spaces between successive problems, right? The word _vertically_ lead me to think the test was about the height of the individual problems.

Apologies if these notes sound like nitpicks. The README file was overall easy to understand and I was able to complete the project.

**Comment by adamdune** [comment]
I agree with what @borntofrappe said (https://github.com/freeCodeCamp/CurriculumExpansion/issues/231#issuecomment-574889042).
The parts he highlighted did come off as a little confusing to me.

All I have to add is a nitpick (I know these aren't important 😅): these two bullet points do not have their full stops.
> * Each number should only contain digits. Otherwise, the function should return `Error: Numbers must only contain digits.`
> * Each number is between one and four digits long. Otherwise, the function should return `Error: Numbers cannot be more than four digits.`

**Comment by scissorsneedfoodtoo** [comment]
Thanks everyone for your review. We'll take this all into account as we work on the next draft.

Given that each number in the problem should be between one and four digits long, the text `There should be a single space between the operator the following number` should probably be changed to `There should be at least one space between the operator the following number`.

As for testing only the upper range of problems passed to the function, we could include text in the README saying that there will always be at least one problem passed to the function. We could also mention that each number in the problems will be at least one digit long. Otherwise we could include a requirement for another error message for each requirement, maybe something like `Error: Expected at least one problem.` and `Error: Expected each number to have at least one digit.`.

@borntofrappe, that's a good point about the `There should be four spaces between each vertically arranged problem` requirement. Perhaps there's a way to make it more clear that each arithmetic problem should be aligned vertically, but printed on the same horizontal plane with 4 spaces between each problem. It's a very difficult thing to describe using only text :laughing: We're open to any suggestions about how to make this more explicit.

**Comment by borntofrappe** [comment]
@scissorsneedfoodtoo quite challenging indeed

Beside updating the text, I would also suggest we'd swap the last two bullet points. This because the very last point describing the dashes refers to the individual problem, and is more connected to the previous points than the penultimate one. Perhaps this is what confused me in the first place.

Hope it's not brash, but maybe the following description might help:

> - There should be dashes at the bottom of each problem. The dashes should consider the entire length of the operation.
> - There should be four spaces between different problems.
>
> The example above shows the result of these rules. 

I'd label them _different_, or _successive_, or _multiple_. Whichever describes the disconnect between the operations best.

**Comment by scissorsneedfoodtoo** [comment]
@borntofrappe, not brash at all, we really appreciate all the input. We're so familiar with these problems and what the expected output should be that it's difficult for us to see the parts that are unclear. Your perspective is a huge help making these descriptions as clear as possible.

I agree, switching those two bullet points is a good idea and should help with clarity. Also those alternative word choices for the last bullet point are all good. Maybe something like "There should be four spaces between each successive arithmetic problem" or "There should be four spaces between each problem."

**Comment by beaucarnes** [comment]
Thanks everybody for the suggestions! I've implemented all the suggestions so far.

**Comment by Gerschel** [comment]
I may have gotten carried away, but I felt there were some subtleties that would make the assignment more clear. So I went through most of the README and made the modifications, mostly in the Rules section that I added.  

### Assignment

Students in primary school often arrange arithmetic problems vertically to make them easier to solve. For example, "235 + 52" becomes:
```
  235
+  52
-----
```

Create a function that receives a list of strings that are arithmetic problems and returns the problems arranged vertically and side-by-side.

### For example

Function Call:
```
arithmetic_arranger(["32 + 698", "3801 - 2", "45 + 43", "123 + 49"])
```

Output:
```
   32      3801      45      123
+ 698    -    2    + 43    +  49
-----    ------    ----    -----
```

### Rules

The function will return the correct conversion if the supplied problems are properly formatted, otherwise, it will **return** a **string** that describes an error that is meaningful to the user.  


* Situations that will return an error:
  * If there are **too many problems** supplied to the function. The limit is **five**, anything more will return:
    `Error: Too many problems.`
  * The appropriate operators the function will accept are **addition** and **subtraction**. Multiplication and division will return an error. Other operators not mentioned in this bullet point will not need to be tested. The error returned will be:
    `Error: Operator must be '+' or '-'.`
  * Each number (operand) should only contain digits. Otherwise, the function will return:
    `Error: Numbers must only contain digits`
  * Each operand (aka number on each side of the operator) has a max of four digits in width. Otherwise, the error string returned will be:
    `Error: Numbers cannot be more than four digits.`
*  If the user supplied the correct format of problems, the conversion you return will follow these rules:
  * There should be a single space between the operator and the longest of the two operands, the operator will be on the same line as the second operand, both operands will be in the same order as provided (the first will be the top one and the second will be the bottom.
  * Numbers should be right-aligned.
  * There should be four spaces between each problem.
  * There should be dashes at the bottom of each problem. The dashes should run along the entire length of each problem individually. (The example above shows what this should look like.)

### Development

Write your code in `arithmetic_arranger.py`. For development, you can use `main.py` to test your `arithmetic_arranger()` function. Click the "run" button and `main.py` will run.

### Testing 

The unit tests for this project are in `test_module.py`. We imported the tests from `test_module.py` to `main.py` for your convenience. The tests will run automatically whenever you hit the "run" button.

### Submitting

Copy your project's URL and submit it to freeCodeCamp.

**Comment by Gerschel** [comment]
Perhaps the line that says "four spaces" should have the word "should" be changed to "will", so that way someone doesn't assume they can string fomat a tab in there like I did.

**Comment by beaucarnes** [comment]
@Gerschel I really like your wording! Thanks for taking the time to rewrite this. I updated the project to incorporate most of your suggestions.

**Comment by jdelarubia** [comment]
The url to my project is: [arithmetic formatter](https://repl.it/@jdelarubia/01-fcc-arithmetic-arranger).
The difficulty for me was not being able to fully use Python string formatting options.
Things like [`f"{operand:>6d}"`](url) , because we cannot include a variable number of spaces that operand can take. However, I managed to find my way around it.
Maybe, relaxing the tests by requiring a fixed length to each operation?
Anyhow, I had fun building it and didn't take me very long.

**Comment by kunalrustagi08** [comment]
This is a great project to get learn string formatting. I enjoyed solving it.
This is the link to my [arithmetic_arranger](https://gist.github.com/kunalrustagi08/3fc1163035f35627a29b4ae60b4d4830) .

**Comment by robertue1** [comment]
It really helped me to learn some formatting. 

Here is the link of my resolution: [arithmetic_arranger](https://repl.it/repls/ReliableThreadbareSort)

Roberto.

**Comment by mike-lloyd03** [comment]
The README.md says:

> Each number (operand) should only contain digits. Otherwise, the function will return:
> `Error: Numbers must only contain digits`

But the UnitTests look for:

> `Error: Numbers must only contain digits.`

There should be a period at the end of the sentence in the .md file to be consistent with the other error strings.

**Comment by salasy** [comment]
Link to my solution:
[fcc-arithmetic-arranger](https://repl.it/@sasakr/fcc-arithmetic-arranger#arithmetic_arranger.py)

**Comment by scissorsneedfoodtoo** [comment]
@mike-lloyd03, awesome, thank you for catching that. I'll update the README to reflect that.

**Comment by manshul1807** [comment]
Hi, Loved the project. Found no glitches. Learnt formatting and googled a lot. 

Link : https://repl.it/@ManshulArora/ArithmeticArranger#main.py

**Comment by scissorsneedfoodtoo** [comment]
@manshul1807, great, thank you for your feedback. Please let us know what you think about the other projects, too.

**Comment by borntofrappe** [comment]
I'm revisiting the project since I first examined it back in February. Am I correct to assume the prototype is now at the following URL @scissorsneedfoodtoo ?

https://repl.it/@freeCodeCamp/fcc-arithmetic-arranger

It seems there's an additional test with respect to the original. I hope to have something constructive to add soon 👍

**Comment by beaucarnes** [comment]
@borntofrappe Yes, that is the new URL to review. And you are right, there is a new test. Thanks for your help reviewing this!

**Comment by borntofrappe** [comment]
A few notes on the starter files.

## arithmetic_formatter.py

The starter code fails not because the function is incomplete, but because there is an error in the return value

```diff
def arithmetic_arranger(problems):

-    return arranged_problems
+    return problems
```

I believe this comes from the previous version of the project, but it's worth a fix.

## test_module.py

A very minor fix to line 7, where the word arrangement is missing a letter.

```diff
-test_arangement
+test_arrangement
```

## README.md

The README file is clear enough, but I have a few suggestions for the wording of a few sentences.

The paragraph introducing the assignment can be re-worded to add more emphasis to the input argument and return values.

> Create a function that receives arithmetic problems as a list of strings, and returns the problems arranged vertically and side by side. The function should optionally take a second argument in a boolean. When this argument is set to `True`, the function should also display the answer to the arithmetic problems.

The list of rules is perhaps better introduced describing the requirements in two separate bulleted lists.

> In the following instances, the function should return a string describing a meaningful error message.
>
> - if there are more than five problems, return `Error: Too many problems.`
>
> - if the problems include the multiplication `*` or division `/` characters, return `Error: Operator must be '+' or '-'.`
>
> - if the operands include characters other than numbers, return `Error: Numbers must only contain digits.`
>
> - if the operands have more than four digits, return `Error: Numbers cannot be more than four digits.`
>
> When formatting the problems, the function should return a string following these rules:
>
> - there should be a single space between the operator and the longest of the two operands
>
> - the operator should be on the same line as the second operand
>
> - the operands should be in the order in which they are provided. The first number will be the top one and the second will be the bottom.
>
> - numbers should be right-aligned
>
> - there should be four spaces between each problem
>
> - there should be dashes at the bottom of each problem. These dashes should run along the entire length of each individual problem
>
> Refer to previous examples to see how the output should look like.

**Comment by borntofrappe** [comment]
In the spirit of discussion, I also have a couple of questions regarding the code of `arithmetic_arranger.py`

## Function definition

In the starter project, the function is defined as accepting a single argument.

```py
def arithmetic_arranger(problems):
```

However, the assignment asks for an optional second argument.

```py
def arithmetic_arranger(problems, show_solutions=False):
```

Should we initialize the argument, or let the campers fill in the required syntax? Given the structure of the README, it seems reasonable to leave the code as-is, but I wanted to ask for a second opinion still.

It is worth mentioning that, without the mention of the optional argument, there is an error with the final test, as the function is called with more positional arguments that it is equipped to.

```py
def test_solutions(self):
        actual = arithmetic_arranger(["32 - 698", "1 - 3801", "45 + 43", "123 + 49"], True)
```

Something to be aware of when testing the program.

## import libraries

Campers should be able to complete the assignment without importing additional libraries. However, and especially after solving the challenges of the **Python for Everybody** module, it seems reasonable to import the `re` library. The module provides the perfect function to ensure that the operands contain only digits.

Perhaps it excessive to add the import statement in the initial code, but should we add a line in the README on the use of libraries, whether they are accepted and in which measure?

I hope the questions are clear enough. Let me know if you need further input :)

**Comment by scissorsneedfoodtoo** [comment]
Hi @borntofrappe, thanks for all of your helpful suggestions. 

I went in and changed `test_arangement` to `test_arrangement` in the test module. As for `return arranged_problems`, I believe that was intentional to help communicate that the problems should be arranged as a string, which students should create themselves. But we could certainly change it since the test module isn't directly calling an `arranged_problems` method.

You bring up good points about the function definition and possibly adding a "Do not import any Python libraries" note. I'm not sure it's necessary here because `re` doesn't totally trivialize the challenge like `time` might for the Time Calculator challenge. What do you think @beaucarnes?

**Comment by borntofrappe** [comment]
I see your point @scissorsneedfoodtoo 

Using the `re` library requires building a regular expression, which in and of itself is a good exercise. 

I now also understand the reasoning behind the default return statement, and apologize for having made the same suggestion in the Time Calculator project. It works as a prompt, to give a direction to campers 👍

**Comment by scissorsneedfoodtoo** [comment]
No worries @borntofrappe, thanks for all of your great suggestions. It's definitely worth considering everything you pointed out, even with the default return statement. I'm sure other people will point out the same thing and we're always open to making changes to improve clarity.

**Comment by anant772** [comment]
It is Showing i have failed Test 1 and Test 2 but my output is correct


   32      3801      45      123    
+ 698    -    2    + 43    +  49    
-----    ------    ----    -----    




F..


F..
======================================================================
FAIL: test_arangement (test_module.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\anant\OneDrive\Desktop\Study Material\puthon prog\test_module.py", line 11, in test_arangement
    self.assertEqual(
AssertionError: '    [23 chars]  123    \n+ 855    -    2    + 43    +  49   [37 chars]  \n' != '    [23 chars]  123\n+ 
855    -    2    + 43    +  49\n-----[23 chars]----'
-     3      3801      45      123
?                                 ----
+     3      3801      45      123
- + 855    -    2    + 43    +  49
?                                 ----
+ + 855    -    2    + 43    +  49
- -----    ------    ----    -----
?                                 -----
+ -----    ------    ----    ----- : Expected different output when calling "arithmetic_arranger()" with ["3 + 855", "3801 - 2", "45 + 43", "123 + 49"]

======================================================================
FAIL: test_solutions (test_module.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\anant\OneDrive\Desktop\Study Material\puthon prog\test_module.py", line 52, in test_solutions
    self.assertEqual(
AssertionError: '   3[23 chars]  123    \n- 698    - 3801    + 43    +  49   [83 chars]  \n' != '   3[23 chars]  123\n- 
698    - 3801    + 43    +  49\n-----[57 chars] 172'
-    32         1      45      123
?                                 ----
+    32         1      45      123
- - 698    - 3801    + 43    +  49
?                                 ----
+ - 698    - 3801    + 43    +  49
- -----    ------    ----    -----
?                                 ----
+ -----    ------    ----    -----
+  -666     -3800      88      172-   -666
-   -3800
-   88
-   172
 : Expected solutions to be correctly displayed in output when calling "arithmetic_arranger()" with arithemetic problems and a second argument of `True`.

----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (failures=2)

**Comment by anant772** [comment]
`

   32      3801      45      123    
+ 698    -    2    + 43    +  49    
-----    ------    ----    -----    




F..


F..
======================================================================
FAIL: test_arangement (test_module.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\anant\OneDrive\Desktop\Study Material\puthon prog\test_module.py", line 11, in test_arangement
    self.assertEqual(
AssertionError: '    [23 chars]  123    \n+ 855    -    2    + 43    +  49   [37 chars]  \n' != '    [23 chars]  123\n+ 
855    -    2    + 43    +  49\n-----[23 chars]----'
-     3      3801      45      123
?                                 ----
+     3      3801      45      123
- + 855    -    2    + 43    +  49
?                                 ----
+ + 855    -    2    + 43    +  49
- -----    ------    ----    -----
?                                 -----
+ -----    ------    ----    ----- : Expected different output when calling "arithmetic_arranger()" with ["3 + 855", "3801 - 2", "45 + 43", "123 + 49"]

======================================================================
FAIL: test_solutions (test_module.UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\anant\OneDrive\Desktop\Study Material\puthon prog\test_module.py", line 52, in test_solutions
    self.assertEqual(
AssertionError: '   3[23 chars]  123    \n- 698    - 3801    + 43    +  49   [83 chars]  \n' != '   3[23 chars]  123\n- 
698    - 3801    + 43    +  49\n-----[57 chars] 172'
-    32         1      45      123
?                                 ----
+    32         1      45      123
- - 698    - 3801    + 43    +  49
?                                 ----
+ - 698    - 3801    + 43    +  49
- -----    ------    ----    -----
?                                 ----
+ -----    ------    ----    -----
+  -666     -3800      88      172-   -666
-   -3800
-   88
-   172
 : Expected solutions to be correctly displayed in output when calling "arithmetic_arranger()" with arithemetic problems and a second argument of `True`.

----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (failures=2)`

**Comment by anant772** [comment]
Can anyone tell me what is the problem in my code .
Code is running successfully and the output is also same as the required output but I can not clear the Test.
**PLEASE HELP ME**
`def arithmetic_arranger(problem,x=False):
    ab=False
    ab=x
    x=[]
    y=[]
    z=[]
    cal=[]
    row1=""
    row2=""
    row3=""
    row4=""
    for key in problem:
        problem1 = key.split()
        x.append(problem1[0])
        y.append(problem1[2])
        z.append(problem1[1])
    no_of_input = len(problem)
    if(no_of_input<=5): 
        
    
        for i in range(no_of_input):
            if z[i] not in ["+","-"]:
                return "Error: Operator must be '+' or '-'."
            try:
                if (isinstance(int(x[i]), int)) and isinstance(int(y[i]), int):
                    q=""
            except:
                return "Error: Numbers must only contain digits."
            if (int(x[i])>=10000) or (int(y[i])>=10000):
                return "Error: Numbers cannot be more than four digits."
        for i in range(no_of_input):
            s1=" "
            xlen = len(str(x[i]))
            ylen = len(str(y[i]))
            if xlen < ylen:
                xdif = ylen-xlen
                for j in range(xdif):
                    s1 = s1+" "
                #print(s1,int(x[i]),"   ",end="")   
                row1 = row1 + s1 + " " + x[i] + "    "
            else:
                #print(" ",int(x[i]),"   ",end="")
                row1 = row1 + "  " + x[i] + "    "
        row1=row1+"\n"
        for i in range(no_of_input):
            s2=""
            xlen = len(str(x[i]))
            ylen = len(str(y[i]))
            if xlen <= ylen:
                #print(z[i], int(y[i]), "   ",end="")
                row2 = row2 + z[i]+ " " + y[i] + "    "
            else:
                xdif = xlen - ylen-1               
                for j in range(xdif):
                    s2 = s2+" "
                #print(z[i],s2,int(y[i]), "   ",end="")
                row2 = row2 + z[i] + " " + s2+" " + y[i] + "    "
        
        row2=row2+"\n"  
        for i in range(no_of_input):
            dash="--"
            xlen = len(str(x[i]))
            ylen = len(str(y[i]))
            max1 = max(xlen,ylen)
            for j in range(max1):
                dash=dash+"-"
           # print(dash,"   ",end="") 
            row3= row3 + dash + "    "       
    else:
        return "Error: Too many problems."
    if ab == True:
        row3 = row3 + "\n"
        for key in problem:
            cal.append(eval(key))
        for i in range(no_of_input):
            k=""
            xlen = len(str(x[i]))
            ylen = len(str(y[i]))
            max1 = max(xlen, ylen)
            clen=len(str(cal[i]))
            for g in range(max1-clen):
                k=k+" "
            if(max1>=clen):
               # print(k,"",cal[i], "   ",end="")
                row4 = row4 + k + "  "+str(cal[i])+"    "
            else :
               # print("",cal[i],"   ",end="")
                row4 = row4 + "  "+str(cal[i])+"    "
            row4=row4 + "\n"
    return row1+row2+row3+row4



`

**Comment by alwaysasking** [comment]
Hey! When I tried running your code, I received some errors. 

(can't use .split() on a list, nor on integers)

for i,problem in enumerate(problems):
        num1,op,num2=problems.split()

remedied by:
 for i in problems:
        a=str(i).split()
        num1=a[0]
        op=a[1]
        num2=a[2]

Then I have a question--I know the test runs to check if we followed the guidelines, but is the output supposed to say FAILED (failures=6) at the bottom? Did I mess up?

https://replit.com/@alwaysasking/boilerplate-arithmetic-formatter#arithmetic_arranger.py 

^^ the code I submitted

**Comment by scissorsneedfoodtoo** [comment]
Hi @alwaysasking, thanks for reaching out about this.

For help with the coding challenges, please check out the forum at https://forum.freecodecamp.org. The contributors there are very active, and can help answer and questions you might have.

Also, there's a good chance that someone else had a similar issue and was able to work it out, so please make sure to search through the existing threads before creating a new one.
