### ISSUE TITLE
Applied Information Security Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#25]
@Greenheart is in charge of coordinating the expansion of these challenges, but he needs your help.

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

We still need to come up with a list of concepts to cover, where each topic can be taught interactively, then translate these concept into the names of the challenges.

**Comment by Greenheart** [comment]
I've gathered some resources that could be useful when creating these challenges in [#6669](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6669).

The idea back in February was to create big projects that encompassed several smaller topics. The main reason was that at least I think it's funnier to learn when it feels like I make progress on a project, rather than just working through loads of smaller challenges without seeing how they fit together.

But I guess the same effect could be achieved through splitting challenges in to sections of something like 5-10 challenges.

**Comment by Greenheart** [comment]
# List of Topics
This is an initial suggestion that needs to be discussed and refined. It's important to focus on the quality of challenges the rather than number of topics we can cover. Therefore something like this could be enough to start with.

### 1. String sanitation - Suggested by @MayankPratap
The fundamental knowledge required to work with untrusted user input. Would it make sense to introduce this section before the one about XSS? Or should this come **when they've seen the threats of XSS in action?**

---

### 2. XSS - Cross Site Scripting
#### Idea 1
I don't know how FCC's editor environment works internally or if it's capable of hosting an simulated full stack app where user input that users think are "sent to the server" actually is handled by the app's frontend.
If this is possible, one idea could be to create a vulnerable app that learners need to patch up over the course of several smaller challenges.

#### Idea 2
Use [Google's XSS-game](https://xss-game.appspot.com/) - 6 challenges of intermediate difficulty, tested by @Greenheart - "Great challenges that are ready to be used as is **if we get permission from Google**"

---

### 3. CSRF - Cross Site Request Forgery

### 4. OWASP NodeGoat
Not tested but seems to be reasonably maintained and of at least decent/good quality.


---

## Not sure about what order the following sections should come in or where they fit in.

### Authentication
* How to handle passwords
* Passwordless auth
* 2-factor auth

### HTTPS
* Set up Node with Let's Encrypt or similar


### Public / Private Keys for Encryption
* Encrypt files or data
* Show campers how GitHub's Public/Private Key pair works (as an example)

---

# Possible Future additions

Some ideas that might not fit for this format of challenges but could be added as video challenges.

### Secure Server Setup
* Disable root-login by password.
* Configure ports (ssh should not run on )

###  DDoS
**Probably more suited for a theoretical tutorial** since this is related to DevOps
* What it is
* How to prevent it

**Comment by SamAI-Software** [comment]
> #### Learn about the target="_blank"-vulnerability
> Note: Should we even promote the use of this functionality in the first place?

Great question! As FCC already uses it everywhere for external links, we can stick to this practice for consistency even though Chris Coyier will call us greedy.

- internal links `target="_self"` (default)

- trusted external links `target="_blank"`

- other external links `target="_blank" rel="noopener noreferrer"`
  - and for window.open() ```var newWnd = window.open();
newWnd.opener = null;```

**Comment by QuincyLarson** [comment]
@Greenheart Someone just published a big security checklist for web developers. Do any of these topics seem like things we can/should cover in these challenges?  https://github.com/FallibleInc/security-guide-for-developers

**Comment by SamAI-Software** [comment]
Btw, `rel="noopener"` would not only increase security, but [it will also increase the performance](https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/).
Doesn't work in Firefox for me, but does work in Chrome.
The article has a very cool interactive example that can be also repeated in the curriculum in a similar way.

**Comment by Greenheart** [comment]
@QuincyLarson Thanks, loads of good content!

@SamAI-Software Good idea! I would need help creating it though :blush:

**Comment by Greenheart** [comment]
The current state of the curriculum https://gist.github.com/Greenheart/13e3afab33903cb188810e496754131f

**Comment by QuincyLarson** [comment]
Issue merged into https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44
