### ISSUE TITLE
Page View Time Series Visualizer (Certification Project)

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/CurriculumExpansion#281]
Project prototype: https://repl.it/@BeauCarnes/fcc-time-series-visualizer

**Comment by rlabuonora** [comment]
## General comments

- I really liked this project. I would add a few words about the overall objectives of the project (understanding the patterns in visits to fcc page teasing out the year by year growth from monthly seasonality).
- The structure of the project (and starter code) could be a little clearer. I think the data loading and preparation for each visualization should be in a different function and have separate tests bc this step is complex enough to require thought.
- I think the comments should reflect this structure too, and some information in the comments should be in the instructions (e.g. copying the data frame). I think this is an important enough step to be mentioned directly in the instructions.

>> Use Pandas to import the data from "fcc-forum-pageviews.csv"

I would add setting the index as Date time in the instructions and include a test case for this step.

>>> Clean the data by filtering out days when the page views were in the top 2.5% of the dataset or bottom 2.5% of the dataset.

I would add tests for this step.

**Comment by scissorsneedfoodtoo** [comment]
@rlabuonora, thank you for your detailed review. We certainly want to make the instructions as clear as possible and can look into the best way to have comments in both `time_series_visualizer.py` and `README.md`.

 We can explore having the data copying and prep for each visualization handled by separate functions, though I worry the code will get a bit messy for the user. My thinking is that, so long as each function returns a valid figure, we can assume that the data was prepped correctly. This is definitely something we can discuss more.

We'll also consider moving the data loading and prep into separate functions for testing. Alternatively we should just be able to call `time_series_visualizer.df` from `test_module.py` and check the length of that. Here's an example: https://repl.it/@scissorsneedfoo/fcc-time-series-visualizer-1

Another thing I found is that `main.py` in the boilerplate calls `time_series_visualizer.draw_box_plot()` rather than `time_series_visualizer.draw_box_plots()`. Just noting it here so we don't forget to fix that.

**Comment by rlabuonora** [comment]
It is sometimes said that 80 percent of a data scientist’s valuable time is spent simply finding, cleansing, and organizing data, leaving only 20 percent to actually perform analysis.

I think separating the code has highlights the importance of data preparation, which is arguably the most important step in creating a visualization.  I also think that adding tests will help guide the student through the task and leave less points where he or she hits a wall. 

>>> Alternatively we should just be able to call time_series_visualizer.df from test_module.py and check the length of that.

That looks great, but I think we're missing a nice opportunity to teach `groupby`, `reset_index`, and all the functions you used for data prep.

**Comment by scissorsneedfoodtoo** [comment]
I have heard that from data scientists, too. 

It's true that we want to teach `groupby`, `reset_index`, and other functions for data prep, but generally we want these projects to be as open ended as possible. These are all things we will definitely go into with the optional projects leading up to these required projects, though. I could see writing more tests if it's required to use those functions to create the charts. It can be a difficult balance to strike.

Did you separate the code in your own solution? If so, could we take a look? It would be a big help if we go down the route of testing the data prep along the way.

**Comment by rlabuonora** [comment]
I created separate variables, here is a [link to my solution](https://repl.it/@rlabuonora/fcc-time-series-visualizer). Maybe you could add tests for `df_box`, `df_no_outliers` and `df_bar` directly?

I caught another typo: in the starter code, `main.py` calls `time_series_visualizer.draw_box_plot()`, but the template in `time_series_visualizer.py` is for `draw_box_plots()`.

**Comment by rayjohnson529** [comment]
1) "Clean data by filtering out days when the page views were in the top 2.5% of the dataset or bottom 2.5% of the dataset"

Just an opinion here, so feel free to skip . . . I found that resolving this problem with numpy was more readable/mapped to the wording of the question/ and was more practical (to me).

Not sure if Numpy is used in order data analysis projects, but if not, this might be a chance to use it.

I also read somewhere that the speed is faster using np.percentile. (But I lost the source and didn't time it myself.)

I realize numpy is not a part of this project, but it's pretty popular among analysts/data scientsts/etc., and I thought I'd mention that.

The code would be:
df = df[df.value.between(np.percentile(df.value, 2.5), np.percentile(df.value, 97.5))]

2) "Make sure the month labels on bottom start at "Jan" and the x and x axis are labeled correctly."

This part caught me off guard because it seemed as if you wanted to reorder the elements. . . it took some data exploration to figure out, but I'm pretty sure it meant you wanted to eliminate partial years.

Assuming that's true, there's wording that would allow for the discovery of that but wouldn't lead someone down the path of mistakenly attempting to reorder them.

I'm just curious, if the reason for this exclusively to get the months to go in order? Or does it have to do with skewing the data somehow?

**Comment by beaucarnes** [comment]
@rlabuonora Thanks so much for your detailed suggestions. I incorporated some of your suggestions, including testing some of the data cleaning. While you had a good point why to move the data preparation out of the main functions, so far I've kept that part in the functions. Since the data preparation is specific to a type of chart, it makes since to me to keep the related code together.

@rayjohnson529 Your right that numpy could be a a good choice for the data cleaning. We'll leave the instructions open ended so users can use either pandas or numpy.

For the part about making sure that the months start at "Jan", it is because depending on how the chart is made, the months could start at a different month since the data does not start at January. Maybe the instructions were unclear, though. Do you think this section could be made better?
