### ISSUE TITLE
Add lessons to Rosetta Code (Coding Interview Section)

### ISSUE THREAD

**Issue by anastasiasoenjoto** [freeCodeCamp/CurriculumExpansion#296]
Hi I wanted to add these challenges to Rosetta Code in the coding interview section: 
-  FizzBuzz: I made a [pull request](https://github.com/freeCodeCamp/freeCodeCamp/pull/38610) for this. 
- Self Describing Numbers: I made a [pull request](https://github.com/freeCodeCamp/freeCodeCamp/pull/38727) for this.

**Comment by scissorsneedfoodtoo** [comment]
@anastasiasoenjoto, sorry I'm just seeing this now. I'll take a look at your ports ASAP.

Also, I saw that you were directed to open an issue here to discuss more Rosetta Code ports. @NitronR has really been a huge help improving the Rosetta Code challenges on freeCodeCamp. This issue will be a good place to discuss future ports so you both don't end up working on the same challenges.

**Comment by NitronR** [comment]
@scissorsneedfoodtoo I have noticed that some problems from Arcade mode were not moved to curriculum. For example, some of the problems from [this](https://github.com/freeCodeCamp/arcade-mode/tree/master/client/scripts/challenges/rosettacode/formatted/F)  folder were not moved.
@anastasiasoenjoto Thank you for the work. You can go ahead and add these. I am currently working on the challenges that start from letter M to letter S.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for confirming that @NitronR. Perhaps @anastasiasoenjoto can work on those missing problems next.

@anastasiasoenjoto, just to give you a bit of context, @NitronR and other were working on Arcade Mode some time ago, but eventually that got folded into the main platform's Coding Interview Prep section. The only thing we need to be careful of is not to port over problems that already exist in other areas of the Coding Interview Prep section. 

For example, some of the Rosetta Code sorting challenges were ported over, but we decided to [remove them](https://github.com/freeCodeCamp/freeCodeCamp/pull/35547) because there were already similar problems in [Coding Interview Prep/Algorithms](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/).

That said, while we already have a modified version of [General FizzBuzz](https://rosettacode.org/wiki/General_FizzBuzz), your PR to add a more basic version of FizzBuzz seems fine -- both challenges are different enough, and we don't seem to have another version of FizzBuzz available.

**Comment by anastasiasoenjoto** [comment]
@scissorsneedfoodtoo @NitronR Thank you for your response! I can definitely work on these missing problems next. I'll make sure to double check so that I don't create similar problems.

**Comment by scissorsneedfoodtoo** [comment]
@anastasiasoenjoto, awesome, thank you for helping us improve this section of the Coding Interview Prep section! Looking forward to seeing all the challenges you and @NitronR create.

**Comment by anthonyzeng99** [comment]
I've added a lesson for "Run-length Encoding" here:
https://github.com/freeCodeCamp/freeCodeCamp/pull/38743

@NitronR Sorry, I didn't see that you were working on lessons through S. I finished this
one before I saw your comment.

**Comment by NitronR** [comment]
@anthonyzeng99 No problem. Thank you for your hard work :)

**Comment by kylayujiri** [comment]
Hi, I'm working with @anastasiasoenjoto and I was looking through the Arcade mode challenges that @NitronR linked. If my crosschecking is correct, then the following problems have not been moved over to the Interview Prep section:

- FASTA
- Find largest left truncatable prime in a given base
- Find palindromic numbers
- Find last Sunday (however, this one is similar to Project Euler's Find Sundays)
- Find missing permutation
- Five weekends
- Floyd-Warshall algorithm
- Formatted numeric output
- Forward difference
- Four bit adder

Let me know if I have made a mistake in my crosschecking, but I think we will start working on porting them over!

**Comment by NitronR** [comment]
@kylayujiri Thanks for checking those out. You can definitely work on these. I would suggest using the content from the files themselves as only the format is different and it would be faster to port these over. These file contents were already reviewed and hence they are mostly good to use as is.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for taking a look at all of those @kylayujiri. You're right, all of those seem to be missing from the current Rosetta Code challenges. Also, feel free to port "Find Last Sunday" challenge -- it seems different enough from the Project Euler problem.

And thanks for joining the porting effort @anthonyzeng99. I'll take a look at your PR now.

**Comment by kylayujiri** [comment]
I believe I missed the following challenges when cross-checking so I'll work on moving these to the Rosetta Code Interview Prep Section as well.

- Fast Fourier transformation
- Filter
- Find common directory path
- Flatten a list
- Floyd’s triangle
