### ISSUE TITLE
Responsive Web Design Project: Pure CSS Portfolio Page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#36]
We are introducing a few new front end projects to give campers more experience working just with HTML and CSS before adding JavaScript to the mix.

Here are the agile use stories for this challenge:
1. I can access all of the portfolio webpage's content just by scrolling.
2. I can click different buttons that will take me to the portfolio creator's different social media pages.
3. I can see thumbnail images of different projects the portfolio creator has built (if you haven't built any websites before, use placeholders.)
4. I can navigate to different sections of the webpage by clicking buttons in the navigation.

We are looking for a volunteer who can build a working demo of this on CodePen using only HTML5 and CSS (no libraries). This should be simple and unambitious. We want the result to be in line with what a camper who's new to coding can realistically achieve themselves.

**Comment by SamAI-Software** [comment]
That's actually an interesting topic, why do we have portfolio project so early in the course?
As a result we have lots of low-quality portfolio pages which don't follow web trends and cannot compete on the market, so they won't help campers to get a job.

Personal portfolio page is the first or at least the second link that HR will check after the resume (CV).
I always have new visitors on my personal page after sending CVs. So may be it makes sense to put it at the end of the Frond End course and give campers an example of great portfolio page?

Some examples for inspiration:

- [Awesome interactive **"projects"** section with fancy sorting feature](http://jasonfallas.com/)

- [Interesting layout for **"projects"** section](http://xiaoweiz.com/)

- [Minimalistic multi-pages flat design](http://stephaniebriones.com)

- [Interactive design with a human body](https://www.patrickelhage.com/)

- [A bit weird UI, but informative and nice easy animations](http://tairemadailey.com/)

- [Looks like a template, but very informative flat design](http://imomen.com/)

Conceptual (good for small nerdy startups)

- [Web brutalism style](http://www.stephanemartinw.com/a-propos-de-stephane-martin)

- [Funny web brutalism with hilarious favicon and title changes when switch tabs](http://imomen.com/) (Doesn't work in Firefox)

- [My interactive CV with Yoda](http://codepen.io/SamAI-Software/full/ZOLOpN) (I didn't land a job yet, but some employers contacted me only because of it and even said thanks for an interesting CV)

If you want more inspiration, I'm collecting interesting examples [here.](https://www.pinterest.com/samaisoftware/portfolios/)

**Comment by atjonathan** [comment]
+1

**Comment by QuincyLarson** [comment]
The reason we had it so early was because we needed a simple HTML/CSS project to give campers practice, and this is a good one that affords lots of options and creativity.

We will probably move the portfolio challenge to be the last of the HTML/CSS project for this reason, so that campers have some projects to list in it.

**Comment by charlesBak** [comment]
hi how to i show the portofolio page i made with HTML/CSS?

**Comment by QuincyLarson** [comment]
@charlesBak we are looking for one that is simpler (no paralax images) and does not use any libraries such as Bootstrap. Could you build one from your own HTML and CSS?

**Comment by oalhait** [comment]
I'll get to work on this. Can it use specific cool repos (say [particles.js](https://github.com/VincentGarreau/particles.js)) in it?

**Comment by ChaituVR** [comment]
@QuincyLarson Hey I already finished it here http://codepen.io/ChaituVR/full/PzXOVv/ ... Sorry i forgot to comment this,,, @oalhait hey if you have already started one .. finish it.. its good to have an alternative

**Comment by QuincyLarson** [comment]
@ChaituVR Excellent work! Yes - this has all the functionality I was hoping for! Only 170 lines of CSS, too! :)

@oalhait if you haven't started on this yet, I would recommend moving on to other related issues where we can use help, such as our visual design challenges :)
