### ISSUE TITLE
Minimalist example projects with tests: Pomodoro Clock

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#57]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [ ] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [ ] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

The current project: https://www.freecodecamp.com/challenges/build-a-pomodoro-clock

**Comment by no-stack-dub-sack** [comment]
I am beginning to work on user stories for this

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, @Weezlo Hey guys, as I started to work on this, I quickly realized that this project is not nearly as straight forward as the calculator project in terms of testing, albeit less complex from a code point of view.

So far I've come up with a list of required elements for programatic testing, a first draft of user stories, and [this ](http://codepen.io/no_stack_dub_sack/pen/BLbXBo) (very) simple example project (which I can stylize later if we agree that the functionality is acceptable). It is built with React.
 
But, I could use a bit of guidance on the following points:

### Functionality 
Since the functionality of the app is in some ways more complex that the last project, it also means a lot of user stories. Even though there are many, they only account for testing the basic functionalities (incrementing, decrementing, starting, stopping, switching timers, indicating switch etc.) Can we decide which functionalities should be required and narrow these down a bit? 

In my example, like in the current example, the timer is cyclical, with breaks and sessions starting automatically at zero. Should this be required? The original project instructions do not specify anything in regards to a break timer, yet it is a central part of the current example. Thoguths on this?

### User Stories / Testability
What I'm really not sure about on this one, is how testable some of the stories are. Numbers 1-6 are no problem, but it gets a little more complicated after that. @Weezlo, can you weigh in on this? 
- Will the fact that some of the tests require the timer cycle to run all the way through mean the tests cannot complete until the countdown completes? 
- Also, some of the tests are not as simple as pressing a button and confirming an expected output, so not sure how to write even manual tests for these.

@Weezlo, maybe we can arrange that Skype call at some point after all to speed up communication on this. 

Anyway, my Pomodoro just ended so gotta run, this is what I have so far but obviously needs some work:

## Required Elements:
- An element that contains the string "Break Length" with corresponding id="break-title"
- An element that contains the string "Session" Length with corresponding id="session-title"
- Two clickable elements that contain a minus symbol ( - ) with corresponding IDs: id="break-decrement" and id="session-decrement"
- Two clickable elements that contain a plus symbol ( + ) with corresponding IDs: id="break-increment" and id="session-increment"
- An element with corresponding id="break-length"
- An element with corresponding id="session-length"
- An element that by default contains the string "Session" with corresponding id="current-timer"
- An element with corresponding id="time-left"
- A clickable element with id="start_stop"
- A clickable element with id="reset"

## User Stories:
1. On load, my Pomodoro Clock displays a value of 25 in the element with id="session-length".
- On load, my Pomodoro Clock displays a value of 5 in the element with id="break-length".
- When I click the element with the id of "break-decrement",  the value within id="break-length" decrements by a value of 1.
- When I click the element with the id of "break-increment",  the value within id="break-length" increments by a value of 1.
- When I click the element with the id of "session-decrement",  the value within id="session-length" decrements by a value of 1.
- When I click the element with the id of "session-increment",  the value within id="session-length" increments by a value of 1.
- When I first click the element with id="start_stop", the timer should begin running from the value currently displayed in id="session-length".
- If the timer is running, the element with the id of "time-left" should display the remaining time in mm:ss format (e.g. 24:59), decrementing by a value of 1 every  1000ms.
- If the timer is running and I click the element with id="start_stop", the countdown should pause.
- If the timer is running and I click the element with id="start_stop", the countdown should resume.
- When a session countdown reaches zero, and a new countdown begins, the element with the id of "current-timer" should display the string "Break", indicating a break has begun.
- When a session countdown reaches zero, a new break countdown should begin, counting down from the value currently displayed in the id="break-length" element.
- When a countdown reaches zero, a sound indicating that time is up should play.
- When a break countdown reaches zero, and a new countdown begins, the element with the id of "current-timer" should display the string "Session", indicating a session has begun.
- When a break countdown reaches zero, a new session countdown should begin, counting down from the value currently displayed in the id="session-length" element.
- While the timer is running, the increment and decrement buttons should be locked.
  - Even though this may seem like overkill, I actually think it’s doing campers a favor, because as I discovered when I first tackled this project a few months ago, modifying the session or break length while a countdown is running can lead to problematic behaviors and unexpected results.
- I should not be able to set a session or break length to <= 0.
- I should not be able to set a session or break length to > 60.
- The element with id="time-left" should never display a negative value (e.g. -00:10).

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Traditionally, Pomodoro involves 25 minutes of work, followed by 5 minutes of break. I think we should enforce this structure with our user stories and test accordingly. 

We should structure these required elements as user stories, as well. For example, 

"An element that contains the string "Break Length" with corresponding id="break-title"" should become "I should see an element with the text "Break Length" and the corresponding id "break-title"

This way there is only one thing the camper has to worry about - addressing all the user stories. This is a small but meaningful distinction. Even though there will still be the same number of tests, they overall process will be perceived as simpler. We can put these basic DOM setup stories at the beginning, since they're relatively easy and give the camper some "small wins" that give them psychological momentum.

This applies to all of the projects that we're creating. We want the first few user stories to be as easy as possible so the camper naturally eases into the hard stuff :)

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Yes - I agree that we should err on the side of giving campers creative freedom where possible. Our tests should aim to verify understanding of the underlying functionality, and minimize dictation of form.

**Comment by no-stack-dub-sack** [comment]
@Weezlo @QuincyLarson, sorry for the delay, crazy busy last weekend. Here is what I have for the app and the user stories. Again, stories are a bit extensive, but can't figure out how to shorted and still represent the functionality we are looking for. Open to suggestions. 

@Weezlo, what do you think about the testability of these? I have some thoughts about what might make some of these difficult to test (without imposing extra restrictions) if you'd like me to share. Taking a stab at writing some of the scripts based on your earlier tests and noticing some issues.

## User Stories:
1. I can see an element that contains the string "Break Length" (be mindful of case!) which has a corresponding id="break-title".
- I can see an element that contains the string "Session Length" which has a corresponding id="session-title".
- I can see two clickable elements that contain a minus symbol ( - ) with corresponding IDs: id="break-decrement" and id="session-decrement"
- I can see two clickable elements that contain a plus symbol ( + ) with corresponding IDs: id="break-increment" and id="session-increment"
- I can see an element, with corresponding id="break-length", which by default (on load) displays a value of 5.
- I can see an element, with corresponding id="session-length", which by default displays a value of 25.
- I can see an element that by default contains the string "Session" with corresponding id="current-timer".
- I can see an element with corresponding id="time-left", that will display the time remaining of the current countdown, in mm:ss format (e.g. 04:59). 
- I can see a clickable element with id="start_stop".
- I can see a clickable element with id="reset".
- When I click the element with the id of "break-decrement", the value within id="break-length" decrements by a value of 1, and I can see the updated value.
- When I click the element with the id of "break-increment", the value within id="break-length" increments by a value of 1, and I can see the updated value.
- When I click the element with the id of "session-decrement", the value within id="session-length" decrements by a value of 1, and I can see the updated value.
- When I click the element with the id of "session-increment", the value within id="session-length" increments by a value of 1, and I can see the updated value.
- When I first click the element with id="start_stop", the timer should begin running from the value currently displayed in id="session-length", even if the value has been incremented or decremented from the original value of 25.
- If the timer is running, the element with the id of "time-left" should display the remaining time in mm:ss format (decrementing by a value of 1 and updating the display every 1000ms).
- If the timer is running and I click the element with id="start_stop", the countdown should pause.
- If the timer is running and I click the element with id="start_stop", the countdown should resume.
- When a session countdown reaches zero, and a new countdown begins, the element with the id of "current-timer" should display the string "Break", indicating a break has begun.
- When a session countdown reaches zero, a new break countdown should begin, counting down from the value currently displayed in the id="break-length" element.
- When a countdown reaches zero, a sound indicating that time is up should play.
- When a break countdown reaches zero, and a new countdown begins, the element with the id of "current-timer" should display the string "Session", indicating a session has begun.
- When a break countdown reaches zero, a new session countdown should begin, counting down from the value currently displayed in the id="session-length" element.
- While the timer is running, the increment and decrement buttons should be locked.
  - Even though this may seem like overkill, I actually think it’s doing campers a favor, because as I discovered when I first tackled this project a few months ago, modifying the session or break length while a countdown is running can lead to problematic behaviors and unexpected results.
- I should not be able to set a session or break length to <= 0.
- I should not be able to set a session or break length to > 60.
- The element with id="time-left" should never display a negative value (e.g. -00:10).

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo So I've forked @Weezlo's test script pen and used his model to get started on writing the tests (hope everyone is cool with this - figured it would save @Weezlo some time!). I've written 13 tests so far, focusing on the ones that are a bit easier and that I was confident I could tackle. [(my tests start on line 235)](https://codepen.io/no_stack_dub_sack/pen/MjNzgB)

We will have to integrate them into @Weezlo's original pen if they are up to standard - but I have one question:

Is it problematic in any way to use Babel as a preprocessor/transpiler to utilize ES6 syntax for these? I have the following tests which rely on `Array().fill()` (could def be written in a another way, but this seemed like the easiest most concise solution):
```
it('25. I should not be able to set a session or break length to <= 0.', function() {
        clickButtonsById(Array(10).fill(_break_min));
        assert.strictEqual("1", document.getElementById("break-length").innerHTML);
        resetTimer();
        clickButtonsById(Array(30).fill(_sesh_min));
        assert.strictEqual("1", document.getElementById("session-length").innerHTML);
      });
```

**Comment by Weezlo** [comment]
@QuincyLarson @no-stack-dub-sack Just to sum up what has been done on my side, I've merged @no-stack-dub-sack's tests into the original pen, made some improvements. The test script is now working with the Quote Machine, the Calculator, and the Pomodoro (corresponding pen: http://codepen.io/Weezlo/pen/ALmBPw)
Some more complex tests still need to be coded for the pomodoro (15->24). I'm working on it.

@no-stack-dub-sack about the babel issue, i think we should definitely encourage people to use ES6 features and we should use them in our code as well. Babel can easily be integrated in any live coding editor.

**Comment by no-stack-dub-sack** [comment]
@Weezlo :+1: cool, I thought so, I just wanted to make sure it didn't interfere with the testing frameworks in any way since these are new to me.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo, I know there's still a few things left to do on this one, but if we are generally happy with the shape of things, I'm going to move on and get the ball rolling on another project.

@QuincyLarson If you'd like to periodically fork for version control, as mentioned in issue #58, the current link for this project is: http://codepen.io/no_stack_dub_sack/pen/BLbXBo. I am also backing up locally periodically.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! That sounds like a plan. 

This looks amazing. You and @Weezlo are doing an amazing job, and I just gave you both a shout-out in gitter.im/freecodecamp/contributors 

I've forked this project and the calculator with Free Code Camp's Gitter account.

**Comment by Weezlo** [comment]
@QuincyLarson @no-stack-dub-sack I've completed the missing tests for the pomodoro project (15->24). It was a bit tricky actually because it implies measuring time, and the script has to test the switch between "Session" and "Break" when time reaches zero. I did my best to keep the code clean, however, it can appear a little bit messy and there is definitely room for optimization. But i did what i could in the short time i had :)

The pen for the test script is still the same: http://codepen.io/Weezlo/pen/ALmBPw (if anyone wants to backup. I have my own at https://github.com/Weezlo/FCCTests)
And you can see the result on @no-stack-dub-sack's Pomodoro: http://codepen.io/no_stack_dub_sack/pen/BLbXBo

There are a few things we need to discuss though:
- I think there is a typo in test # 18, it should be:
`If the timer is **NOT** running and I click the element with id="start_stop", the countdown should resume.`
I corrected that in the test suite and implemented accordingly.
- If we want to test if a sound plays when the timer reaches zero(# 21) -- i've implemented that test and it's working -- we have to add a new user story where we tell the campers to add an <audio> tag with an ID of "beep" (or something else).
- Testing time flow was not easy. For instance, in test # 19, I couldn't afford to let the tests wait a whole minute to see if the pomodoro automatically switches to "break time" when the session time reaches zero. So i had to "Hack" the setTimeout and setInterval functions so that time elapses faster (30ms delay, always). Doing so, it implies that campers use one of these functions to measure time in their pomodoro, if they don't, these tests will fail. 
If somebody has a better idea to test these tricky user stories, he's welcome. 
- I think we should give campers a way to prevent tests execution, by setting a global variable. Example: `const no_test = true`. If the script detects this variable, the tests are not executed.
- For consistency, user stories 25 and 26 should be moved at position 15 and 16 respectively.

**Comment by QuincyLarson** [comment]
@Weezlo awesome! Thank you for the update. @no-stack-dub-sack can you make the changes to these tests sequence them accordingly? Also, perhaps you could QA the tests by applying them to your current Pomodoro design (which seems to have a buggy countdown process, by the way) and verify that the tests all work.

You two are making steady progress toward completing these. I have issued a call for additional help from contributors, who may be able to help speed things up by building on the model you've established for these more advanced projects.

I've also asked to see whether anyone's interested in helping redesign the data visualization projects.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson assuming you were looking my version of the Pomodoro that @Weezlo posted above, just curious, what seems buggy about it to you? If you noticed that the numbers were changing before any buttons were pressed, perhaps this was the tests running. All the tests are already applied to this pen, and all are passing (they just take a few seconds to run based on the nature of them). As I change different pieces of code, they fail accordingly. It is possible that it is buggy in a way I haven't picked up on, however, I painstakingly went through it to make the countdown as accurate and as stable as possible (utilizing AccurateInterval.js to prevent time drift for when a pomodoro is running and a user has the browser minimized or is working in a differnt tab). Anyway, please let me know, more than happy to address any existing bugs that I may have missed.

As for the test sequences, for sure, I can update the user stories according to @Weezlo's suggestions, but I think he will have to update the tests since he has the master pen - it should be just a few edits at this point.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack just to be 100% certain we're talking about the same codepen, could you post the link to the one you're talking about?

**Comment by Weezlo** [comment]
@QuincyLarson As i mentioned in my previous post, here is @no-stack-dub-sack's pomodoro:
http://codepen.io/no_stack_dub_sack/pen/BLbXBo
If the pomodoro looks a little bit "crazy", it's because the 26 tests are performed on the app when you open the pen. 
The tests work perfectly.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson - I was also wondering if perhaps we were talking about different pens, because the one I submitted to FCC a few months ago (which can be viewed from my portfolio page, but I will not post here to avoid further confusion) is a bit wonky. 

But yes, please see the one @Weezlo posted above, this is the correct pen with working tests. Once all the tests have run - you can then begin using the app and check out the countdown process. Re-testing it manually now to be sure ( I've been running the pomodoro concurrently against production timers and making sure 25 min is the same on both - both while the current tab is in focus and when it's not. this was actually quite tricky due to `setItnerval`'s natural drift over long periods of repetition and I would not expect all campers to come up with a solution for this)

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack this is the pen I was talking about, which @Weezlo most recently linked to: http://codepen.io/no_stack_dub_sack/pen/BLbXBo

Is there a better version of this that has the tests?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson better in what sense? Just pinged you on Gitter - maybe it would be easier to chat it out there.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, @Weezlo - I just realized I never made the changes to the user stories @Weezlo mentioned in his post from last week, so I need to get on that. Also - [this Pomodoro](http://s.codepen.io/shawngrooms/full/KNMNxB) made by another camper, makes me want to slightly re-work the user stories. It might mean eliminating a couple and minimal changes to existing tests (which I am happy to take on). I know we also need to move on, but I think this will be a solid improvement. Will post in next day or so with updates.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack When I mentioned the "better" implementation of the project, I misunderstood and thought your project was buggy - actually it was just running tests. 

The current implementation seems fine. No need to re-implement this.

**Comment by no-stack-dub-sack** [comment]
## Final User Stories 

1. I can see an element with `id="break-label"` that contains a string (e.g. “Break Length).
2. I can see an element with `id="session-label"` that contains a string (e.g. "Session Length”).
3. I can see two clickable elements that contain a minus symbol ( - ) with corresponding IDs: `id="break-decrement"` and `id="session-decrement"`.
4. I can see two clickable elements that contain a plus symbol ( + ) with corresponding IDs: `id="break-increment"` and id=`"session-increment"`.
5. I can see an element, with corresponding `id="break-length"`, which by default (on load) displays a value of `5`.
6. I can see an element, with corresponding `id="session-length"`, which by default displays a value of `25`.
7. I can see an element, with corresponding `id="timer-label“`, that contains a string indicating a session is initialized (e.g. “Session”).
8. I can see an element with corresponding `id="time-left"`, that will display the time remaining in the countdown, in mm:ss format (e.g. 04:59).
9. I can see a clickable element with corresponding `id="start_stop"`.
10. I can see a clickable element with corresponding `id="reset"`.
11. When I click the element with the id of "break-decrement", the value within `id="break-length"` decrements by a value of `1`, and I can see the updated value.
12. When I click the element with the id of "break-increment", the value within `id="break-length"` increments by a value of `1`, and I can see the updated value.
13. When I click the element with the id of "session-decrement", the value within `id="session-length"` decrements by a value of `1`, and I can see the updated value.
14. When I click the element with the id of "session-increment", the value within `id="session-length"` increments by a value of `1`, and I can see the updated value.
15. I should not be able to set a session or break length to <= 0.
16. I should not be able to set a session or break length to > 60.
17. When I first click the element with `id="start_stop"`, the timer should begin running from the value currently displayed in `id="session-length"`, even if the value has been incremented or decremented from the original value of `25`.
18. If the timer is running, the element with the id of "time-left" should display the remaining time in mm:ss format (decrementing by a value of `1` and updating the display every 1000ms).
19. If the timer is running and I click the element with `id="start_stop"`, the countdown should pause.
20. If the timer is paused, when I click the element with `id="start_stop"`, the countdown should resume.
21. When a session countdown reaches zero (00:00), and a new countdown begins, the element with the id of "timer-label“ should display a string indicating a break has begun.
22. When a session countdown reaches zero, a new break countdown should begin, counting down from the value currently displayed in the `id="break-length"` element.
23. When a break countdown reaches zero, and a new countdown begins, the element with the id of “timer-label” should display a string indicating a session has begun.
24. When a break countdown reaches zero, a new session countdown should begin, counting down from the value currently displayed in the `id="session-length"` element.
25. When a countdown reaches zero, a sound indicating that time is up should play (should be longer than 200ms and utilize an html5 `<audio>` tag with corresponding `id="beep"`).

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, @Weezlo Made the following changes to Pomodoro User Stories & Tests (final stories posted above):

@QuincyLarson IMPORTANT NOTE: all of this depends on forcing campers to use setInterval() / setTimeout() for these tests to work, as @Weezlo mentioned above.
- Instead of requiring specific strings (e.g. “Break” & “Session”) to signify the current timer – just require some label and test that it changes with each phase of the timer which gives more creative freedom and effectively forces the same functionality (changes inspired by [this camper’s pen](http://codepen.io/shawngrooms/full/KNMNxB), his labels are a bit more creative).  
- Reordered the tests/user stories according to Anis’s suggestions for consistency.
- Deleted the user story requiring the +/- buttons to be locked while the timer is running – this can present tricky problems, but the camper’s pen that I shared above shows there are other reasonable solutions besides locking the buttons.[1]
- Fixed the typo pointed out by Anis

@Weezlo – I’ve been making changes on a fork of [your master pen]( https://codepen.io/Weezlo/pen/ALmBPw).
My version is here: http://codepen.io/no_stack_dub_sack/pen/zoxjvQ 
And my Pomodoro with the passing updated tests is here: http://codepen.io/no_stack_dub_sack/pen/BLbXBo 

So this would be the same thing that we need to do for the tribute page, if you’d like to review and integrate, I PM’d you the lines that changes are on to save space here.

[1] NOTE: There is one problem that needs fixing – for some reason, deleting the user story about locking the buttons while the timer is running, has seemed to prevent the tests from "un-hacking" the global timeout/interval settings and time still runs at 1ms rather than 1s. I couldn’t seem to figure this out but I’m sure will be easy for you.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! Thank you for the update. I've forked your pen. I will work to find someone to start QA'ing these.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson No prob - sounds good! I will move on to another project.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Also, when you do find someone - maybe we should make it a point to have them build it in something else besides React. I can't see why it wouldn't work in another framework, but best to have it proven I suppose.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Awesome. I will do so. I will tweet a link to it, and to the empty codepen with the proper test harness in place. Could you provide me with final links to both?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson You know what, actually - in preparing this, I think I realized we might not be quite there yet, unless they are only forking a blank pen with the test selector variable and a link to the user stories. If we include the test suite in the pen, as I did for [this one](http://codepen.io/no_stack_dub_sack/pen/ObRdab), even when you start adding elements, the tests don't run because some of the tests require button pushes and of course the buttons don't exist yet. 

Until we solve this, if we'd like the QA process to begin, the best solution might be to have them develop the app to the user stories, then test once it's done - because at least all elements will be there, and if certain things were done wrong, the tests will tell them.

So we can have them let you know when they are done, or just instruct them not to un-comment the "test selector" until they are mostly done (but in that case, the `Testing...` button will still appear in the top left corner).

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson - Ok, you can pretty much disregard my previous post. I came up with a basic solution that fixes the problem mentioned above. One thing to note though: I've made some changes to the test scripts which have not yet been reviewed by @Weezlo, but all tests work in example and I'm fairly confident in the code.

Here is the blank codepen for forking with all current test harnesses included (so any of the 4 projects could be ready for QA if we are happy with their current states) and a README that explains the deal: http://codepen.io/no_stack_dub_sack/pen/ObRdab 

And here is the finished Pomodoro project that passes all tests to show campers:
http://codepen.io/no_stack_dub_sack/full/BLbXBo/

You might want to check out the blank pen's comments to make sure you are ok with all of this. If you'd like me to make any changes, let me know.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! I'm tweeting this out now! We'll see who volunteers to tackle this.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack @Weezlo do we know why the test suites only work in Chrome? Is this something we could potentially fix with a refactor?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson I'm going to defer to @Weezlo to answer that question (who I know has been very busy lately) since he built the test suite from the start... 

@QuincyLarson good points have been made already by @P1xt on the Forum page - things we def need to consider...

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, @Weezlo - one camper brought up a good point on the QA thread on the forum for this: I overlooked writing user story that defines the functionality of the reset button. So I have cooked up this additional user story which I have added a placeholder for on the most current version of the test script here (should be in position 11 - it makes more sense logically to put if a few places later, but if this user story isn't done first, the next few won't work): http://codepen.io/no_stack_dub_sack/pen/zoxjvQ

### New User Story: 

When I click the element with the id of "reset", any running timer should be stopped, the value within id="break-length" should return to 5, the value within id="session-length" should return to 25, and the element with id="time-left" should reset to it\'s default state.

Also, we cannot test the last part of this user story since the default state of id="time-left" is never defined to allow for creative flexibility.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack OK - sounds good! Will people who've already started working with your boilerplate need to update anything?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Not at this point, because the test isn't written yet - and both folks who have completed it already have implemented a reset button in this way anyway so would pass the test once it's in place. The function of the reset button is kind of pre-prescribed in this case, it pretty much HAS to have these functionalities for the app to work, so it shouldn't change much.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack excellent. Well in that case, I agree that we should add this user story and test. Thank you for the detailed explanation.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo Here are 2 projects that were written to the tests:

http://codepen.io/P1xt/pen/ObWZgZ4
http://codepen.io/Quickz/pen/vyggKE1

They've both used jQuery and `setTimeout()` rather than `setInterval()`. They are both failing the last 5 tests. My guess is because `clearTimeout()` does not seem to be working to stop time from running for @Weezlo's sped up "global hacks". This is the error message they're getting and you can see the difference when watching the test run on mine vs theirs: `timeout of 5000ms exceeded`.

Hoping this can be fixed from a testing perspective, but if not, we could (reluctantly) scale back what the tests actually do if it seems like it might be too hard to cover all possible implementations.

**Comment by no-stack-dub-sack** [comment]
Creating a couple of to do lists here, mostly for me but just to keep everything straight. 

### Pomodoro To Do:
- [ ] Address issue of last 5 tests - do not seem to be working in projects built for QAing these.
- [ ] Need test for new user story number 11 (define reset button functionality). I have a placeholder with basics tests in the [current test script.](http://codepen.io/no_stack_dub_sack/pen/zoxjvQ)
- [ ] Code review of recent changes to tests (all tests work on example project) - I've noted where changes have been made to make this easier. Includes code I wrote to get tests to work before reset button is implemented. 
- [ ] We need to tell campers somewhere that they have to use either `setTimeout()` or `setInterval()` for this test suite to work. 

### Testable Projects To Do / Important Notes: 
- [ ] Address either getting tests to work in browsers other than Chrome, or add alert that says tests must be done in Chrome.
- [ ] Add another button, or some other way to control when a camper runs tests - "on demand".
- [ ] Make language/style of all user stories consistent - I just thought of this and it can take a back burner for now, but I don't think it's a bad idea and I would be willing to take it on when all user stories are done. 
- [ ] Create a general set of instructions that say how tests work, and how to go about using them (instructions on what to fork, uncommenting variables, browser requirements, etc.)
- [ ] For projects that need clear or reset buttons for tests to work (calc, pomodoro) - check that code that makes tests run before implementation is ok. 
- [ ] Some better form of version control for this - with a minimum of 2 people working on the tests, there are several versions floating around. I've been careful up to this point to track what needs to be merged into Weezlo's current master test script, but this is getting more and more confusing as more changes get made. Maybe we can create a new codepen account that anyone working on these can access?

**Comment by Weezlo** [comment]
Hey @no-stack-dub-sack @QuincyLarson !
Sorry for being so busy these days, I finally found time today to work on this.
@no-stack-dub-sack very good job with the modifications you did.

Here are the last actions I made, and my remarks. Feel free to tell me if I've missed something :

- I have integrated your changes in the "master" pen => http://codepen.io/Weezlo/pen/ALmBPw (I agree that it's not really convenient to be working this way and that we should find another way)
- I'm ok with the modification you made on the "resetTimer" function.
- I'm ok with the modification on the regex for minutes and secondes. 
- I have made a fix to the MutationOberver so the failing tests can pass.

But, 
the tests still cannot pass with P1xt's pomodoro http://codepen.io/P1xt/pen/ObWZgZ because:
- The pomodoro doesn't display zero seconds (00:00) when it reaches zero. It immediately resets the value to the next phase's initial value (Session or Break).
- The pomodoro doesn't use an audio tag with and id of "beep". The corresponding test fails accordingly.

the tests still cannot pass with Quickz's pomodoro http://codepen.io/Quickz/pen/vyggKE because:
- The pomodoro doesn't display the correct initial when switching from Break to Session and from Session to Break (tests 22 and 24).

Finally, I'm not sure I understand why test # 26 (buttons blocked) should be removed.

Please Note that the reference pen for the tests is still this one: http://codepen.io/Weezlo/pen/ALmBPw

The next actions I'll carry out: 
- the button that re-runs the tests "on demand".
- adding a test for user story 11.
- forcing some styles on the test window so campers styles do not interfere.

**Comment by no-stack-dub-sack** [comment]
@Weezlo Awesome!!! And thanks, glad I didn't mess anything up! 

Sounds like some great headway overall - and if I understand correctly, the reason the remaining failing tests are failing is because, for one reason or another, the apps are functioning improperly/do not meet the user stories... which is a good thing! However, in @P1xt's case, I think we could afford to be a bit more clear that the timer MUST display 00:00 before moving to the next timer for this test to pass as this might be a bit ambiguous as is (either in the user stories themselves, or by way of a warning in the test if it fails).

This is excellent and I think represents a great test case for us, because a test is failing, and the message is very clear as to why, so a camper experiencing this should know just what to fix!
![image](https://cloud.githubusercontent.com/assets/18563015/20551574/9b75a550-b10f-11e6-9dbf-160a5fd326b2.png)




> I'm not sure I understand why test # 26 (buttons blocked) should be removed.

I thought this appropriate to afford campers a bit more creative freedom, because I came across [this pen](http://codepen.io/shawngrooms/full/KNMNxB) where the designer simply removes the buttons from the UI when the timer is running. Achieves the same effect, but wouldn't necessarily pass our tests. What do you think?

**Comment by no-stack-dub-sack** [comment]
@Weezlo This is strange - a camper seems to be having the same problem that @P1xt's Pomodoro was experiencing for the last 5 or so tests. What's weird is that, running at @P1xt's Pomodoro off of your latest test script is no longer producing the same clear error message as it was a couple of weeks ago and as is shown in the above post... that is awfully strange.

**Comment by no-stack-dub-sack** [comment]
Ok, it was definitely because the timer didn't hit `00:00` on the new campers pen... the strange part is that it did not give the right error, but I am changing the user stories above, on the forum, and in the tests to make this very clear.

**Comment by Weezlo** [comment]
@no-stack-dub-sack I implemented test # 11 and almost finished implementing the "Run again" button.
I still have a problem with mocha that refuses to execute the test suite twice and give errors the second time it's executed. I should fix that soon hopefully. 
The changes I made are in the new pen: 
http://codepen.io/FCC_test_suites/pen/qqmGXr

The "Run again" button is temporarily hidden until it works properly.

**Comment by no-stack-dub-sack** [comment]
@Weezlo Nice! Thanks, looks like test # 11 is working great!

**Comment by Weezlo** [comment]
@QuincyLarson @no-stack-dub-sack 
"Run again" button is now up and running. 
Any feedback on this feature is welcome (bugs, remarks, suggestions, etc).

Now I have to adapt test # 26 to take into account the loading time of the sound file. For this purpose, I will create a generic function that should be reused in other projects (i.e. Drum Machine).

**Comment by Weezlo** [comment]
as @no-stack-dub-sack suggested I should take the "Run" button outside of the Test window so that tests are manually triggered by the user instead of being automatically fired on every code modification.

**Comment by QuincyLarson** [comment]
@Weezlo awesome! Thanks for the update on the "run again" button. This will be a huge usability breakthrough. I couldn't figure out how to use the demo you linked to. Do we need to pull this into the existing calculator app?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson - try it now - I might have been working on it. Just made some slight changes so that the button is accessible from the main page and the tests don't run automatically on page load so it won't be prohibitive in projects like the Pomodoro and drum machine. Just updated that thread too - check it out!

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack @Weezlo awesome! This works great! This is a huge improvement over the self-running tests.

**Comment by QuincyLarson** [comment]
Here's the forum thread for the QA effort: https://forum.freecodecamp.com/t/pomodoro-clock-with-testable-user-stories-guinea-pigs-needed/56837/33

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
