### ISSUE TITLE
Minimalist example projects with tests: JavaScript Calculator

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#58]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [ ] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [ ] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

The current project: https://www.freecodecamp.com/challenges/build-a-javascript-calculator

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, so I've been thinking about taking this up as you suggested, however, I'm a little concerned that part of this _might_ be too advanced for me at this point. What kind of automated tests are you thinking about? So far, I have no experience in designing automated tests to test code against. How are FCCs tests usually created? I'm by no means the type to shy away from a challenge, so with a little basic guidance, I think I could take this up...


> This means we need to create user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project). #10158 

>  New agile user stories with one automated test each (reply to this issue with the user stories and their tests)

As far as the user stories go, this should be no problem - so we are looking at approximately 10 user stories to go along with each test? 

Lastly, in terms of the project itself - @SamAI-Software mentioned that he shared my codepen with you that can be found [here](http://codepen.io/no_stack_dub_sack/full/rLgEYA/). I take it as this would not quite be considered minimalist. I think I can simplify this a bit more, but I have some questions about what specifically you are looking for to help guide and avoid future back and forth on design/functionality decisions.

- In issue #10158, the 2 types of calculator logic were discussed in quite a bit of depth. Mine is updated with the more modern, Google-esque logic, while the original project is built with the simpler, but more oldschool, Windows/80's Digital Calc logic. For the final updated project, which logic would you like to see used? The more modern logic and some of the features that go along with it, certainly lend to complicating things a bit.
- In terms of UI, would you like to see something simplified even further? I can eliminate features like the scrolling animation when a user's calculation yields a long answer, but in terms of the overall design, is this ok?
- When @SamAI-Software and I were working on re-designing my project, we got stuck on the issue of rounding a bit - to keep things simple, and answers truncated, are you ok with only a few decimal places? Of course, this would lend to overall inaccuracies in certain calculations, and inevitably to campers raising issues about this, but it would allow for a simpler design since handling super long answer strings would not come up as often. 

I know this is a lot to consider, but I am thinking that getting this out of the way now, will lead to a smoother process down the line. Although, the biggest hurdle for me still remains the testing - so if you think that me tackling this will require too much hand holding and take too much time, I would understand, because I would definitely be starting from scratch on that part.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack yes - you have taken this project quite seriously and attacked a number of corner cases that I don't expect an average camper to have the patience to do. You are the perfect person to create these new tests. Perhaps you could start by explaining what the tests do - come up with the copy such as "I should be able to add two numbers together." Then we can actually create the tests once we get the platform up.

As for the design of your calcualtor, if you could create one that uses React/Redux with minimal CSS - really as simple as possible - that would be ideal. Does this sound like something you're up for?

**Comment by SamAI-Software** [comment]
Here is some inspiration for tests for Windows alike calc - [test-ur-calc](https://github.com/SamAI-Software/test-ur-calc)

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, sure, let's do it. I am just beginning to learn React now, so excited to be able to implement. This seems like the perfect opportunity. What is the timeline you are looking at for this project being completed?

Thanks @SamAI-Software, I will take a look at your link and go from there.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack there are a lot of other things we need to build first, so there's no rush. Take your time and think this through. I will let you know if this becomes "critical path" and we become blocked until you to finish.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson ok, that sounds perfect. I'll make this my top free-time priority, but at the same time, full time job (non-dev), getting to know React, etc. etc. I will keep you posted as I hit landmarks in progression or have critical questions only. Thanks!

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack I recently discovered this Pen by @AnisNouira: https://codepen.io/Weezlo/pen/dpXJrp

It's built in Angular, and would need to be simplified, but it has a full test suite which we could model other challenge test suites off of. 

Then campers could fork a pen that already has a project-specific test suite.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson That pen is pretty cool, the test suite especially. The idea of forking a blank pen with a built in test suite I think could work great, especially for more complex projects.

I just finished redesigning my app in React - the logic still follows the "google style" so the code is still kind of complex at points. The pos/neg toggle button adds a ton of complexity and could be removed easily. 

The UI still looks the same, but I think is fairly simple and uses half the CSS as before. The formula display component could also be easily removed if not simple enough. 

there still might be a couple of bugs to work out but mostly finished: http://codepen.io/no_stack_dub_sack/full/jrxpKP/

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack This looks great! Yes - if the pos/neg is particularly difficult to implement, we may want to remove that so campers can keep moving forward instead of spending several hours figuring out how to implement that. You are writing the user stories, so use your best judgement.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson :+1: Thanks! Sounds good, I forked a version before implementing the pos/neg, so I'll fix it up a bit and post that and the user stories in the next couple of days, then we can address the testing piece. 

For now, I am just writing button sequence tests to go along with the user stories that can be entered and tested manually.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack OK - sounds like a plan :) Thanks for lending us your help and expertise 😄

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Well, if we are going for minimalism, I think [this ](http://codepen.io/no_stack_dub_sack/full/amaAzq/) should do it. 

I've simplified it in 2 major ways:

1.  Removed pos/neg toggle functionality
- Removed "clear entry" functionality, now, only 1 clear button that clears all at any state

Both of these functionalities added significant complexity, and this takes the app from about 280 lines of code to 174. This gives campers a much simpler app conceptually to model after - although, I do see some merit in showcasing a more complex app, and clearly stating which functionalities are required and which are not (bonus user stories?), giving more ambitious campers something to strive for. But if the goal is just to keep it as simple as possible...

User stories coming in next post.

**Comment by no-stack-dub-sack** [comment]
## User Stories
1. **You should be able to add, subtract, multiply and divide a chain of numbers of any length.**
  - _Button Sequence:_ `3 + 5 x 6 - 2 / 4 =`
    - Immediate Execution Logic: `11.5`
    - Formula/Expression Logic: `32.5`
    - **NOTE ON LOGIC**– It should be noted in the challenge instructions that there are two main schools of thought on calculator input logic, and that either is acceptable, as long as the logic the camper chooses is executed effectively. We can either write our own brief article on this and point campers to it on the wiki/forum, or link to [this]( https://en.wikipedia.org/wiki/Calculator_input_methods) wikipedia page.
  - _Button Sequence:_ `10 + 5 =`
    - _Output:_ `15`
  - _Button Sequence:_ `10 - 5.5 =`
    - _Output:_  `4.5`
  - _Button Sequence:_ `20 / 2 =` 
    - _Output:_ `10`
  - _Button Sequence:_ `5 x 5.5 =` 
    - _Output:_ `27.5` 
- **Two decimal points in one number should not be accepted**
  - _Button Sequence:_ `5 . . 0` 
    - _Display:_ `5.0`
  - _Button Sequence:_ `5 . 5 . 5` 
    - _Display:_ `5.55`
   - _Button Sequence:_ `. . 2`
     - _Display:_ `0.2`
- **Decimals should append to the current number. If the current number is zero, or if entered immediately following an operator, the decimal should have a leading zero.**
   - _Button Sequence:_ `. 0`
     - _Display:_ `0.0`
  - _Button Sequence:_ `5 x . 5`
    - _Display:_ 0.5
  - _Button Sequence:_ `2 . 3 4`
    - _Display:_ 2.34
  - _Button Sequence:_ `. 0 2 0`
    - _Display:_ `0.020`
- **If 2 or more consecutive operators are entered,  the operation performed should be the last operator entered.**
  - _Button Sequence:_ `5 x - + 5 =` 
    - _Output:_ `10`
  - _Button Sequence:_ `5 + + 5 =`
    - _Output:_ `10`
- **At any time, pressing the clear button initializes the calculator, initialized state should display** `0`.
- **A leading input should not allow multiple zeros.** 
  - _Button Sequence:_ `0 0 0`
    - _Display:_ `0`
  - _Button Sequence:_ `0 2 3`
    - _Display:_ `23`
- **The evaluate button should be locked if a number ends in an operator or a decimal point.**
  - _Button Sequence:_ `5 + 5 + =`  
  - _Button Sequence:_ `5 + 5 . = `
    - _Display:_ Display should remain the same as it was before `=` was pressed
- **Pressing a number immediate following `=` should start a new calculation with that number.**
  - _Button Sequence:_ `5 + 5 = 2 x 2 =` 
    - _Output:_ `4`
- **Pressing an operator immediately following** `=` **should start a new calculation that operates on the result of the previous evaluation.**
  - _Button Sequence:_ `5 - 2 = / 2 =`
    - _Output:_ `1.5`
  - _Button Sequence:_ `5 + 5 = + 3 =`
    - _Output:_ `13`
- **Your calculator should have several decimal places of precision when it comes to rounding. There is no exact standard, but you should be able to handle calculations like** `2 / 7` **with reasonable precision.** 
  - _Button Sequence:_ `2 / 7 =` 
    - _Possible Output:_ `0.285714` `||` `0.285714285714` `||` `0.2857142857142857` etc.
    - _Should Not Output:_ `0.29`
- **Bonus User Story: I should be able to change the sign of a number before or after evaluating**.
  - _Button Sequence:_ `5 ± x 3 =` 
    - _Output:_ `-15`
  - _Button Sequence:_ `5 x ± 3 =`
    - _Output:_ `-15`
  - _Button Sequence:_ `5 x 3 = ± x 2 =`
    - _Output:_ -30
  - _Button Sequence:_ `5 - 10 = ± + 5 =` 
    - _Output:_ `10`

**Comment by zelite** [comment]
> 3. Decimals should append to the current number. If the current number is zero, or if entered immediately following an operator, the decimal should have a leading zero.

I am against this behavior being mandatory. Check how the google calculator works.

It is very common in math and engineering fields to ommit the leading zero from a decimal number. And I think the meaning of a number formatted like that is absolutely unambiguous. So, -1 for that user story.

> 5. At any time, pressing the clear button initializes the calculator, initialized state should display 0.

Some calculators do not display anything on the initial state. So, I do not think it should be forced to display zero.

> 7. The evaluate button should be locked if a number ends in an operator or a decimal point.

If the number ends in a decimal point, then it is a correct number, do not see why there should be any lock. If the number ends in an operator, then the author of the calculator should be able to decide the behaviour. I see two extra acceptable solutions:
i) ignore the operator.
ii) display an error.

I don't think the user stories should force any direction on this behavior.

> 10. Your calculator should have several decimal places of precision when it comes to rounding. There is no exact standard, but you should be able to handle calculations like 2 / 7 with reasonable precision.

In my opinion the other user stories were too specific, this seems to be too vague. How are we gonna test this?

**Comment by no-stack-dub-sack** [comment]
@zelite Thanks for this input, these are all valid points, and totally open to suggestions and re-working these....

These could be changed to:

3) **Decimals should append to the current number (formats with or without a leading zero are acceptable).**

5) **At any time, pressing the clear button returns the calculator to its initialized state.**

6) **If the** `=` **button is pressed immediately following an operator, the calculator should either: a) display an error, b) ignore the trailing operator, or c) lock the** `=` **button.**
- Or ^^this user story could be eliminated. Also, I see your point about the decimal numbers and have updated my code to reflect that. 

For number 10, regarding the rounding, I agree that this is may be a bit vague and difficult to test, but there is no correct answer here, except that the calculators should offer some level of precision. Though we should not enforce rounding to a specific number of decimal places if another answer is just as correct. At the same time, I believe some guidance on this issue should be provided. We could test this by ensuring a campers calculator produces more than 2 decimal places as a result of `2 / 7 =`.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack these user stories are very comprehensive. 

I agree with @zelite that we don't need to enforce a leading zero. These user stories are the bare-minimum, so it's campers can add things like that as they desire.

I don't see this mentioned in the thread, so just to make sure everyone's aware, @Weezlo has already built a calculator with many of the unit tests intact: https://codepen.io/Weezlo/pen/dpXJrp

He's also implemented some functional tests for the Random Quote Machine here, so you can get an idea of where he's planning to go with these: http://codepen.io/Weezlo/pen/qaQEYm

I recommend that you and @weezlo collaborate on this.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson so just to get a sense of what you'd like to see - the calculator built in react with the unit tests built in like in @Weezlo's? Or are you happy with the version he's built for the most part?

@Weezlo - let me know if you have some time to chat on Gitter about collaborating on this.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack it should be a React version. I'm partial to yours, which looks great and uses React. We should see if we can retrofit yours to work with @Weezlo's test suite, then expand his tests to include the additional test cases you proposed.

**Comment by Weezlo** [comment]
@no-stack-dub-sack @QuincyLarson I also think a React version would be more relevant than an angular 1.X one. Ok to adapt the unit tests I made to work with the react version. Does this React app already exist ?
In both cases I'm OK to get in touch with @no-stack-dub-sack and work on it.
There are more things to settle. The user stories must include the part where we ask the campers to assign specific classes and names to their elements and variables so the app can be programmatically tested.

**Comment by Weezlo** [comment]
@QuincyLarson I've just realized that @no-stack-dub-sack has already made the React version.
We should start working on this.

**Comment by QuincyLarson** [comment]
@Weezlo yes - @no-stack-dub-sack is quite good at building un-intimidating user interfaces in React. As time permits, I recommend the two of you collaborate to the extent possible. I think together you will be able to design better challenges than independently.

**Comment by no-stack-dub-sack** [comment]
> We should see if we can retrofit yours to work with @Weezlo's test suite 

@QuincyLarson, ok, just wanted to be clear that that's where were headed... thanks!

@Weezlo, what time zone are you in?

**Comment by Weezlo** [comment]
@no-stack-dub-sack I sent you messages on gitter ? have you received them ?

**Comment by no-stack-dub-sack** [comment]
@Weezlo, here is the latest set of user stories updated as we discussed to allow for programmatic testing (unique IDs for each element). 

@QuincyLarson, The downside to this is that it creates a set of user stories that some might see as too constraining and that are not exactly concise... so if anyone else has any input at this stage (on this or on the below points), let me know. 

Anis, I have also bolded #s 2, 7, 8, and 9 because there are discussion points to be decided on each. Let me know what you think and I can update if need be (we can discuss on Gitter again):

- [ ] Ok to have 2 correct answers for this test to reflect the note to campers? Side note: I'm also not a huge fan of the wiki article I pointed to, so I think a better option might be to write our own short article instead.
- [ ] For user story 7, should we force the initialized state to be `0` so that this can be more easily tested? I know @zelite expressed some dissension on this particular point earlier on, but for testability it seems to make sense (otherwise we cannot reasonably predict what the campers initialized state will be). If so, we could write another brief instruction in the first user story that says this should be the case. 
- [ ] For user story 8, I think this should be the behavior of a well designed calc, but is it too much to ask of campers if we just want them to be able to win "small victories" and move on? This is already a relatively complex project as is.
- [ ] For user story 9, regarding rounding, I know this one’s a bit abstract, but I think we can test this with a RegEx so we can confirm the calculation is correct up to at least 4 decimals. If rounding is done correctly to 4 digits, the answer should be `.2857`, if the camper implements more precise rounding, the answer will still start with `.2857`… So the RegEx might look something like `/0?.2857\d*/`, which should match `.2857` with an optional leading `0` and zero or more trailing digits. Does this work?


## (Mostly) Testable User Stories 
1. At a minimum, my calculator should contain the following elements:
    - A clickable element  containing an `=` with a corresponding `id="equals"`.
    - 10 clickable elements containing one number each from 0-9, with the following corresponding IDs: `id="zero"`,  `id="one"`,  `id="two"`, `id="three"`, `id="four"`, `id="five"`, `id="six"`, `id="seven"`, `id="eight"`, and `id="nine"`.
    - 4 clickable elements each containing one of the 4 primary mathematical operators with the following corresponding IDs: `id="add"`, `id="subtract"`, `id="multiply"`, `id="divide"`.
    - A clickable element containing a `.` with a corresponding `id="decimal"`.
    - A clickable element with an `id="clear"`.
    - An element to display values with a corresponding `id="display"`.
1. **In any order, I should be able to add, subtract, multiply and divide a chain of numbers of any length. I should be able to see my input, and when I hit** `=`, **the correct result should be shown in the element with the id of "display"**.
    - **Note On Calculator Logic:** It should be noted that there are two main schools of thought on calculator input logic: immediate execution and formula logic (our example utilizes formula logic and observes order of operation precedence). Either is acceptable, but please note that depending on which you choose, your calculator may yield different results than ours for certain equations (see below example). As long as your math can be verified by another production calculator, please do not consider this a bug. You can read more about calculator input logic [here]( https://en.wikipedia.org/wiki/Calculator_input_methods).
  - _Button Sequence:_ `3 + 5 x 6 - 2 / 4 =`
       - Immediate Execution Logic: `11.5`
       - Formula/Expression Logic: `32.5`
- When inputting numbers, my calculator should not allow a number to begin with multiple zeros. 
  - _Button Sequence:_ `0 0 0`
   - _Display:_ `0`
-  When the decimal element is clicked, a `.` should append to the currently displayed value. Two `.`s in one number should not be accepted.
  - _Button Sequence:_ `5 . . 0` 
    - _Display:_ `5.0`
  - _Button Sequence:_ `5 . 5 . 5` 
    - _Display:_ `5.55`
- I should be able to perform any operation (`+`, `-`, `*`, `/`) on numbers containing decimal points.
  - _Button Sequence:_ `10.5 - 5.5 =`
    - _Output:_  `5`
  - _Button Sequence:_ `5 x 5.5 =` 
    - _Output:_ `27.5`
  - _Button Sequence:_ `10.5 + 5.5 =`
    - _Output:_  `16`
  - _Button Sequence:_ `10 / 2.5 =`
    - _Output:_  `4`
- If 2 or more operators are entered consecutively,  the operation performed should be the last operator entered.
  - _Button Sequence:_ `5 x - + 5 =` 
    - _Output:_ `10`
  - _Button Sequence:_ `5 + + 5 =`
    - _Output:_ `10`
- **At any time, pressing the clear button clears the input and output values, and returns the calculator to its initialized state.** `0` **should be shown in the element with the id of "display".** 
- **Pressing an operator immediately following** `=` **should start a new calculation that operates on the result of the previous evaluation.**
  - _Button Sequence:_ `5 - 2 = / 2 =`
    - _Output:_ `1.5`
  - _Button Sequence:_ `5 + 5 = + 3 =`
    - _Output:_ `13`
- **My calculator should have several decimal places of precision when it comes to rounding (note that there is no exact standard, but you should be able to handle calculations like `2 / 7` with reasonable precision to at least 4 decimal places).**
  - _Button Sequence:_ `2 / 7 =` 
    - _Possible Output:_ `0.2857` `||` `0.2857142` `||` `0.2857142857` etc.
- (optional) The page should contain a horizontally centered container element with an `id="calc-container"`.
- (optional) The page should contain a vertically centered container element with an `id="calc-container"`.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack this is a good list of user stories. I don't think we need to test for UI elements here (though we'll do that for the responsive design projects).

#1 and #2 should each be several distinct user stories (each story should only test one thing). This means that we will probably end up having closer to 15 user stories.

We should not need to link to external articles, and all explanation of user stories should be the text of the test message (like the tests on Free Code Camp's algorithm challenges). The reason for this is we've observed time and time again the UX phenomenon that "people don't read", so we should assume the only thing they'll look at is the test text.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, :+1: updated user stories again to reflect only testing one item at a time, and nixed the wiki link.

**Comment by Weezlo** [comment]
For all the projects:
Because the test engine will be common to all projects, we also need to add a javascript constant to identify which project is being tested.
something like 
`var PROJECT_NAME="calculator"`

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! Sounds good. 

@Weezlo @no-stack-dub-sack keep in mind that we have 14 other projects that we will ultimately need testable user stories for, so I recommend getting this into reasonably good shape then moving on to the others. I'm happy to provide guidance and QA these :)

**Comment by Weezlo** [comment]
@QuincyLarson You're absolutely right. We need to move on.
After our discussions with @no-stack-dub-sack on the identification of the elements, and the adjustments he did on his example, i could finally develop the automated tests. And everything works perfectly. 
We now have a script that plugs into any project (Random quote machine and Calculator so far) and performs the automated tests on it.
We just have a little problem with the calculator (and we will probably face the same problem for other projects): We need to programmatically reset the calculator between each test, and we do that by clicking the "clear" button. The problem is that it requires that the camper develops the "clear" functionnality first, or all the tests will fail until he does so.
Maybe you should take a look at the result so you can better understand what's happenning.
Here is the @no-stack-dub-sack's calculator with the automated tests embedded: http://codepen.io/no_stack_dub_sack/pen/amaAzq
If you change the id of the "clear" element to something else, all the tests will fail.
Do you think it would be acceptable to advise the campers to implement this "clear" functionnality before anything else ?

**Comment by QuincyLarson** [comment]
@Weezlo is there a way you could force a refresh on the codepen, or clear all the variables some other way if the clear functionality isn't yet functional? 

I agree with you that ideally campers would be able to attack these tests in any order they choose.

I suspect the lessons that you and @no-stack-dub-sack have learned on the calculator and random quote machine will make subsequent challenges much easier to test.

The first few projects are just HTML and CSS, and will probably be significantly easier to test.

The D3 projects are a bit ambiguous. We may need to completely redesign them based on testability.

Keep up the great work. This will be a massive user experience breakthrough for campers building projects!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson - Thanks! :+1:, @Weezlo is doing some awesome work with the test scripts 

I totally agree that the first few project should be much easier to test with this experience under our belts. I am happy to take on the part of forking the apps to add unique IDs to the elements for testability (if they do not already have them as is), and of writing new testable user stories for the first few apps. 

I could try to take on some of the projects that need to be redesigned in a minimalist fashion as well (such as the Pomodoro Clock), but there might already be some viable examples out there that campers have already created...

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack I think it's best for us to take a holistic approach - we can build these example apps from the ground up with testability in mind. By writing the tests first, then building the app, we can get an idea of what campers will go through building them themselves, which will help us create better user stories and instructions.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Sounds good, well I'm happy to help with what I can, I'll start with user stories for projects that don't yet have them and go from there. I will only be able to help up to a point in developing new apps based on my current level, but I'm sure there are many others willing to help!

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Great! I suggest you approach this as a learning opportunity. It is clear that @Weezlo knows a lot (he's an experienced developer and has managed to accomplish many things in a short period of time) and I think you and I can both learn quite a bit from his work 😄

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson That is the only way to approach it as far as I am concerned :smiley:, @Weezlo has told me a bit about his background as well, and it's great that FCC is managing to pair experienced developers with those who can not even quite be considered developers yet! I'm certainly learning a lot and am excited to be able to contribute to FCC being as new at this as I am. 

Just began work on the Pomodoro Clock project last night so looking forward to continuing, appreciate the confidence and opportunity to pitch in.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Awesome! I am thrilled you recognize this as a big learning opportunity. I agree - @Weezlo is a huge asset to our community. We are transitioning Free Code Camp to also be a strong reference resource for experienced developers as well, so @Weezlo may soon be in good company :)

**Comment by Weezlo** [comment]
@QuincyLarson @no-stack-dub-sack Hey guys ! Thanks for all these "facts" about my so called "experience" :) I was out of town for a few days, and back to work now.
I wonder if we have to commit our code somewhere on this github repository, or just let it as it is on codepen ?

**Comment by no-stack-dub-sack** [comment]
@Weezlo, I was wondering the same thing. Especially with the internet being as vulnerable as it seems to be these days :smile: 

Would hate to lose the work... I'm backing my contributions locally, but still.

**Comment by QuincyLarson** [comment]
@Weezlo for now you can leave the code on CodePen. Once we have the multi-file editing on Free Code Camp, you and @no-stack-dub-sack can import these challenges into our seed files and get proper credit for your open source contributions in the Git history 😄 

Since these are on CodePen, if you give me a link, I can routinely fork these, which should reduce the risk associated with not having them in proper version control.

**Comment by no-stack-dub-sack** [comment]
@Weezlo Hey Anis, this code needs to be added to the master pen (on line 143 I believe), to replace the existing function so that tests will run until `AC` button is implemented (same method we are using for pomodoro) - if you think this is the best solution. 

```
 function clearDisplay(){
    //document.getElementById("display").innerHTML = "0";
    if (document.getElementById('clear')) clickButtonsById([_AC]); /* CHANGE *////////////////////////// 
  }
```

**Comment by no-stack-dub-sack** [comment]
@Weezlo - disregard above post - you and I have talked this out on Gitter

**Comment by no-stack-dub-sack** [comment]
This is a reference for campers who will be helping to QA this project:

## User Stories
1. My calculator should contain a clickable element  containing an `=` with a corresponding `id="equals"`.
2. My calculator should contain 10 clickable elements containing one number each from 0-9, with the following corresponding IDs: `id="zero"`,  `id="one"`,  `id="two"`, `id="three"`, `id="four"`, `id="five"`, `id="six"`, `id="seven"`, `id="eight"`, and `id="nine"`.
3. My calculator should contain 4 clickable elements each containing one of the 4 primary mathematical operators with the following corresponding IDs: `id="add"`, `id="subtract"`, `id="multiply"`, `id="divide"`.
4. My calculator should contain A clickable element containing a `.` with a corresponding `id="decimal"`.
5. My calculator should contain a clickable element with an `id="clear"`.
6. My calculator should contain an element to display values with a corresponding `id="display"`.
7. As I input numbers, I should be able to see my input in the element with the id of "display". 
8. In any order, I should be able to add, subtract, multiply and divide a chain of numbers of any length, and when I hit `=`, the correct result should be shown in the element with the id of "display". 
    - **Note On Calculator Logic:** It should be noted that there are two main schools of thought on calculator input logic: immediate execution and formula logic (our example utilizes formula logic and observes order of operation precedence, immediate execution does not). Either is acceptable, but please note that depending on which you choose, your calculator may yield different results than ours for certain equations (see below example). As long as your math can be verified by another production calculator, please do not consider this a bug. 
    - _**EXAMPLE:**_ `3 + 5 x 6 - 2 / 4 =`
         - Immediate Execution Logic: `11.5`
         - Formula/Expression Logic: `32.5`
9. When inputting numbers, my calculator should not allow a number to begin with multiple zeros. 
10.  When the decimal element is clicked, a `.` should append to the currently displayed value. Two `.`s in one number should not be accepted.
11. I should be able to perform any operation (`+`, `-`, `*`, `/`) on numbers containing decimal points.
12. If 2 or more operators are entered consecutively,  the operation performed should be the last operator entered.
13. At any time, pressing the clear button clears the input and output values, and returns the calculator to its initialized state. `0` should be shown in the element with the id of "display".
14. Pressing an operator immediately following `=` should start a new calculation that operates on the result of the previous evaluation.
15. My calculator should have several decimal places of precision when it comes to rounding (note that there is no exact standard, but you should be able to handle calculations like `2 / 7` with reasonable precision to at least 4 decimal places).

**Comment by QuincyLarson** [comment]
This thread is live here: https://forum.freecodecamp.com/t/javascript-calculator-project-with-testable-user-stories-guinea-pigs-needed/58941/1

**Comment by Weezlo** [comment]
@QuincyLarson @no-stack-dub-sack 
The "Run again" button has been implemented in the master generic test script (http://codepen.io/FCC_test_suites/pen/qqmGXr). The blank pen and the example project for the javascript calculator from @no-stack-dub-sack' previous post already include this new master test script, no modification is needed.

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
