### ISSUE TITLE
Minimalist example projects with tests: Markdown Preview

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#60]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [ ] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [ ] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

The current project: https://www.freecodecamp.com/challenges/build-a-markdown-previewer

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson I'm going to start working on this, while continuing to work on user stories for Game of Life (#61). 

The existing example project is already pretty simple - in keeping with our theme of as minimalist as possible, I'm thinking something similar would be appropriate minus the transitions/animations. Let me know if you have any other thoughts on this.

**Comment by QuincyLarson** [comment]
Yes - this sounds good! Most of the complexity involved in this app is in manipulating local storage, and we should keep the presentation as simple as possible.

**Comment by no-stack-dub-sack** [comment]
Sounds good, on it!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson are you in any way opposed to actually showing recipes as well rather than just lists of ingredients? It doesn't have to be required, and won't make things that much more complex since there is already a bunch of local storage manipulation going on anyway. And that way it will truly be a recipe box rather than just an ingredient box 😄

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack that's a good point. Yes - if there were separate ingredient and steps sections, that would be preferable. You're right - currently, this is really just an ingredient box 🙂

**Comment by no-stack-dub-sack** [comment]
Ok, cool. I will add that. 👍

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @bonham000 @Weezlo These are a rough draft, and I think there will be problems testing some of them, but I will get started and see what happens. @bonham000 and I are going to get on a call tomorrow to discuss...

### Intro
You might find this project a little tricky because it involves significant manipulation of your browser’s local storage. For this recipe box app, when a user adds their recipe to the box, not only should it display on the screen, but it should also save to local storage, so that when they return to the app, all of recipes that they have entered are still there. If they edit or delete their recipe, local storage should be updated to reflect this as well. The user stories you must fulfill for all tests to pass are below. Good luck and happy coding!

## User Stories:

1. In my Javascript, I should have a variable that takes the following format: const localStorageKey = “_” + yourUserName + “_recipeBox” (e.g. const lcoalStorageKey = “_freeCodeCamp_recipeBox”). This is important because we need to know what your local storage key is in order to test your application! NOTE: All of your recipes should be set and retrieved from local storage using this key. The value for this key should take the form of an array of JSON objects each with 3 properties: “recipe” (string), “ingredients” (array), and “directions” (array). Each object should look something like this: {'recipe': ‘foo-bar-pie’, 'ingredients' : [‘foo foo berries’, ‘bar bar’], 'directions' : [‘combine bar bar with foo foo berries’, ‘Enjoy!’]}.
2. When a user first visits my recipe box, local storage should automatically be set with at least one default recipe.
3. I should see an element with corresponding id=“index-view” in which the name of each recipe that is stored in local storage is displayed, each in it’s own clickable element with a class of "index-view-item" and an id corresponding to the recipe name (e.g.id=“pasta”).
4. When I click on an element with class=“index-view-item”, I am shown the corresponding recipe in an element with a class of "index-view-item" and an id of "view-" + recipename (e.g. id="view-pasta"). Only one “recipe-view” element should visible at any given time.

### ADD:

1. I can see a clickable element with corresponding id=“add-recipe”.
2. When I click the element with the id of “add-recipe”, I am presented with a form that has the following elements: a clickable element with id=“add-submit”, a clickable element with id=“add-close”, and 3 input fields (<input> or <textarea>) with the following corresponding id’s: “add-recipe-name”, “add-ingredients”, and “add-directions”.
3. When I enter text into at least the first form field and click the element with id=“add-submit”, the name of the recipe I have entered should display in the “index-view” as a clickable element and should be saved to local storage in the format described above.
4. If no text is entered into the first form field (id=“add-recipe-name”), the form should not submit.
5. I should be able to exit the add recipe form by clicking the element with id=“add-close” and no submission should occur.

### EDIT:

1. When a recipe is displayed to a user, I can see a clickable element with a corresponding id of “edit-” + “recipename” (eg. id=“edit-pasta”).
2. When I click the element with the id of “edit-” + “recipename”, I am presented with a form that has the following elements: a clickable element with id=“edit-submit”, a clickable element with id=“edit-close”, and 3 input fields with the following corresponding id’s: “edit-recipe-name”, “edit-ingredients”, and “edit-directions”. When I am presented with this form, the data from the corresponding recipe should be populated into the correct form fields.
3. When I submit edits by clicking the element with id=“edit-submit”, the newly edited recipe should be merged with or replace the corresponding object on the local storage array (editing a recipe should not add a new unique recipe to the array, i.e. the length of the recipe array should increase after an edit is made).
4. I should be able to exit the edit recipe form by clicking the element with id=“edit-close”.

### DELETE:

1. When a recipe is displayed to a user, I can see a clickable element with a corresponding id of “delete-” + “recipename” (eg. id=“delete-pasta”).
2. When I click the element with the id of “delete-” + “recipename”, the object that corresponds with that recipe should be removed from the local storage array and the user should no longer be able to view that recipe (in "index-view" or "recipe-view").

**Comment by QuincyLarson** [comment]
Note that we are abandoning "Recipe Box" as a testable project. Instead, we plan to use Markdown Preview, which will be easier to test.

Recipe Box will live on in its old form under our "extra practice projects" section.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson  http://codepen.io/no_stack_dub_sack/full/ZBwZqW

This seems pretty straight forward - unless we want to require anything additional like the ability to clear the textarea at any time (just to add a little extra challenge), I think we only need these 4 user stories:

## User Stories 

1. I can see a `<textarea>` element with corresponding `id="editor"`.
2. I can see an element with corresponding `id="preview"`.
3. When I enter text into the `#editor` element, the `#preview` element is updated as I type to display the content of the textarea.
4. When I enter GitHub flavored markdown into the `#editor` element, the text is rendered as markdown in the `#preview` element (Hint: You don't need to interpret Markdown yourself - you can import the Marked library for this: https://cdnjs.com/libraries/marked).

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack these stories are solid. As far as the demo project, I would recommend going with higher contrast - using white or gray instead of that dark teal color (which makes black very hard to read). 

This is off to an excellent start!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson no prob, I can make that change. Should be able to have the tests done this evening or tomorrow.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome - You're making rapid progress on these!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo Due to issue with simulating typing in a textarea, I'm proposing the following changes to this project and the user stories. The updated project is [here](http://codepen.io/no_stack_dub_sack/pen/ZBwZqW) (I've also changed the colors for higher contrast).

@Weezlo - if you have any ideas on how to do this, give me a buzz on Gitter. [Here's an SO question](http://stackoverflow.com/questions/17880821/javascript-simulate-key-events-into-textbox-input) that describes the problem pretty well, explains why it doesn't work, and also references other SO solutions to the same problem that I've tried and don't work. On top of these I've tried several more. There could be a different approach altogether that I'm missing though. 

## Proposed User Story Changes

**Note the changes from above on stories 3, 4, & 5.

1. I can see a `<textarea>` element with corresponding `id="editor"`.
2. I can see an element with corresponding `id="preview"`.
3. I can see a clickable element with corresponding `id="convert-markdown"`.
3. When I enter text into the `#editor` element and click the #convert-markdown element, the `#preview` element is updated to display the content of the textarea.
4. When I enter GitHub flavored markdown into the `#editor` element and click the #convert-markdown element, the text is rendered as markdown in the `#preview` element (Hint: You don't need to interpret Markdown yourself - you can import the Marked library for this: https://cdnjs.com/libraries/marked).
5. When my markdown previewer first loads, there is default markdown that explains the purpose of the project contained in the `#editor` field and its contents are rendered as markdown in the preview field.
6. My default markdown should include at least one of each of the following: a header (H1 size), a sub header (H2 size), a link, inline code, a code block, a list item, a blockquote, an image, bolded text, and italic text.
7. When a user clicks a link rendered by my markdown previewer, the link is opened up in a new tab (HINT: read the Marked.js docs for this one!).

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Ok, so I finally figured a way around the issue we were discussing the other night with @BerkeleyTrue of forcing a react state update via the tests without using Enzyme (which I fully admit I did not think was going to happen). We can now sort of simulate a user typing into the textarea by manually changing the textarea's value and then triggering a change event so React hears it and updates the app's state:
```javascript
editor.value = 'new value';
const event = new Event('input', {bubbles: true} );
editor.dispatchEvent(event);
```
That said, I've reverted back to an older version of the user stories and finished the tests. I've created an alternate event object for triggering events on the textarea that work in both jQuery and vanilla JS, however I am not sure about other frameworks - we will have to see when this is QA'd.

I will post everything shortly so that we can get the process started on this one as well.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! I'm thrilled to hear you had a breakthrough. If it works with React and jQuery (which at least Ember uses) then I think you've covered about 95% of users. We can go ahead and do that, then add additional fallbacks as deemed necessary by issues.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson - see note in above post. Let's see how this one does. I QAd it myself a bit and also implemented a jquery version from scratch. Tests seem to work at least with those 2 libs and vanilla JS which I think will be the most usual suspects. Anyway - ready for QA:

sample project w/ tests: http://codepen.io/FCC_test_suites/full/NbVbqo
pen to fork: http://codepen.io/FCC_test_suites/pen/QGMMZO

## User Stories 

1. I can see a `<textarea>` element with corresponding `id="editor"`.
2. I can see an element with corresponding `id="preview"`.
3. When I enter text into the #editor element, the #preview element is updated as I type to display the content of the textarea.
3. When I enter GitHub flavored markdown into the #editor element, the text is rendered as HTML to #preview as I type (Hint: You don\'t need to parse Markdown yourself - you can import the Marked library for this: https://cdnjs.com/libraries/marked).
4. When my markdown previewer first loads, the #editor field should contain valid default markdown that provides a brief description of the project and demonstrates the previewer\'s capabilities.
5. When my markdown previewer first loads, the default text in the #editor field should contain valid markdown that represents at least one of each of the following elements: a header (H1 size), a sub header (H2 size), a link, inline code, a code block, a list item, a blockquote, an image, and bolded text.
6. When my markdown previewer first loads, the default markdown in the #editor field should be rendered as HTML in the #preview element.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome - I've listed this here: https://forum.freecodecamp.com/t/markdown-editor-project-with-testable-user-stories-guinea-pigs-needed/68717/1

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson sweet, we'll see how it goes...

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
