### ISSUE TITLE
Minimalist example projects with tests: Drum Machine

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#61]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [ ] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [ ] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

An unsimplified example of this is: http://codepen.io/mattgreenberg/pen/dObVvw

**Comment by no-stack-dub-sack** [comment]
Working on designing an app for this and am creating user stories as I go - my first go round at this project so might be a bit of a challenge, but my goal is to keep it very simple and with minimal features. If someone else wants to take this on that has more experience, let me know, but for now I will start something and see where it goes...

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack sounds good. I agree - the fewer user stories we have the better for starters. I recommend basically ensuring that the tiles appear and follow the rules of the game, since that's already quite challenging. Then anything campers want to build on top of that is up to them.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Perfect, pretty much exactly what I was thinking. I will let you know when I get somewhere. Pretty close actually, if we're just going for basics, because I found a _relatively_  simple algorithm on which to base my app on (compared to some of the other options I've seen out there during my research).

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Should have first draft of stories posted by this evening, along with example project. If you are good with stories and app, we can talk to @Weezlo about ideas for testing - might be a bit challenging.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo Ok, so I have a very simple implementation of Conway's Game of Life here:
http://codepen.io/no_stack_dub_sack/full/KNdzrP/  

BUT, I think we might need to discuss the merits of testing this project before moving on. In trying to come up with testable user stories, I've been impeded by several major problems:

- First and foremost - programmatically testing that the rules of the game are being followed. To do this, at it’s most basic, we’d have to input at least one cell into our test, count that cell’s neighbors, then follow that cell to the next state to check whether it is alive or dead. For this to happen, I think we would need to know some, if not all, of the following:
  - First, **how the board is represented**: as an array, a multi-dim array, or something else?
  - Second, how cells are represented (on whatever it is they are being represented on): as integers, as strings, as objects (like in the current example, which was something I hadn’t even previously thought of), etc.
  - Third, **how is alive vs. dead is being represented** for each cell: 1s & 0s, Xs and Os, object properties, etc.
  - Fourth, **how cells are being visually represented**, so we can know what the code corresponds to (divs, tables, canvas elements, svg).
  - And fifth, **how alive vs. dead is being visually represented** within the visual representation of each cell: color change (expected but not guaranteed), or some other way. 

My board is represented as a multi-dimensional array of 1s and 0s (to represent alive and dead) with 1500 total indices/cells, but the current project looks to me like a single dimensional array made up of 3500 unique objects each with a status property to represent alive or dead. Knowing that this such a stark difference - can we envision a script that could successfully test both approaches? And this is just scratching the surface, I think. It would also need to handle whatever other approaches campers might manage to throw at us

Not to say that this CAN'T be tested, because where there's a will there's a way, but if we are going to do it effectively, I think it might mean implementing some very stringent guidelines (which is obviously something we have discussed avoiding).

Do either of you guys have any thoughts on this?

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Thanks for the explanation. I agree - this would really force us to dictate how the camper goes about most aspects of designing this. 

Unless @Weezlo has a good idea for how to test this in a relatively non-invasive way, I would say write user stories for everything but testing that the game of life rules are being followed - even if it's only a handful of trivial tests. 

Another camper will undoubtedly come forward to figure out a good way to test these in the future.

**Comment by no-stack-dub-sack** [comment]
> write user stories for everything but testing that the game of life rules are being followed - even if it's only a handful of trivial tests.

@QuincyLarson Sounds manageable, will do.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Working prototype done, but have not yet ported to CodePen - tests should be done within a couple of days and will post all here

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Awesome! Thanks for keeping me posted on this :)

**Comment by no-stack-dub-sack** [comment]
## User Stories

1. I should be able to see an outer container with a corresponding `id="drum-machine"`.
2. Within `#drum-machine` I can see an element with a corresponding `id="display"`.
2. Within `#drum-machine` I can see 9 clickable "drum pad" elements, each with a `class` name of `"drum-pad"`.
3. Within each `.drum-pad` element, I can see a string that corresponds to one of the following keys on the keyboard: `"Q"`, `"W"`, `"E"`, `"A"`, `"S"`, `"D"`, `"Z"`, `"X"`, `"C"`. This will become important later - these are the keys we will use to trigger the sounds on our sampler!
4. Within each `.drum-pad`, there should be an HTML5 `<audio>` element which has a `src` attribute pointing to an audio clip, a `class` name of `"clip"` and an `id` corresponding to the inner text of its parent `.drum-pad` (e.g. `id="Q"`, `id="W"`, `id="E"` etc.).

***will come back and edit this later... need to finish these.

@QuincyLarson - what do you think about requiring 2 different sample sets/kits like in the example pen? I also need to pick out some samples from my library and dropbox them to you or something like that to throw up on S3. Do they need to be 100% known to be open license? If so, not sure if i have anything that I know for a fact is open.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Tentative user stories are above. 

First 6 tests are done and pen is on code pen. Will get a bit more styling soon. 
Also, picked new sounds. The drum samples are from my library which should be fine, and the other clips are open license from youtube's audio library.

Here's the pen with tests so far: http://codepen.io/no_stack_dub_sack/full/woQzNW/ 

@Weezlo - any idea if we will run into trouble testing for sounds shorter than 200ms? I know that was an issue with the pomodoro but can't remember the reason why.

**Comment by Weezlo** [comment]
@no-stack-dub-sack When we test that a sound is actually playing, like in test # 26 of the pomodoro, we test the "paused" property of the audio tag. If the value of this property is "false" then we know the sound is currently playing.
The 200ms in the pomodoro is the time given to the application to trigger the sound after 00:00 is reached. It's just a security. This number could be reduced to a smaller value (e.g. 10ms) but I just realised that I forgot to take into account the loading time of the sound file. if it's a big file or poor internet connection and it takes like 500ms to load, then the test will fail.
I will modify the test so it handles this situation. I think I will create a generic function for this purpose, then we'll be able to use this function in any project (e.g. Drum Machine).

**Comment by no-stack-dub-sack** [comment]
@Weezlo great, thanks. That sounds perfect!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson, @Weezlo Ok, the drum machine is almost ready for QA. This is the finished project with working tests: http://codepen.io/no_stack_dub_sack/pen/woQzNW

Tests are integrated into the master test script pen (and I made some slight changes to the "on demand" button so that the tests don't run automatically when the page loads).

I'm still going to do a tiny bit of work to the SCSS at some point, but as soon as I update the user stories we can push this out to QA. I will post the final user stories here tomorrow. 

This is going to be one of the easier projects probably - and it def keeps with the minimalist theme, the tests just cover the basics and let the campers take the creativity anywhere from there. 

I specifically wrote the tests so that if they want to include extras, like more drum pads, etc. the tests wont fail.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! That is great. I played with it for a solid 10 minutes. Even the tests are a blast to run. 💯 

I can already tell that this will be an extremely popular challenge.

**Comment by Weezlo** [comment]
@no-stack-dub-sack just a few remarks about the tests.
- Test # 3: If we let people put more than 9 drum pads, then the order should not matter. For example, if you insert a new pad at the first position of the existing array (just before 'Q') in the example project, depsite the presence of all the required 9 pads in the array, the test will fail.
- Tests # 4, 5, 6: We should not use `firstChild` to get a specific HTML element. The existing tests currently work because React automatically removes the space between the elements during transpilation (carriage returns, line feeds, spaces, etc). But if someone writes it differently, the tests will fail with an error that will be difficult to debug. A `querySelectorAll` should be used instead. (cf. http://www.w3schools.com/jsref/prop_node_firstchild.asp)
- Tests # 5, 6: For clarity and maintanability, the following lines:
```javascript
if (!document.getElementById(pad.firstChild.id).paused) {
   assert.strictEqual(1, 1);
} else {
   assert.strictEqual(false, true, 'No audio plays when the .... ');
}
```
should be simplified with:
```javascript
assert.isOk(!document.getElementById(pad.firstChild.id).paused, 'No audio plays when the .... ');
```
- Tests # 6, 7: I'm not sure why we use timeouts in these tests. I think removing them would make the test suite run even faster. 
- For all the tests: the Mocha documentation discourages the use of arrow functions inside of suites and tests declarations ("this" context issues). For consistency, and maintanability, arrow functions should not be used (cf. https://mochajs.org/#arrow-functions).

**Comment by no-stack-dub-sack** [comment]
@Weezlo Awesome, thanks for the review! I will make these changes today before we open this up QA. 

As to the `=>` syntax, I realized this half way through when I got the challenges I was using `Promise`s and `this.timeout`s on, which led to binding issues. I meant to go back through and change them all. I will do this for another recent suite I wrote as well.  

Thanks again! I'll be online early this evening if you will be around again. Appreciate the guidance as always.

**Comment by no-stack-dub-sack** [comment]
@Weezlo Ok - fixed all the issues you pointed out, however - I left the timeouts for now, I think it better illustrates the tests running than if they all happen practically simultaneously. I think it makes for a better UX overall, but if you both disagree and prefer just to have it move as quickly as possible, we can always remove them.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Ok, I'd say this is ready for QA. Example project, pen to fork, and user stories below:

*Note: working on fixing some x-browser issues in the example project, but working well in chrome, and since that's where the tests have to be run, I don't think this should hold us up.

Example: http://codepen.io/no_stack_dub_sack/full/woQzNW/
Pen to Fork: http://codepen.io/FCC_test_suites/pen/QGMMZO

## User Stories

1. I should be able to see an outer container with a corresponding `id="drum-machine"` that contains all other elements.
2. Within `#drum-machine` I can see an element with a corresponding `id="display"`.
2. Within `#drum-machine` I can see 9 clickable "drum pad" elements, each with a `class` name of `"drum-pad"`, a unique `id` that describes the audio clip the drum pad will be set up to trigger, and an inner text that corresponds to one of the following keys on the keyboard: Q, `W, E, A, S. D, Z, X, C.
4. Within each `.drum-pad`, there should be an HTML5 `<audio>` element which has a `src` attribute pointing to an audio clip, a `class` name of `"clip"` and an `id` corresponding to the inner text of its parent `.drum-pad` (e.g. `id="Q"`, `id="W"`, `id="E"` etc.).
5. When I click on a `.drum-pad` element, the audio clip contained in its child `<audio>` element should be triggered.
6. When I press the trigger key associated with each `.drum-pad`,  the audio clip contained in its child `<audio>` element should be triggered (e.g. pressing the Q key should trigger the drum pad which contains the string "Q", pressing the W key should trigger the drum pad which contains the string "W", etc.).
8. When a `.drum-pad` is triggered, a string describing the associated <audio> element is displayed as the inner text of the `.display` element (each string must be unique).

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! I've published this on our forum here: https://forum.freecodecamp.com/t/drum-kit-with-testable-user-stories-guinea-pigs-needed/66354

**Comment by no-stack-dub-sack** [comment]
@Weezlo @QuincyLarson - So I've been toying with getting all of the tests and dependencies bundles together so we only need one dependency each in the "fork pen" for JS and CSS. Not the most elegant of solutions, but basically I just pasted the minified source code for all the JS dependencies above the test suite code and created a rawgit CDN out of it. I just tried it for the drum machine and its working well, so I don't see this being an issue going forward. All we will need in the "fork pen" for dependencies is to have Babel enables, the rawgit CDN that we will eventually create when all the tests are done, and the mocha CSS cdn. 

You can see this is action here: http://codepen.io/no_stack_dub_sack/pen/woQzNW

The only issue will be that if we have to edit the tests or work out bugs, we will have to create a new CDN - as far as I can tell, once you create a CDN with rawgit, even if you update your git project file, the CDNs code wont change. Now that I think about it, this could be problematic, if we make updates and people already have the previous CDN built into their projects, they wont get the updates.

Thoughts?

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome work! I agree that this is how we should do these testable projects from here on out. 

This will make it much easier for campers to use platforms other than CodePen (or develop locally) if they so desire :)

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson it will take virtually no time at all. We could start doing it this way as soon as we solve the issue of the CDN being updated every time we push a change to the repo. We'll just have to create a new repo on FCC somewhere to host the test file when we are ready.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Also, as a last resort, if we can't find an easy, cost-effective way to go the CDN route that will allow the changes we push to be reflected without changing URLs - we really don't have to deploy the tests via a CDN at all. We can achieve the same effect by just bundling all the code in a single pen. It will work in the same exact way and boil things down to just one external JS dependency - it's just not as elegant, professional or safe (in terms of version control).

**Comment by augmt** [comment]
@no-stack-dub-sack How about [GitCDN](https://gitcdn.link/)? Its focus (contrasting with RawGit) is "[on providing the latest commit of a given GitHub file](https://github.com/schme16/gitcdn.xyz#how-is-this-different-from-rawgitcom-and-githackcom)."

**Comment by no-stack-dub-sack** [comment]
@augmt Dude, thank you! Exactly what I've been looking for! That will do the trick 👍 👍 👍 

@QuincyLarson Looks like @augmt has found our solution! ☝️ ☝️

**Comment by QuincyLarson** [comment]
@augmt wow - that's awesome! I can't believe I'd never heard of this. This will be a huge help with a wide variety of projects we're working on.

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
