### ISSUE TITLE
Minimalist example projects with tests: Bar Chart

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#62]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [ ] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [ ] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

The current project: https://www.freecodecamp.com/challenges/visualize-data-with-a-bar-chart

**Comment by evaristoc** [comment]
@QuincyLarson with some additional polishing, can this be the minimalistic project you are looking for? Data based on Stackoverflow Survey and remote work.
http://codepen.io/ecccs/pen/rLbJyG

The example that you used for the article about remote work was the following:
https://gitter.im/FreeCodeCamp/DataScience?at=57b65bb8219328ee32a7557b

My proposal is a scaling of the data using percentages instead of absolute values to highlight the differences according to salary (x axis).

**Comment by QuincyLarson** [comment]
@evaristoc yes - this sounds good. 

@Weezlo @no-stack-dub-sack do either of you have any idea how we might go about testing something like this?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson hmmm... not sure, I will let @Weezlo answer this one. I can do a bit of research too though.

**Comment by Christian-Paul** [comment]
@QuincyLarson @no-stack-dub-sack @paycoguy I have some ideas for user stories and how to test them: let me know what you all think!

# User Stories

1. My chart should have a title with a corresponding id="chart-title"
   * Check that an element with that id exists

2. My chart should have an x axis with a corresponding id="x-axis"
   * Check for a "g" element with id="x-axis"
   * Element should contain children with class='tick

3. My chart should have a y-axis with a corresponding id="y-axis"
   * Same as above

4. My chart should have bars with corresponding class="bar" displaying the data
   * Check for "rect" elements with class="bar"

5. My chart's bars should accurately represent the sample data
   * Measure ratios of bar heights at random indexes to test against ratios of data at the same indexes
   * (For example: if bar at index 0 has a height of 23, and bar at index 3 has a height of 5, the data at indexes 0 and 3 should also have a ratio of 23:5 

6. I can mouse over a bar and see tooltips with corresponding class="tooltip" which displays more information about the data
   * Programmatically mouse over each bar and see if the opacity value of any tooltip changes

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul These sound great and I think most of them should work... maybe the last one could be a little tricky though since there are probably other ways to show and hide tooltips other than with opacity? Unless that is a D3 specific thing and that's how it always works in D3 - which in that case - perfect!

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack Thanks! Good catch! users can do it in numerous ways; I'll check for a change in other ways as well. Opacity, display, visibility, z-index, color/background-color (if they use rgba)

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul that sounds good! And then just maybr offer specific error messages for each approach or something. You probably were already planning on this, but just in case - I would also first test for the presence of the class so they get a less specific error message first that tells them they are missing the class before getting to the how of the implementation. We could also could t the tooltips to be sure there's one for every .bar.

Also, will there be a certain number of bars dictated by the data? If so, maybe we can confirm they have the right number. Or in lieu of that, make sure they have a certain minnimum so they cant cheat the tests by having just a single bar. Sorry if these are silly questions/suggestions - they may be irrelevant, not sure since I dont know D3 well enough yet.

**Comment by no-stack-dub-sack** [comment]
Can't seem to edit my post on mobile... that's supposed to say "we could also count the tooltips..."

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack Gotcha, I'll make specific test cases. Your suggestions are helpful! I'll check for the number of bars and tooltips under the 5th user story, or perhaps I'll break that up into smaller stories. 

The proposed update to the project (http://codepen.io/ecccs/pen/rLbJyG) doesn't meet the user stories that I've proposed (only three tooltips, they aren't made visible by mouseover). Is this the project we're going forward with as an example? Should I make the necessary changes to it?

**Comment by QuincyLarson** [comment]
@Christian-Paul @paycoguy For these data visualization projects, I recommend you build completely new minimalist example projects that meet your user stories. You can use the original data sets if you want, or find simpler ones.

The simpler and less intimidating these look (and the fewer libraries they use) the better. One thing we've learned is that polished projects tend to intimidate campers, who will react that "wow - there's no way I could build something like that"

So all of our new example projects are pretty bare-bones.

**Comment by Christian-Paul** [comment]
I've added some more user stories and implemented the tests for them.

Here is the pen with my tests: 
http://codepen.io/Christian-Paul/pen/gLZVXZ

And the sample project: 
http://codepen.io/Christian-Paul/pen/NbZzJV

The reason test 10 takes so long is because I'm accommodating for any transition time the users' tooltips need to go back to being hidden when the mouse leaves the bar.

I'd love some feedback @no-stack-dub-sack @QuincyLarson 

# User Stories

1. My Chart should have a title with a corresponding id="title"
2. My Chart should have an x-axis with a corresponding id="x-axis"
3. My Chart should have a y-axis with a corresponding id="y-axis"
4. Both axes should contain multiple tick labels
5. My Chart should have a bar for each data point with a corresponding class="bar" displaying the data
6. Each bar should have the properties "data-date" and "data-gdp" containing date and gdp values
7. The "data-date" properties should match the order of the provided data
8. The "data-gdp" properties should match the order of the provided data
9. Each bar's height should accurately represent the data's corresponding GDP
10. I can mouse over a bar and see a tooltip with corresponding id="tooltip" which displays more information about the data
11. My tooltip should have a \"data-date\" property that corresponds to the given date of the active bar

**Comment by QuincyLarson** [comment]
@Christian-Paul Excellent work! First of all, this looks beautiful. The tests run plenty fast! @no-stack-dub-sack what do you think? Any feedback before we open this one up to campers to solve?

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul, @paycoguy Actually - your test for story 10 looks like the perfect solution for the same user story for the scatter plot which I just referenced on #63. Can we implement this solution for that project as well?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson  - as far as feedback - the user stories look great! I'm going to take a quick glance at the tests and then I think we can open it up.

@QuincyLarson @paycoguy @Christian-Paul @Weezlo When it's ready I'm going to integrate this into the new tests-bundle which I will have to explain to everyone at some point. This is a major breakthrough, thanks in part to @bonham000, which will allow us SIGNIFICANTLY improved maintainability for this code base, and eliminates all dependencies except for one CDN. The codebase for this is now a git repo which we will eventually fork over to FCC. For now, the test bundle is being served via rawgit - but we will update this to gitCDN before releasing to "production" so that our latest commits will always be reflected by the CDN URL without worrying about throttled traffic.

If anyone wants to take a first glance, the repo is below, however it's not quite ready for PRs because become of some of the eccentricities involved, it will need a thorough contributing.md file. The readme.md will eventually contain credits for everyone that worked on this too.

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul one other thing to consider is if no code was populated, would any of the tests pass? They should all be failing to start. 6, 7, and 8 were all passing with no code, so i added an assert to each to check for the existence of bar elements before doing anything else. This has them all failing from the start. I also added `display = "none"` to the ORs for the tooltip test, just in case.

**Comment by no-stack-dub-sack** [comment]
1. My chart should have a title with a corresponding `id="title"`.
2. My Chart should have an x-axis with a corresponding `id="x-axis"`.
3. My Chart should have a y-axis with a corresponding `id="y-axis"`.
4. Both axes should contain multiple tick labels.
5. My Chart should have a bar for each data point with a corresponding `class="bar"` displaying the data.
6. Each bar should have the properties `data-date` and `data-gdp` containing date and GDP values.
7. The `data-date` properties should match the order of the provided data.
8. The `data-gdp` properties should match the order of the provided data.
9. Each bar\'s height should accurately represent the data\'s corresponding GDP.
10. I can mouse over a bar and see a tooltip with corresponding `id="tooltip"` which displays more information about the data.
11. My tooltip should have a `data-date` property that corresponds to the given date of the active bar.

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack @QuincyLarson Awesome! Thanks guys!

@no-stack-dub-sack I updated the bar chart to use D3 v4: the changes were only in syntax, everything renders the same way, so the tests should be fine regardless of version. Here's the updated project if you're interested:
http://codepen.io/Christian-Paul/pen/ZBgrvd

Also, I've encountered a weird bug while testing out your example project link:
http://codepen.io/FCC_test_suites/full/LbwNxZ

Sometimes, after refreshing and then clicking run tests, test 10 fails with:
`Error: Tooltip should be visible when mouse is on a bar 
    at https://gitcdn.link/cdn/no-stack-dub-sack/testable-projects-fcc/9ae2d501da456bdf0ddded867ce76c8783d22f92/build/bundle.js:20616:21`

This only happens about once or twice in ten runs, but it never happens in my development version:
http://codepen.io/Christian-Paul/full/NbZzJV/

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul - hmm - its def an odd bug, but I'm not going to stress too much over it. When a test fails, I think the natural inclination is to run it again, especially if someone believes their code is right and/or the test passed previously. I just ran it about 12 times and it only happened once. 

My guess is that it's somehow an effect of the bundling that we're now doing, but really that is our best option to have this as an organized, maintainable codebase - so if this is the one side effect, I suppose I can live with it (even though I don't like it)

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack Great! I had a feeling that the 10ms may have been the cause of it, but wasn't sure why bundling it would make it fail all of a sudden. Anyway, I'm glad it's working properly now 😄

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul Yeah, it's possible code-pen's internal engine somehow changes things a bit. We'll never know, but seems to be working well now. I've often found weird quirks when going from codepen to a proper dev environment or vice versa...

**Comment by QuincyLarson** [comment]
We now have a QA thread live here: https://forum.freecodecamp.com/t/bar-chart-project-with-testable-user-stories-guinea-pigs-needed/71909

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
