### ISSUE TITLE
Minimalist example projects with tests: Scatterplot

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#63]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [ ] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [ ] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

The current project: https://www.freecodecamp.com/challenges/visualize-data-with-a-scatterplot-graph

**Comment by paycoguy** [comment]
@QuincyLarson @no-stack-dub-sack @Christian-Paul 

I've been working on this and I have most of these user stories complete.  I'm still unsure about my solution to validate the data.

Here is a link to the sample project:
http://codepen.io/paycoguy/pen/ObdByK
Here is the link to the test script:
http://codepen.io/paycoguy/pen/VmgEYE?editors=0010

Here are the user stories and my notes:

1. I can see a title that has id="title" **(complete)**
2. I can see an x-axis that has id="x-axis" **(complete)**
3. I can see a y-axis that has id="y-axis" **(complete)**
4. I can see dots that have class="dot" that represent the data being plotted **(complete)**
5. Each dot will have the properties "data-xvalue" and "data-yvalue" containing their corresponding x and y values **(complete)**

This was my solution on trying to validate the plotted dots.  I'm requiring the user to put the actual data in each dot, so that when I get the collection of dots, I can validate the actual data with the dot locations.  I do the validation in story 6 and 9.

6. The data-xvalue and data-yvalue of each dot should be within the range of the actual data **(complete)**

7. The data-xvalue of each dot should line up with the x location of the dot in the graph **(complete)**

Does this story make sense to you?

8. The data-yvalue of each dot should line up with the y location of the dot in the graph **(complete)**

Does this story make sense to you?

9. I can see the range of the x-axis labels are within the range of the actual x-axis data **(complete)**
10. I can see the range of the y-axis labels are within the range of the actual y-axis data 

Currently having issues with this one because this axis has a user readable time that might be hard to convert back to Date object.  I might use a different data set, or require the user to put the actual values in the label properties.

11. I can see a legend that has id="legend" **(complete)**
12. I can mouse over a dot and see a tooltip with corresponding id="tooltip" which displays more information about the data

Currently working on this.

I would love to get your opinion on this.  I want to make sure I'm on the right track on what you all were thinking about on how to implement this.

**Comment by no-stack-dub-sack** [comment]
@paycoguy I think this is shaping up pretty nicely...

To your notes/questions:

> The data-xvalue of each dot should line up with the x location of the dot in the graph (complete)
> Does this story make sense to you?

For these two - what I think you are trying to say is that the scatter plot point should line up correctly with the value in the x or y axis? Is this right? If so, I think maybe a way to state it a bit more clearly could be to say something like:

- The data-xvalue and its corresponding dot should vertically align with the corresponding point/value on the X-Axis.

and similarly:

- The data-yvalue and its correpsonding dot should horizontally align with the corresponding point/value on the Y-Axis.

Am I on the right track?

**Comment by QuincyLarson** [comment]
@paycoguy excellent work so far. This seems like a good way of going about testing the scatterplot. 

9/12 stories passed for me. Once you're ready, we can put this on the forum and get some campers building it, and that feedback should help us understand how intuitive these tests are.

Keep up the awesome work on this!

**Comment by paycoguy** [comment]
@QuincyLarson @no-stack-dub-sack @Christian-Paul 

Here are the updated user stories.  These are all complete.  Let me know if you have any questions!

1. I can see a title that has id="title"
2. I can see an x-axis that has id="x-axis"
3. I can see a y-axis that has id="y-axis"
4. I can see dots that have class="dot" that represent the data being plotted
5. Each dot will have the properties "data-xvalue" and "data-yvalue" containing their corresponding x and y values
6. The data-xvalue and data-yvalue of each dot should be within the range of the actual data
7. The data-xvalue and its corresponding dot should align with the corresponding point/value on the x-axis.
8. The data-yvalue and its corresponding dot should align with the corresponding point/value on the y-axis
9. I can see multiple tick labels on the y-axis with "%M:%S" time format
10. I can see multiple tick labels on the x-axis that show the year
11. I can see the range of the x-axis labels are within the range of the actual x-axis data
12. I can see the range of the y-axis labels are within the range of the actual y-axis data
13. I can see a legend that has id="legend"
14. I can mouse over a dot and see a tooltip with corresponding id="tooltip" which displays more information about the data

**Comment by no-stack-dub-sack** [comment]
@paycoguy - looks awesome! Test 6 is failing on my end though. Also, per your question on Gitter - these tests are designed specifically to work with the FCC provided data set, correct? So when we push it to QA, we will still provide the link to that data set and an instruction letting them know they need to use it. Once that test is fixed, I will integrate and we can post on the Forum

**Comment by paycoguy** [comment]
@no-stack-dub-sack All of my tests pass on Chrome 55.0.2883.95 (64-bit) It looks like 4 of my tests fail on my Firefox browser.  What browser were you using to test?  What browsers and versions should we be using for these tests?

@Christian-Paul and I agree that these tests should a specific FCC provided data set

**Comment by paycoguy** [comment]
If you would like to make these tests data independent, it may be possible.  It may be possible to write tests to check if the project they created "looks" like a scatterplot graph or a bar chart....

Some considerations if we go this route:

1. Different data types (dates, numbers, month names,...) 
2. Allow ascending and descending order for x-axis and y-axis values
3. Pretty formatting for x-axis and y-axis labels might be hard to test.  For example, if the x-axis contains dates, but they are formatted in (mm:ss), it may be hard to convert it to the original date object.

I have more thoughts on this in case you want to delve deeper into this

**Comment by no-stack-dub-sack** [comment]
@paycoguy @Christian-Paul I think we should stick with FCC provided data sets. It will get too complicated and unpredictable going the other route I think.

@paycoguy - what's really interesting is I'm using the same exact version of chrome (Version 55.0.2883.95 64-bit), yet test 6 is still failing for me with the following: 
```
AssertionError: The data-yvalue of a dot is below the range of the actual data: expected Mon, 01 Jan 1900 05:36:50 GMT to be at least Mon Jan 01 1900 03:36:00 GMT-0500 (EST)
```

I'm on OSX 10.11.6 - how about you for OS? This is bringing to light a pretty interesting problem - the tests and results should be as browser independent as possible (considering that the test suites only works in Chrome and FIrefox, for now anyway). But they should at least be able to be consistent across all versions of both of those browsers. Any idea what the issue might be? 

We are charting unexplored territory with these so not surprised we're running into issues...

**Comment by QuincyLarson** [comment]
@paycoguy @no-stack-dub-sack I agree that we should stick to the FCC datasets for now. Later, someone can refactor the tests to allow for other Scatterplot data to work.

**Comment by paycoguy** [comment]
@no-stack-dub-sack 

The failed test issue had to do with dates and our different time zones.  I have fixed it and @Christian-Paul tested it and all the tests pass.  

I also fixed the issue with the tests failing in Firefox.  Apparently, the dataset property doesn't work for SVG elements in Firefox.

**Comment by no-stack-dub-sack** [comment]
@paycoguy Ok, looks great - all tests passing for me now - good catch on the timezone issue! I will fork, integrate, etc., and let Quincy know we are good to go on this one. Nicely done!

**Comment by no-stack-dub-sack** [comment]
### prepping for QA
1. I can see a title element that has a corresponding `id="title"`.
2. I can see an x-axis that has a corresponding `id="x-axis"`.
3. I can see a y-axis that has a corresponding `id="y-axis"`.
4. I can see dots, that each have a `class` of `"dot"`, which represent the data being plotted.
5. Each dot should have the properties `data-xvalue` and `data-yvalue` containing their corresponding x and y values.
6. The `data-xvalue` and `data-yvalue` of each dot should be within the range of the actual data.
7. The `data-xvalue` and its corresponding dot should align with the corresponding point/value on the x-axis.
8. The `data-yvalue` and its corresponding dot should align with the corresponding point/value on the y-axis.
9. I can see multiple tick labels on the y-axis with "%M:%S" time format.
10. I can see multiple tick labels on the x-axis that show the year.
11. I can see that the range of the x-axis labels are within the range of the actual x-axis data.
12. I can see that the range of the y-axis labels are within the range of the actual y-axis data.
13. I can see a legend that has a corresponding `id="legend"`.
14. I can mouse over any dot and see a tooltip with corresponding `id="tooltip"` which displays more information about the data.

**Comment by no-stack-dub-sack** [comment]
@paycoguy @Christian-Paul -ok, so was just getting ready to integrate this... and my only issue at present is the last test... what if a camper makes the tooltips visible/invisible with something other than opacity? Can we think of a way around this? I think this test needs to be a bit more flexible - unless we say specifically in the user story they must use opacity. But I'd like to avoid that and only use it as a last resort... thoughts?

**Comment by paycoguy** [comment]
Let's hold off on integrating this.  I'll add the code from the heat map
project first.

**Comment by no-stack-dub-sack** [comment]
@paycoguy - it looks like there's a great solution for this on the bar chart too. Not sure if that's the same one used in the heatmap. Thanks, give me the greenlight when you are good to go!

**Comment by no-stack-dub-sack** [comment]
Also, that `00` in test 12 - that won't compile outside of codepen, just a single `0` will have the same effect

**Comment by paycoguy** [comment]
@no-stack-dub-sack This is good to go now.  I used the code from the heat map and updated test 12.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @paycoguy @Christian-Paul Hey guys - I hate to say it, but we may have an issue... does anyone know how significant the differences are between the latest version of D3 and those that these projects were built on? 

Because neither project works (bar chart, scatter plot) when you swap out the D3 CDN for the latest version that's found in CodePen's "quick-add" drop-down. So this could be a major problem - if the example projects don't work with the latest version of D3, will any project that's developed with versions other than these be able to pass the tests? Of course, our assumption should be, if campers are starting fresh, they will be using that latest version found in codepen.

**Comment by paycoguy** [comment]
We will work on updating our projects to use the latest version of D3.  I
haven't used the latest version (V4), so I don't really know what the
differences are.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @paycoguy Let's give it a whirl! Ready for QA, running off of new test bundle.

pen to fork: http://codepen.io/FCC_test_suites/pen/JbgXab?
example project: http://codepen.io/FCC_test_suites/full/xRvEKa/

## User Stories

1. I can see a title element that has a corresponding `id="title"`.
2. I can see an x-axis that has a corresponding `id="x-axis"`.
3. I can see a y-axis that has a corresponding `id="y-axis"`.
4. I can see dots, that each have a `class` of `"dot"`, which represent the data being plotted.
5. Each dot should have the properties `data-xvalue` and `data-yvalue` containing their corresponding x and y values.
6. The `data-xvalue` and `data-yvalue` of each dot should be within the range of the actual data.
7. The `data-xvalue` and its corresponding dot should align with the corresponding point/value on the x-axis.
8. The `data-yvalue` and its corresponding dot should align with the corresponding point/value on the y-axis.
9. I can see multiple tick labels on the y-axis with "%M:%S" time format.
10. I can see multiple tick labels on the x-axis that show the year.
11. I can see that the range of the x-axis labels are within the range of the actual x-axis data.
12. I can see that the range of the y-axis labels are within the range of the actual y-axis data.
13. I can see a legend that has a corresponding `id="legend"`.
14. I can mouse over any dot and see a tooltip with corresponding `id="tooltip"` which displays more information about the data.
15. My tooltip should have a `data-year` property that corresponds to the given year of the active dot.

**Comment by QuincyLarson** [comment]
We now have a QA thread live here: https://forum.freecodecamp.com/t/scatterplot-project-with-testable-user-stories-guinea-pigs-needed/71907

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
