### ISSUE TITLE
Minimalist example projects with tests: Heat Map

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#64]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [ ] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [ ] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

The current project: https://www.freecodecamp.com/challenges/visualize-data-with-a-heat-map

**Comment by paycoguy** [comment]
Here are some possible user stories for this project.  This was adapted from the scatterplot project.

1. I can see a title that has id="title"
1. I can see a description that has id="description"
2. I can see an x-axis that has id="x-axis"
3. I can see a y-axis that has id="y-axis"
4. I can see cells that have class="cell" that represent the data being mapped
5. I can see different colors used for the cells
6. Each cell will have the properties "data-month", "data-year", "data-temp" containing their corresponding month, year, and temperature values
7. The "data-month", "data-year", "data-temp" of each cell should be within the range of the actual data
8. I can see the cells aligning with the corresponding month on the y-axis.
9. I can see the cells aligning with the corresponding year on the x-axis.
10. I can see multiple tick labels on the y-axis with the full month name (January, February,...)
11. I can see multiple tick labels on the x-axis that show the year
12. I can see the range of the x-axis labels are within the range of the actual x-axis data
13. I can see the range of the y-axis labels are within the range of the actual y-axis data
14. I can see a legend that has id="legend"
15. I can mouse over a cell and see a tooltip with corresponding id="tooltip" which displays more information about the cell

**Comment by paycoguy** [comment]
@Christian-Paul and I have been pairing on this project for the past week and we think this is ready.

Here is the sample project:
http://codepen.io/paycoguy/pen/VmNQJg
Here is the test code:
http://codepen.io/paycoguy/pen/ObGQKP

Here is the list of the user stories:
1. My heat map should have a title with a corresponding id="title"
2. My heat map should have a description with a corresponding id="description"
3. My heat map should have an x-axis with a corresponding id="x-axis"
4. My heat map should have a y-axis with a corresponding id="y-axis"
5. My heat map should have cells with a corresponding class="cell" that represent the data
6. There should be at least 4 different fill colors used for the cells
7. Each cell will have the properties "data-month", "data-year", "data-temp" containing their corresponding month, year, and temperature values
8. The "data-month", "data-year" of each cell should be within the range of the data
9. My heat map should have cells that align with the corresponding month on the y-axis
10. My heat map should have cells that align with the corresponding year on the x-axis
11. My heat map should have multiple tick labels on the y-axis with the full month name
12. My heat map should have multiple tick labels on the x-axis with the years between 1754 and 2015
15. My heat map should have a legend with corresponding id="legend"
16. I can mouse over a cell and see a tooltip with a corresponding id="tooltip" which displays more information about the cell
17. My tooltip should have a "data-year" property that corresponds to the given year of the active cell

Here are some notes about this project

- Removed all use of jquery except for test 14 where we check if the tooltip is visible
- In order to make all tests fail on a blank project, test 8 has the same exact code as test 6 and 7.  We were wondering if there's a good way to refactor this without a lot of duplicate code.  Is there a way to only run test 8 if test 6 and 7 pass?  Should we be putting this code in a common utility test function?
- Test 16 will be common across the current d3 projects.  How can we write these tests so that this tooltip test can be shared across test suites?

**Comment by QuincyLarson** [comment]
I've created a forum discussion for this here: https://forum.freecodecamp.com/t/heat-map-data-visualization-project-with-testable-user-stories-guinea-pigs-needed/73241
