### ISSUE TITLE
Testable User Stories: Technical Documentation Page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#69]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to create user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

Here's the newly designed version of this project: http://codepen.io/ChaituVR/full/pbprjE/

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Working on this... Only question is @Chaitanya's project uses a lot of HTML5 tags, since I haven't gotten a solid look at the new curriculum, I'm not sure if this is something that is being taught and that we want to require with the tests since it can easily be done without tags like `<article>`, `<section>`, `<nav>`, etc. I think using these is great and enforces best practices, but since this project is early on and there are plenty of ways around it... Let me know what you think.

**Comment by no-stack-dub-sack** [comment]
## Preliminary User Stories:
In regards to my post above, these user stories DO require campers to use HTML5 tags. This can only be a good thing since this is what they should be learning/doing anyway. 

I've also included 3 user stories for layout which would test responsiveness to some degree. This might be a little tricky so I need to look into it a bit. I'm assuming we'd like to test for responsiveness on some level since the new curriculum section is called "Responsive Web Design" but let me know if you think this is overkill.

### Content
1. I can see an `<article>` element with a corresponding `id="main-doc"`, which contains the page's main content (technical documentation).
2. Within the "main-doc" `<article>` element, there should be at least 5 `<section>` elements, each with the following corresponding `id`s: `id="section-one"`, `id="section-two"`, `id="section-three"`, `id="section-four"`, and `id="section-five"`.
3. The first element within each `<section>` should be a `<header>` element which contains text that describes the topic of that section.
4. Each `<section>` should contain at least one `<p>` element with textual content.
5. My page should contain at least one list (`<ul>` or `<ol>`).
6. My page should contain at least 3 `<code>` elements.
4. I can see a `<nav>` element with a corresponding `id="navbar"`.
5. The first element within the navbar should be a `<header>` which contains text that describes the topic of the technical documentation. 
6. Additionally, the navbar should contain at least 5 elements with the following corresponding `id`s: `id="nav-one"`, `id="nav-two"`, `id="nav-three"`, `id="nav-four"`, and `id="nav-five"`.
7. Each navbar element (except for your `<header>`) should contain text that corresponds with the `<header>` text within each `<section>` (e.g. if you have an "Introduction" section/header, your sidebar should have an element which contains the text "Introduction"). 
7. When I click on a navbar element, the page should navigate to the corresponding section of the "main-doc" element (e.g. when I click on the element with the `id` of `"nav-three"`, the element with the `id` of `"section-three"` is displayed).

**Note:** Unless the material you are using is original, please credit the source somewhere on your page and provide a link to the original documentation.  

### Layout
1. On regular sized devices (laptops, desktops), the element with `id="navbar"` should be shown on the left side of the screen and should always be visible to the user.
2. On tablets, phones and other medium/small devices, the navbar should responsively reposition to the top of the screen.
3. When the navbar is on the top of the screen, it should have a height that is equivalent to no more than ~ `275px`. Each element within the navbar should still be accessible.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo Testable Technical Docs Page is here: http://codepen.io/no_stack_dub_sack/pen/woqEdW

3 more tests to go on this one... getting there!

**Comment by no-stack-dub-sack** [comment]
### Content
1. I can see an `<article>` element with a corresponding `id="main-doc"`, which contains the page's main content (technical documentation).
2. Within the `#main-doc` `<article>` element, I can see several `<section>` elements, each with a `class` of `"main-section"`. There should be a minimum of 5.
3. The first element within each `.main-section` should be a `<header>` element which contains text that describes the topic of that section.
4.  Each `<section>` element with the `class` of `"main-section"` should also have an `id` that corresponds with the text of each `<header>` contained within it. Any spaces should be replaced with underscores (e.g. The `<section>` that contains the header "Javascript and Java" should have a corresponding `id="Javascript_and_Java"`).
5. The `.main-section` elements should contain at least 10 `<p>` elements total (not each).
6.  The `.main-section` elements should contain at least 5 `<code>` elements total (not each).
7. The `.main-section` elements should contain at least 5 `<li>` items total (not each).
4. I can see a `<nav>` element with a corresponding `id="navbar"`.
5. The first element within the navbar should be a `<header>` which contains text that describes the topic of the technical documentation. 
6. Additionally, the navbar should contain link, `<a>`, elements with the `class` of `"nav-link"`. There should be one for every element with the `class` `"main-section"`.
7. Each element with the `class` of `"nav-link"` should contain text that corresponds to the `<header>` text within each `<section>` (e.g. if you have a `"Hello world"` section/header, your navbar should have an element which contains the text `"Hello world"`).
7. When I click on a navbar element, the page should navigate to the corresponding section of the `#main-doc` element (e.g. If I click on a `.nav-link` element that contains the text `"Hello world"`, the page navigates to a `<section>` element that has that `id` and contains the corresponding `<header>`.

**Note:** Unless the material you are using is original, please credit the source somewhere on your page and provide a link to the original documentation.  

### Layout
1. On regular sized devices (laptops, desktops), the element with `id="navbar"` should be shown on the left side of the screen and should always be visible to the user.
2. My Technical Documentation page should use at least one media query.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack OK - I've created the forum thread here: https://forum.freecodecamp.com/t/technical-documentation-page-project-with-testable-user-stories-guinea-pigs-needed/69494

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
