### ISSUE TITLE
Testable User Stories: Survey Form

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#70]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to create user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

Here's the newly designed version of this project: http://codepen.io/SamAI-Software/full/KroJvX/

**Comment by IsaacAbrahamson** [comment]
1.  I can view the page on any device.
2. At least one field should be required.
3. I can see if a field is responsive or not if it has a `*`
4. I can enter my name in a textbox.
5. I can select an option from a dropdown.
6. I can select a field from a series of radio-buttons.
7. I can select several fields from a series of check-boxes.
8. I am presented with a textarea at the end for additional comments.
9. I can resize the textarea vertically but not horizontally.
10. If I submit without a required field filled out I get an error message by the field.

**Comment by QuincyLarson** [comment]
@IsaacAbrahamson this is a great start! Here are the ones of these that I think are doable:

2. At least one field should be required.
3. I can enter my name into a text box.
4. I can select an option from a dropdown.
5. I can select a field from a series of radio-buttons.
6. I can select several fields from a series of check-boxes.
7. I am presented with a textarea at the end for additional comments.
9. If I submit without a required field filled out I get an error message by the field.

Some of the others might seem too vague, like "I can view the page on any device" might seem to vague.

You could also add:

1. I can see a title for the survey in H1-sized text.
2. I can see a short explanation of the purpose of the form in p-sized text.

**Comment by paycoguy** [comment]
Here are the user stories that I implemented

## Content
1.  At least one input field should be required
2.  There is an input text field with id="name"
3.  I can select an option from a dropdown
4.  I can select a field from a series of radio buttons.
5.  I can select several fields from a series of checkboxes.
6.  I am presented with a textarea at the end for additional comments.

Here is the pen with my tests: http://codepen.io/paycoguy/pen/xRQbPz
And the sample project with a few changes to the ids to pass the tests: http://codepen.io/paycoguy/pen/NbEpdq

Here are the stories that I didn't implement and the reasons why:

- If I submit without a required field filled out I get an error message by the field.
If you submit the survey with no fields filled out, the error that is seen is being generated by the browser and not accessible in the DOM. 
- I can see a title for the survey in H1-sized text.  
This seems too implementation specific.  Maybe we could just have a tag with id='title'?
-I can see a short explanation of the purpose of the form in p-sized text.
The current sample page doesn't have an explanation.  Would you like me to create one?

I'd love some feedback @no-stack-dub-sack @QuincyLarson

**Comment by no-stack-dub-sack** [comment]
@paycoguy so far so good! So for your first bullet - are you saying if you programmatically try to submit the form those are the error messages you get? I'm on mobile right now with poor service so haven't really gotten to look at the code yet. But if that's what you mean, we should be able to just fill out the forms with mock data through the tests. I had to do something similar for the recipe box tests  (which we are no longer using). If you go with your suggestion, just make sure you confirm there's actually text in the element.

Lastly, yeah, go ahead and add that description to the pen so we can test that one. Always good to have a description!

For the second piece - I'm not too concerned about requiring an H1. I don't think it's overly restricting, but on the other hand, I'm not too concerned if we dont. Feel free to change the pen and make the call as you see fit.

**Comment by QuincyLarson** [comment]
@paycoguy 

> If I submit without a required field filled out I get an error message by the field.
If you submit the survey with no fields filled out, the error that is seen is being generated by the browser and not accessible in the DOM.

This would need to be a regex check for something like:

```
type="email" required
```

> I can see a title for the survey in H1-sized text.

It's a good practice for web pages to use H1 and H2 elements for search engine optimization and accessibility. I say we just verify that an H1 attribute exists on the page.

> I can see a short explanation of the purpose of the form in p-sized text.

We can probably eliminate this completely.

**Comment by no-stack-dub-sack** [comment]
@paycoguy - I misunderstood your first point in your last post so disregard the first part of my last comment. I didn't realize the first line of that bullet was the user story. I think what @QuincyLarson suggested above makes sense and should be doable - except instead of regex, you can write an assert that checks for the "required" attribute: `assert.strictEqual(document.getElementById("id_here").hasAttribute('required'), true, 'error message...');`

**Comment by paycoguy** [comment]
@QuincyLarson @no-stack-dub-sack Thanks for the helpful responses!

I added the following 2 user stories to the test code and sample project 

7.  I can see a title with id="title" in H1 sized text
8. I can see a short explanation with id="description" in P sized text

> you can write an assert that checks for the "required" attribute: 
The first user story already checks for this.  Do you think this is enough?

**Comment by QuincyLarson** [comment]
@paycoguy Looks good.

> you can write an assert that checks for the "required" attribute:
> The first user story already checks for this. Do you think this is enough?

It should not only be required but should have some HTML5 validation type.

**Comment by no-stack-dub-sack** [comment]
@paycoguy I think maybe we could get a little more specific with the first user story. Instead of asking that they make at least one field required, lets just tell them which fields to require instead, and then like Quincy said, make sure they define a type as well for the required fields.

Thoughts? It might mean re-working in a bit, but I think it would be a better test suite for it.

**Comment by paycoguy** [comment]
@QuincyLarson @no-stack-dub-sack 

I agree that we should tell them which fields are required.  I decided on making the name and email fields required.  The email field should be HTML5 validated.  I also added an HTML5 validated number field requirement.   Here are the user stories I have right now:

1.  I can see a title with id="title" in H1 sized text
2.  I can see a short explanation with id="description" in P sized text
3.  There is a required input text field with id="name"
4.  There is a required HTML5 validated email field with id="email"
5.  There is an HTML5 validated number field with id="number". This field should have a defined minimum and maximum range
6.  I can select an option from a dropdown
7.  I can select a field from a series of radio buttons.
8.  I can select several fields from a series of checkboxes.
9.  I am presented with a textarea at the end for additional comments.

Let me know what you all think!

**Comment by QuincyLarson** [comment]
Hi Andre,

These look great!

I would also try to word the actual user story instructions to be something
like "I am required to input a valid email address by an HTML5 validation"
so we can keep these user stories user-centric (rather than stating them as
a requirement.)

- Quincy Larson
teacher at FreeCodeCamp.com

Follow my writing about technology:
medium.com/@quincylarson
quora.com/profile/Quincy-Larson
<http://quora.com/profile/Quincy-Larson/answers?sort=views>

**Comment by paycoguy** [comment]
That makes sense.  Here is the new list of user stories.  Let me know what you think!

1.  I can see a title with id="title" in H1 sized text 
2.  I can see a short explanation with id="description" in P sized text 
3.  I am required to enter my name in a field with id="name" 
4.  I am required to enter an email in a field with id="email". 
5.  If I enter an email that is not formatted correctly, I will see an HTML5 validation error. 
6.  I can enter a number in a field with id="number" 
7.  If I enter non-numbers in a number field, I will see an HTML5 validation error 
8.  If I enter numbers outside the range of the number field, I will see an HTML5 validation error 
9.  I can select an option from a dropdown 
10.  I can select a field from a series of radio buttons 
11.  I can select several fields from a series of checkboxes 
12.  I am presented with a textarea at the end for additional comments

**Comment by no-stack-dub-sack** [comment]
@paycoguy These look great to me! And I see that all 12 tests are written and passing - am I good to integrate these into the master and push over to QA?

**Comment by paycoguy** [comment]
Yup go ahead!

**Comment by no-stack-dub-sack** [comment]
@paycoguy Awesome, will do.

**Comment by no-stack-dub-sack** [comment]
@paycoguy hmmm... I just thought of this - if we are going to reinforce best practices for these projects, how do you feel about adding a test that says something like: 

- I can see a corresponding label for each input field included in the survey form.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @paycoguy As long as both of you are ok with the two last minute stories and tests I added (9 & 10), we can go ahead and push this over to QA! Here's the final user stories and links. I think we can safely forgo any layout tests for this project since the main purpose is familiarizing campers with form best practices. 

example project: http://codepen.io/FCC_test_suites/full/KNEQNz
pen to fork: http://codepen.io/FCC_test_suites/pen/QGMMZO

## User Stories
1.  I can see a title with `id="title"` in H1 sized text. 
2.  I can see a short explanation with `id="description"` in P sized text. 
3.  I am required to enter my name in a field with `id="name"`.
4.  I am required to enter an email in a field with `id="email"`. 
5.  If I enter an email that is not formatted correctly, I will see an HTML5 validation error. 
6.  I can enter a number in a field with `id="number"`.
7.  If I enter non-numbers in a number field, I will see an HTML5 validation error. 
8.  If I enter numbers outside the range of the number field, I will see an HTML5 validation error. 
9. For the name, email, and number input fields, I can see corresponding labels that describe the purpose of each field with the following ids: `id="name-label"`, `id="email-label"`, and `id="number-label"`.
10. For the name, email, and number input fields, I can see placeholder text that gives me a description or instructions for each field.
9.  I can select an option from a dropdown. 
10.  I can select a field from a series of radio buttons. 
11.  I can select several fields from a series of checkboxes. 
12.  I am presented with a `<textarea>` at the end for additional comments.

**Comment by no-stack-dub-sack** [comment]
@paycoguy one last quick note - I've changed all of your `assert.equal()`s to `assert.strictEqual()` for consistency/maintainability and just to avoid any random potential issues.

**Comment by paycoguy** [comment]
Sure no problem.  I'll be sure to do that for future tests.

**Comment by no-stack-dub-sack** [comment]
@paycoguy Are you cool with the couple of user stories I added? I think issue #63 looks like its coming along nicely!

**Comment by paycoguy** [comment]
Yes those stories look great!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson - just wanted to make sure you caught this one - also ready for QA. See above.

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
