### ISSUE TITLE
Testable User Stories: Product Landing Page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#71]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to create user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

Here's the newly designed version of this project: https://s.codepen.io/atjonathan/debug/wWZxVA

Here are the old agile use stories for this challenge:

- When I arrive at the product landing page, I can click buttons in the navbar that will take me to the corresponding section of the landing page (features, pricing, email sign up)
- I can watch an embedded product video
- There is a form field where I can enter an email address.
- The form uses HTML5 validation to confirm that the entered text is an email address
- Upon clicking the button, it will post to a static page on FCC that confirms the email address entered (and that it posted successfully)

**Comment by paycoguy** [comment]
# User Stories

## Content
1.  My product landing page should have a navigation bar with id="navigation"
2.  I can click buttons in the navigation bar that will take me to the corresponding section of the landing page
3.  I can watch an embedded product video with id="video".
4.  There is an input field with id="email" where I can enter an email address.
5.  The email input field uses HTML5 validation to confirm that the entered text is an email address
6.  Upon clicking the button, it will post to a static page on FCC that confirms the email address entered (and that it posted successfully)

Here is the pen with our tests: http://codepen.io/paycoguy/pen/xRQbPz
And the sample project with a few changes to the ids/classes to pass the tests: http://codepen.io/paycoguy/pen/XNyJzV

We'd love some feedback @no-stack-dub-sack @QuincyLarson

**Comment by no-stack-dub-sack** [comment]
@paycoguy @Christian-Paul Hey guys! Nice job - but a few changes need to be made (also, the test suite is not working right now with your link - I had to pull the tests into the master to see them working - I'm guessing this is because someone is working on that pen currently but not sure...). 

I'll can make the necessary changes in the master suite as I integrate it in if that's ok with you both. These are the things I'm going to look at are: 

1. Test 2: A couple of things here:
    - We need to tell the campers in the user story that their buttons must have a class of "nav-link" - easy fix there!
    - Also, this code: `var linkDestination = navLink.getAttribute('href').split('').splice(1).join('');` looks like it can be simplified to `var testLink = navLink.getAttribute('href').slice(1);`
    - Going to add error messages so campers know where they are going wrong if they miss something.
2. Test 3: I think we can go a bit further and test for an `<iframe>` element to be sure there is some media embedded there. 
3. Test 6: should we provide them with the mock FCC url in the user story so they know the URL doesn't need to be real? I know this was an earlier user story - so not sure if Quincy had in mind an actual mailing list URL for this one...

I think we might re-word that last one a bit so its not as confusing... 

Thanks for all the work on these guys! Looking great so far. I will make these changes when I integrate it into the master script if that's ok with you both.

**Comment by Christian-Paul** [comment]
@paycoguy Thanks!

2. If we're testing for iframe, we should also test for a video element in case they use that instead.

3. I think we should include a mock URL just to avoid any potential confusion

As for making changes, that's fine by me!

**Comment by no-stack-dub-sack** [comment]
@paycoguy Agreed on both counts, especially about the video element, I will include that as well. Good call.

**Comment by no-stack-dub-sack** [comment]
1. My product landing page should have a `<nav>` element with corresponding `id="nav-bar"`.
2. I can see at least three clickable elements inside the nav bar, each with a corresponding `class` of `"nav-link"`.
3. When I click a `.nav-link` button in the nav bar, I am taken to the corresponding section of the landing page.
4. I can watch an embedded product video with `id="video"`.
5. My landing page has a `<form>` element with a corresponding `id="form"`.
6. Within the form, there is an `<input>` field with `id="email"` where I can enter an email address.
7. The `#email` input field should have placeholder text to let the user know what the field is for.
8. The `#email` input field uses HTML5 validation to confirm that the entered text is an email address.
9. Within the form, there is an submit `<input>` with corresponding `id="submit"`.
10. When I click the `#submit` button, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered (and that it posted successfully).

**Comment by no-stack-dub-sack** [comment]
...updating this post shortly, making some last minute changes

## Final User Stories
1. My product landing page should have a `<nav>` element with corresponding `id="nav-bar"`.
2. I can see at least three clickable elements inside the nav bar, each with a corresponding `class` of `"nav-link"`.
3. When I click a `.nav-link` button in the nav bar, I am taken to the corresponding section of the landing page.
4. I can watch an embedded product video with `id="video"`.
5. My landing page has a `<form>` element with a corresponding `id="form"`.
6. Within the form, there is an `<input>` field with `id="email"` where I can enter an email address.
7. The `#email` input field should have placeholder text to let the user know what the field is for.
8. The `#email` input field uses HTML5 validation to confirm that the entered text is an email address.
9. Within the form, there is an submit `<input>` with corresponding `id="submit"`.
10. When I click the `#submit` button, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered (and that it posted successfully).

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul @paycoguy So, I was going to push this out to QA - then I realized we didn't have any layout user stories, and since this is going to be in the responsive web design section, I figured we should at least have a couple. So I went to borrow the tests from @Christian-Paul 's Portfolio project tests and I noticed a couple of problems: 

- the nav-bar test could potentially fail even if a user is doing it right if they have a margin set on the nav element (I think?). I made the landing page project have a fixed nav bar and applied the test but it failed and I think this is why. 
- The media query test fails in full page mode because codepen isn't using the same class name on the style sheet. Also, when I realized this is how the test was working, I realized we have to scrap that method regardless - we are not requiring these projects to be done on codepen. Someone could theoretically develop it locally and still pull in the test scripts is script tags. So we can't rely on anything CodePen specific to run the tests. This seems like it might be a tricky one.

Either of you guys have any idea how these might be fixed?

The tests for both are now in the master script here: http://codepen.io/FCC_test_suites/pen/qqmGXr?editors=0010

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack 

1. I tried to replicate that but couldn't: the method used for determining the position is getBoundingClientRect, which doesn't take margin into consideration. (http://help.dottoro.com/ljvmcrrn.php) I'll keep trying to replicate it.

2. This was definitely the trickiest one I've faced so far. My initial solution was to iterate through each element and collect their style values that are likely to change (display, font-size, etc), then to change the width of the viewport, repeat the collection and see if there are any differences. 

I felt that my current solution was more elegant, but it does pose the challenge of detecting the right stylesheet. I believe my current solution makes testing for a number of layout based user stories easy, so we could attempt salvage it by trying to detect which style sheet is appropriate. We could check for the presence of stylesheets with the default codepen class name, and if it's not present, look for the full screen one, then look for a stylesheet with a name we tell users to use (if developing/testing locally)

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack 

Ok, so getBoundingClientRect simply doesn't return the margin values. I think the simplest fix would be to subtract the margin-top value from our existing "distance from top" value. I'll try this out and update this comment with the code.

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul ok, cool. Sounds like you have a pretty solid handle on it. I realized that the reason the nav bar test failed when I tried to implement it in the product landing page was because the nav element was inside a header element and that's what represented the unaccounted for distance. This can of course be fixed from the landing page, but if someone does the same thing in their project, it will seem like they've met the requirement but the test will still be failing. So... I'm thinking maybe we have to specify that the nav should be the outer element, and still account for the margin issue as well. How might it also affect if body has a margin? Def lots of variables. I wonder if another approach could work that wouldn't be as specific? There's also a closeTo() or approximately() Chai assert - you can set a range that is considered an acceptable margin of error. Maybe just this is our solution? If we set a 10 or 15px margin of error, we can be reasonably sure the nav is still in the viewport and not worry too much about how they accomplish it or if the nav element is the outer element. 

Thoughts?

**Comment by Christian-Paul** [comment]
@no-stack-dub-sack Agreed, there would be a lot of variables to account for. I think the best course of action is for the user story to indicate that the outer element should have the navbar id, and to allow a margin of error. Here's the code for that:

```
      it('3. The navbar should always be at the top of the viewport', function() {
        const navbar = document.getElementById('navbar');
                        
        assert.approximately(navbar.getBoundingClientRect().top, 0, 15);

        window.scroll(0, 500);        
        assert.approximately(navbar.getBoundingClientRect().top, 0, 15, 'Navbar should be at the top of the viewport even after scrolling');
        window.scroll(0, 0); 
      });
```

Also, what did you think about the responsiveness/media query solutions?

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul This test looks good 👍 , as long a we change the user story to say that it must be the outer element. Which I can go ahead and do.

I think the thing for the media query tests could work - have you tried it yet?

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul so it would seem when code pen is in full screen mode, the stylesheet does not have a class like it does it editor view.

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul @paycoguy - Ok, I think this one's in good shape now. I wanted to also include the user story where we test that it is always at the top of the page, but in this project the <nav> element is inside a <header>, which is good practice anyway. So I added user stories to account for this, which I figure is good because we want them using HTML5 tags as much as possible anyway. So now there's a layout section which includes this test, as well as the media query test and a test that requires they use CSS flexbox at least once. I'm going to let Quincy know this one is also ready for QA!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson We have another ready for QA - I think the responsiveness tests are in decent shape. Everything needed is below:

Example project: http://codepen.io/FCC_test_suites/full/ZBVxQw/
Pen to fork: http://codepen.io/FCC_test_suites/pen/QGMMZO

## User Stories

### Content:
1. My product landing page should have a `<header>` element with corresponding `id="header"`.
2. I can see an image within the `#header` element with a corresponding `id="header-img"`.
3. Within the `<header>` element I can see a `<nav>` element with corresponding `id="nav-bar"`.
2. I can see at least three clickable elements inside the nav bar, each with a corresponding `class` of `"nav-link"`.
3. When I click a `.nav-link` button in the nav bar, I am taken to the corresponding section of the landing page.
4. I can watch an embedded product video with `id="video"`.
5. My landing page has a `<form>` element with a corresponding `id="form"`.
6. Within the form, there is an `<input>` field with `id="email"` where I can enter an email address.
7. The `#email` input field should have placeholder text to let the user know what the field is for.
8. The `#email` input field uses HTML5 validation to confirm that the entered text is an email address.
9. Within the form, there is a submit `<input>` with corresponding `id="submit"`.
10. When I click the `#submit` button, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered (and that it posted successfully).

### Layout:
1. The `<header>` element with `id="header"` should always be at the top of the viewport.
2. My product landing page should have at least one media query.
3. My product landing page should utilize CSS flexbox at least once.

**Comment by QuincyLarson** [comment]
Excellent work everyone! Here's the QA and feedback thread on our forum: https://forum.freecodecamp.com/t/product-landing-page-project-with-testable-user-stories-guinea-pigs-needed/68614

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
