### ISSUE TITLE
Quality Assurance and Information Security Project: Stock Price Checker

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#77]
We are updating the Dynamic Web App projects to focus 100% on their back ends, and adding additional quality assurance and information security user stories
These projects will no longer require a front end. Instead, all the tests will be focused on JSON APIs like the API and Microservice projects. The front end will be optional and not tested.

Note: Stock quotes can be accessed by using the Google Finance API like this: http://finance.google.com/finance/info?q=NASDAQ%3aMSFT

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
- I can pass a stock to get a pretty JSON response of that stock's current price, and how many likes it has
- I can like a stock by passing its symbol and "&like=true"
- one IP address can only like an individual single stock one time.
- I can pass two stocks to get both of their prices, and the difference in their likes

We can add more stories for additional testing and security issues.

Progress: 
- [ ] Create the list of tests
- [ ] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] To ask campers to build their own versions based off of our instructions and our boilerplate
- [ ] A series of tests added to Free Code Camp's seed files

**Comment by JosephLivengood** [comment]
**User Stories:**

- Set the content security policies to only allow loading of scripts and css from your server.
- I can GET /api/stock-prices with form data containing a Nasdaq stock ticker and recieve back an object _stockData_.
- In stockData, I can see the _stock_(string, the ticker), _price_(decimal in string format), and _likes_(int).
- I can also pass along field _like_ as true(boolean) to have my like added to the stock(s). Only 1 like per ip should be accepted.
- If I pass along 2 stocks, the return object will be an array with both stock's info. Instead of likes, it will display rel_likes(the difference between the likes on both stocks) on both.
- A good way to receive current price is the following external API(replacing 'GOOG' with your stock): https://finance.google.com/finance/info?q=NASDAQ%3aGOOG
- All 5 functional tests are complete and passing.

**Example usage:**

```
/api/stock-prices?stock=goog
/api/stock-prices?stock=goog&like=true
/api/stock-prices?stock=goog&stock=msft
/api/stock-prices?stock=goog&stock=msft&like=true
```
**Example return:**

```
{"stockData":{"stock":"GOOG","price":"786.90","likes":1}}
{"stockData":[{"stock":"MSFT","price":"62.30","rel_likes":-1},{"stock":"GOOG","price":"786.90","rel_likes":1}]}
```


Completed passing project: https://gomix.com/#!/project/giant-chronometer
Boilerplate: https://gomix.com/#!/project/fcc-stock
Tester(ISQA_5-Nasdaq Stock Prices): https://pricey-hugger.gomix.me/


This is a smaller project but is very good experience as it involves 2-4 async processes per call making the camper use promises/callbacks before responding!

(It was pretty fun to make)

**Comment by QuincyLarson** [comment]
Here's the forum thread: https://forum.freecodecamp.com/t/stock-price-checker-project-with-testable-user-stories-guinea-pigs-needed/72753

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
