### ISSUE TITLE
Quality Assurance and Information Security Project: Anonymous Message Board

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#79]
We are updating the Dynamic Web App projects to focus 100% on their back ends, and adding additional quality assurance and information security user stories.

These projects will no longer require a front end. Instead, all the tests will be focused on JSON APIs like the API and Microservice projects. The front end will be optional and not tested.

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
- I can create a poll anonymously (something like /poll/create?question=who was the better captain&options=kirk,piccard,janeway)
- I can get a list of active polls
- I can get a list of completed polls
- I can vote on active polls
- Anyone can vote on my poll
- Only one vote can occur per poll from an single IP
- If a vote is cast and it isn't correct, the API should return an error

Progress: 
- [ ] Create the list of tests
- [ ] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] To ask campers to build their own versions based off of our instructions and our boilerplate
- [ ] A series of tests added to Free Code Camp's seed files

**Comment by JosephLivengood** [comment]
*Changed to Anon Message Board*

User Stories

- Only allow your site to be loading in an iFrame on your own pages.
- Do not allow DNS prefetching.
- Only allow your site to send the referrer for your own pages.
- I can POST a thread to a specific message board by passing form data _text_ and _delete_password_ to /api/threads/{board}.(Recommend res.redirect to board page /b/{board}) Saved will be at least __id_, _text_, _created_on_(date&time), _bumped_on_(date&time, starts same as created_on), _reported_(boolean), _delete_password_, & _replies_(array).
- I can POST a reply to a thread on a specific board by passing form data _text_, _delete_password_, & _thread_id_ to /api/replies/{board} and it will also update the bumped_on date to the comments date.(Recommend res.redirect to thread page /b/{board}/{thread_id}) In the thread's _replies_ array will be saved __id_, _text_, _created_on_, _delete_password_, & _reported_.
- I can GET an array of the most recent 10 bumped threads on the board with only the most recent 3 replies each from /api/threads/{board}. The _reported_ and _delete_passwords_ fields will not be sent to the client.
- I can GET an entire thread with all it's replies from /api/replies/{board}?thread_id={thread_id}. Also hiding the same fields the client should be see.
- I can delete a thread completely if I send a DELETE request to /api/threads/{board} and pass along the _thread_id_ & _delete_password_. (Text response will be 'incorrect password' or 'success')
- I can delete a post(just changing the text to '[deleted]' instead of removing completely like a thread) if I send a DELETE request to /api/replies/{board} and pass along the _thread_id_, _reply_id_, & _delete_password_. (Text response will be 'incorrect password' or 'success')
- I can report a thread and change it's reported value to true by sending a PUT request to /api/threads/{board} and pass along the _thread_id_. (Text response will be 'success')
- I can report a reply and change it's reported value to true by sending a PUT request to /api/replies/{board} and pass along the _thread_id_ & _reply_id_. (Text response will be 'success')
- Complete functional tests that wholly test routes and pass.

![](https://cdn.gomix.com/8f5547a1-a0d6-48f6-aa38-51753a0105f4%2FScreen%20Shot%202017-01-02%20at%201.04.10%20AM.png)

Should be last project potentially as its somewhat more complex and has a much more blank boilerplate canvas for them to implement these user stories however they want.

Passing prototype built on boilerplate: https://gomix.com/#!/project/horn-celery
Boilerplate: https://gomix.com/#!/project/fcc-message
Tester(ISQA_3-Anon Message Board): https://pricey-hugger.gomix.me/

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
