### ISSUE TITLE
Testable API and Microservice Projects: File Metadata

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#83]
We are updating the API and Microservice projects to be testable. Campers will start with a boilerplate specific to each project.

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
(to be added)

Progress: 
- [x] Edit the user stories if necessary to ensure they are testable 
- [x] Create the list of tests 
- [x] Build a prototype where all of those tests pass (to verify it can be done) 
- [ ] Ask campers to build their own versions based off of our instructions and our boilerplate
- [ ] Add tests to Free Code Camp's seed files

**Comment by Em-Ant** [comment]
### Links:
* boilerplate: TDB
* prototype: [purple-paladin](https://hyperdev.com/#!/project/purple-paladin)

### Improvements
* endpoint: `POST /api/fileanalyse - (encoding: multipart)`

**Comment by Em-Ant** [comment]
@QuincyLarson as far as I know simulating a file upload with jQuery/ajax requires the use of [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob), and [formData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) from the new WebAPI. 
These technologies are **unsupported by IE9**. Is that OK ? 
Otherwise I don't know how to test the file uploading from the client without having the user to upload a file manually. 

@Greenheart @systimotic any further information/ideas about this problem ?

**Comment by Em-Ant** [comment]
@QuincyLarson 
If you think it is OK, we are ready for QA.
* boilerplate: [roasted-season](https://hyperdev.com/#!/project/roasted-season)
* prototype: [purple-paladin](https://hyperdev.com/#!/project/purple-paladin)

tesing with [narrow-plane](https://narrow-plane.hyperdev.space/)  option `MS5 file metadata`

**Comment by QuincyLarson** [comment]
Forum thread for QA'ing this is live here: https://forum.freecodecamp.com/t/file-metadata-project-with-testable-user-stories-guinea-pigs-needed/60766

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
