### ISSUE TITLE
Testable API and Microservice Projects: Request Header

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#84]
We are updating the API and Microservice projects to be testable. Campers will start with a boilerplate specific to each project.

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
(to be added)

Progress: 
- [x] Edit the user stories if necessary to ensure they are testable
- [x] Create the list of tests 
- [x] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] Ask campers to build their own versions based off of our instructions and our boilerplate :construction: 
- [ ] Add tests to Free Code Camp's seed files

**Comment by Em-Ant** [comment]
At the moment Hyperdev doesn't report the correct caller IP, because of a bug https://support.hyperdev.com/t/get-client-external-ip-address/704
Should we wait for this to be fixed ? 

To test the api we can :

1. validate the ip with a regex
2. in the client we have access to the user agent and the accepted language  in `navigator` object. We can match the api response against its properties.

Should the API return the user-agent and the accept-language headers without any modification ?

@Greenheart what do you think ?

**Comment by Em-Ant** [comment]
To test the API output we can :

1. validate the ip with a regex
2. in the client js we have access to the user agent and the accepted language  in the `navigator` object. We can match the api response against its properties.

Should the API return the user-agent and the accept-language headers without any modification ?

@Greenheart what do you think ?

---
At the moment Hyperdev doesn't report the caller IP correctly, because of a bug https://support.hyperdev.com/t/get-client-external-ip-address/704
Should we wait for this to be fixed ?

**Comment by Greenheart** [comment]
Validating the ip using a regex feels a bit clunky but could work.
Using other headers misses the point of this micro service imho.
Waiting for a fix could work, but we never know how long it will take. We
could probably wait a month at most.

How about start by using the regex (there are good ones already made if you
search for it). Then we can use a proper solution as soon as hyperdev fixes
it.

Note: We probably want to respond to the hyperdev forum post and tell them
were interested in a fix.

måndag 21 november 2016 skrev Emanuele Antonelli <notifications@github.com>:

**Comment by Em-Ant** [comment]
@Greenheart to solve this project as it is now you need to analyse 3 objects :

1. `req.ip` or 'x-forwarded-for` header (to get the **client IP**)
2. the `user-agent` header ( to get the **client OS** )
3. the `accept-language` header (the get the **client Language** )

To obtain the output format that we have now, you have to manipulate the 2 and 3. 
I'm proposing to output them without editing, to simplify the tests.

**Comment by Greenheart** [comment]
I missed that this micro service should return other data as well as the IP.

Let's go with your solution and keep it simple - who says the project requires the IP adress at all? :relaxed:

**Comment by Em-Ant** [comment]
I have tests and a working example. The only thing that I don't like is the regex that I used to validate the ipv6 IP format. 
@Greenheart any thoughts/improvements ?

**Comment by Greenheart** [comment]
Nice work from the hyperdev team, just in time! :100:
@En-Ant Do you mean the server side or for the tests?

How about using [this library](https://github.com/beaugunderson/ip-address) or even something like [these regexes](https://stackoverflow.com/questions/23483855/javascript-regex-to-validate-ipv4-and-ipv6-address-no-hostnames)? :blush:

**Comment by Em-Ant** [comment]
The regex, despite being ultra-long, unfortunately doesn't seem to work...
To use external libraries we need them to be made available to the fcc client.

**Comment by Greenheart** [comment]
Haha oops.

What about looking at the source code for the library and just using their
validation-code?

tisdag 22 november 2016 skrev Emanuele Antonelli <notifications@github.com>:

**Comment by Em-Ant** [comment]
@QuincyLarson 

This should be ready for QA for now. We can fix/improve the ip regex when we'll import the tests into seeds

Boilerplate : https://hyperdev.com/#!/project/shard-weed
Working project: https://hyperdev.com/#!/project/dandelion-roar

It can be tested on [narrow-plane](https://narrow-plane.hyperdev.space/) selecting the option `MS_2 header parser`

**Comment by QuincyLarson** [comment]
I've encouraged campers to try building this on the forum here: https://forum.freecodecamp.com/t/timestamp-microservice-with-testable-user-stories-guinea-pigs-needed/58955

**Comment by Em-Ant** [comment]
@QuincyLarson the forum link is wrong. It points to the **timestamp** microservice.

**Comment by QuincyLarson** [comment]
@Em-Ant I've updated the URL. Please take a look when you get a moment - a camper has already responded with feedback.

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
