### ISSUE TITLE
Learn Websockets by Building a Chat Room

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#98]

**Comment by Ethan-Arrowood** [comment]
Can I take up this project?

**Comment by picolloo** [comment]
I would like to help if I can

**Comment by Ethan-Arrowood** [comment]
@picolloo go for it! I'm going to be reviewing many of these challenges so I'd rather someone else focus on writing this one.

**Comment by QuincyLarson** [comment]
@picolloo Thanks for your patience. Yes - we would welcome your help! 

The first step is to build the project itself. Then you can work backward to break it down into steps, like this: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files#diff-99314d694942b489d28d8a6f0c3bc5a3

**Comment by picolloo** [comment]
So I'll build a 0.1.0 version for this one, thanks for helping me

**Comment by QuincyLarson** [comment]
@picolloo Awesome! Thanks for keeping us posted on your progress with this.

**Comment by picolloo** [comment]
Hey guys, I'm working on this project using Node.js with Express and serving static html/css files. I was wondering if I am doing it right to just use pure DOM Api or if I should use some framework to manipulate de page.
I know it can get the user confused but I really think that it could be good for the project.

**Comment by picolloo** [comment]
I don't really know how this project will be but I'm trying to make something that I would like to build, maybe some suggestions can help me.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, great to hear that you're making progress on this and are building something you're excited about! I'm sure your enthusiasm will really come through in your lessons.

About the framework, I think we're trying to avoid those unless the project requires it. As you mentioned, it's often better to focus on teaching one thing at a time to avoid confusion. What framework were you thinking about using?

**Comment by picolloo** [comment]
Actually I was think of how this project should be and realize that its better to make things simplest as possible, I can use just DOM Api or a Express view engine (ejs) to manipulate the page and maybe localStorage to hold relevant data during session. 

I openned a PR to show you what I've done so far and I'm all ears to suggestion and critics

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, just skimmed through your code and everything looks good so far! Would you be able to get this working on [Glitch](https://glitch.com/)? It'll be much easier for me and others to review if we can get your app up on an easily accessible site.

**Comment by picolloo** [comment]
@scissorsneedfoodtoo I'll move it to glitch as soon as possible, thank you for listening

**Comment by scissorsneedfoodtoo** [comment]
Sounds good! Looking forward to seeing it.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, were you able to move your project to Glitch or a similar platform? We'd love to see your prototype and give some feedback.

**Comment by picolloo** [comment]
I'm currently working on my fork and working to have an MVP and then move it to Glitch.

The project itself is not that hard but I'm missing time to get it done, and now that FreeCodeCamp's contribute styles changed I'l have to change some layout properties. I'll finish it in a week and send you de Glitch's link to get feedback.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, that sounds good. Please post the link to your project on Glitch when you can. Though the Contributor's Guide was added recently, a lot of it applies to the broken down project rather than the prototype itself. Don't feel pressured to make a lot of changes to your prototype! Those are just for early feedback before you start breaking the project down into steps.

**Comment by picolloo** [comment]
I'm working on this project and trying to move it to Glitch but something is going wrong when I try to clone the repo, my files do not appear, only the assets directory. 

@scissorsneedfoodtoo do you have any idea what I might be doing wrong? I'm simply creating a new project direct from my fork on github.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, I just tried it and it seems like it's not possible since you're working from a mono repo with a lot of other directories. Unfortunately cloning https://github.com/picolloo/CurriculumExpansion/tree/master/issue98-websockets doesn't work, either.

It should be up and running here: https://codesandbox.io/s/mwovmm1jx. Just had to rename `src/server.js` to `src/index.js` due to something happening behind the scenes. Feel free to fork that link and expand on it!

I played around with it a bit and everything looks good! I like the way you styled the chatroom so it looks similar to the upcoming UI overhaul. Looking forward to seeing your finished project!

**Comment by picolloo** [comment]
Oh thanks for helping me @scissorsneedfoodtoo , I'll keep working in codepen from now

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, no problem! Just let me know if there's anything else I can do. Are you working on the frontend in CodePen now?

**Comment by picolloo** [comment]
@scissorsneedfoodtoo I've already implemented the socket signals and now I'll work on frontend. 

I got a question and maybe you can help me:
I want every logged-in user to have a username that was entered on the login screen and attach it to every sended message. I don't have any storage so I tought to use LocalStorage, but I couldn't figure out how I'm suppose to deal with it since I'm using node to send message in broadcast and don't have access to the browser's localStorage.

**Comment by picolloo** [comment]
Actually maybe I found the solution, I can use express-session to keep user logged and add a logoff button to the chatroom

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, glad you found a solution! Looking forward to seeing the final chat room :+1: :+1:

**Comment by picolloo** [comment]
Hey @scissorsneedfoodtoo, is there a way to get changes made in codesandbox and push to the github repository?

**Comment by scissorsneedfoodtoo** [comment]
That's a good question! I've never done that, so I can't say for sure. Hopefully this page will help: https://codesandbox.io/docs/git

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, how's everything going? Were you able to sync your changes on CodeSandbox to your GitHub repo? Anything I can help with?

**Comment by picolloo** [comment]
@scissorsneedfoodtoo I'm working on the session task, the logged users are being saved in memory with an ID and name thanks for the express-session. Now I have to connect the user identified by the request to the socket.io but the way I did it is getting a little hard since all the users are in a list in a single file that is not accessible through the socket module.
Do you have any idea of how should I store the users? I already implemented the socket connection and every message has a sender's ID, do I have to keep these users globally?

**Comment by picolloo** [comment]
The most updated code still in codesandbox if you want to take a look.

**Comment by scissorsneedfoodtoo** [comment]
I'm not sure of the best way to store the users right now, but I'd be happy to look into it over the next few days. Perhaps a single file with a bunch of user objects would be best, as long as we can get it working with socket.io. When we start breaking this project down we might have to work with local storage to hold the user list since we want this to work offline. But anyway, that's something we can worry about later.

I believe this is the link to your CodeSandbox in case anyone else can take a look at this: https://codesandbox.io/s/k5q426knjo

**Comment by picolloo** [comment]
I have made a file that works like a db so all connected users will be placed in there. 

I'm almost finishing the project but it has some limitations that might be discussed:
- There is only one room for all users
- The only customizable is the username that is chosen in the login page

What do you think about that @scissorsneedfoodtoo?

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, that's great! Glad you found a way to store all the users locally. Looking forward to seeing your chatroom soon!

About the limitations, one chatroom for all users is totally fine. Having multiple rooms might over complicate things. And having the username be the only customization option also seems fine. This is just a simple app, so I don't think giving users the option of changing their username during the session is necessary.

**Comment by picolloo** [comment]
Hey @scissorsneedfoodtoo , I'm having some doubts about how can I link the socket.io-client with the express-socket.io-session , right now I can send messages through chat but without any username. I'll still work on this issue but it might take a little longer than I expected.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, I see. No problem, just take your time with this. Also, when I go to https://codesandbox.io/s/k5q426knjo I get an error that causes the app to crash. Is that happening on your end as well?

**Comment by picolloo** [comment]
Oh, I have moved the project from CodeSandbox because I was getting too many errors when saving and open the application even with the chat working, I don't know why it happened.
Now I'm working on VSCode in my local but still trying to link the client-socket.io to the express-session to establish a session to the user, it has been such a challenge to me and I'm learning how to do it. 

I'll move it back again to CodeSandbox to be possible to you see what I have done so far, I'm struggling with this part of the project so any help will be great.

**Comment by picolloo** [comment]
I am refactoring the project to see what I did wrong and how can I serve static html with session-socket.io, I'll bring news as soon as possible.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, alright, that sounds great! Thank you for updating us. Looking forward to hearing more news soon.

**Comment by picolloo** [comment]
The good news is that I've finally found what I was doing wrong, the bad news is that I'll have to refactor the project structure. I'll bring updates asap, thank you for being so patient @scissorsneedfoodtoo.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, no need to apologize! Thank you for continuing to work on this. Good luck with the refactor and please let us know if there's anything we can do to help.

**Comment by QuincyLarson** [comment]
@picolloo I just wanted to chime in and say this looks amazing and works great.

I encourage you to strip out everything that isn't absolutely necessary. We want as few files and as few lines of code as possible. 

For example, I found your todo list and it said:
- [ ] private rooms
- [ ] group rooms
- [ ] user avatar

These would all be awesome but I think we could probably do without these advanced features.

Thanks again for your work on this. I'm excited to get this broken down into individual tests so people can build this one line of code at a time.

**Comment by picolloo** [comment]
Hey @QuincyLarson , thank you for taking some time to see what I'm doing lately and for the advice, I am stripping out everything that I found unnecessary and keep it as simple as possible. 

Right now I'm reorganizing the project accordingly to express middlewares necessity and applying the session to the client's socket to enforce a single connection for each user. 

I had to learn a few new concepts for this project so it is being such a challenge and I'm thankful for the given opportunity.

**Comment by picolloo** [comment]
I have finally made it work, the client's socket now can send and receive messages with the right username. I had never handle session so it was a huge experience and I'm glad that I could handle it. 

For the project to be done, I have to make some adjustments on the layout and some functionalities like the logged user list. I had some trouble trying to import the project to de CodeSandbox so if you want to see how it is here is the link to my personal repo https://github.com/picolloo/CurriculumExpansion/tree/authSocket/issue98-websockets.

Thank you for the patience and the opportunity to learn. Looking forward to the final version.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, glad that you were able to get it working and have been working steadily on it. Pulled your repo and took a look, and everything seems to be working fine. No errors like on CodeSandbox.

My only suggestion would be to keep things as simple as possible. We want learners to write as much of the code as possible, including any views and styling you have. By logged users list, do you mean a list of all the users who log into the chatroom? If so, that probably isn't necessary. A simple working chatroom is more than enough for this project. I would say this project is about ready to go as is, though it would be nice to see the usernames rather than freeCodeCamp whenever a message is sent.

Looking forward to seeing the final version, too :1st_place_medal:

**Comment by picolloo** [comment]
Oh, thank you @scissorsneedfoodtoo for the feedback. 

After made the chat work as I expected I have stripped out everything I thought it's too much and made the username be shown in the message, but I forgot to merge the branch so when I get home I'll fix that and open the PR on the FCC repo.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, awesome! Saw your PR yesterday and I'm looking forward to going through it.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, thanks for your patience. Just merged your PR and I'm happy that we got it into the repo. If you have some time to hop on a call later this week, please send me an email at kris@freecodecamp.org. I'd be happy to talk more about your project and answer any questions you might have before you finish breaking it down into steps.

**Comment by scissorsneedfoodtoo** [comment]
Hi @picolloo, just wanted to check in since our talk a little while ago. Were you able to start working on another PR for this project?

**Comment by picolloo** [comment]
Hey @scissorsneedfoodtoo, sorry for the late response, I had been really busy these weeks so I didn't have time move forward on this 'breaking into steps' part of the project. Next week I gonna have more time to dedicate to it because I'll finish a project that I'm doing to apply for a new job, I hope you understand it and I'll keep you updated.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, thank you for the update. Good luck with the job application! Just keeps us posted and I look forward to seeing your steps soon.

**Comment by picolloo** [comment]
Hey, @scissorsneedfoodtoo I started to break the project into steps and would be great to get some feedback to know if I'm doing it right. I've tried to abstract all the npm complexity and to keep it as simple as possible as you recommended.

 The link for my repo is [https://github.com/picolloo/CurriculumExpansion/tree/steps](url), thank you and we keep in touch.

**Comment by picolloo** [comment]
Hey you guys, I want to know if I can abstract the html part of client-side and focus on the client socket.io connection.

I am using some of the other projects as a guide but no other project deal with this much of files so I'm kinda doing it as I think is the best way.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, thanks for your patience.

Sure, that sounds like a good way to do it for now. Just focus on the Express and Socket.io side of things and we can always add more steps for the HTML and CSS later.

I took a quick look at your steps and it seems like you're headed in the right direction. My only suggestion would be to be more explicit in your instructions and to try and break things down even more. For example, in `server02.js` the instructions could read:

```
Declare a variable called `PORT` and set it equal to 3000. Then chain the `listen` method to `app` and pass it `PORT` as an argument.
```

**Comment by picolloo** [comment]
Alright then, I'll break the steps even more. Thanks for your help.

**Comment by scissorsneedfoodtoo** [comment]
@picolloo, great, thank you. Looking forward to seeing the rest of your steps. Please let me know if there's anything I can do to help or if you'd like more early feedback before submitting a PR.

**Comment by sultonbayevogabek** [comment]
Hi
